# CMake generated Testfile for 
# Source directory: /home/zhaodi-chen/project/uvhttp
# Build directory: /home/zhaodi-chen/project/uvhttp/build_debug
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_allocator "/home/zhaodi-chen/project/uvhttp/build_debug/dist/bin/test_allocator")
set_tests_properties(test_allocator PROPERTIES  _BACKTRACE_TRIPLES "/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;234;add_test;/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;0;")
add_test(test_async_file_full_coverage "/home/zhaodi-chen/project/uvhttp/build_debug/dist/bin/test_async_file_full_coverage")
set_tests_properties(test_async_file_full_coverage PROPERTIES  _BACKTRACE_TRIPLES "/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;234;add_test;/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;0;")
add_test(test_config_full_coverage "/home/zhaodi-chen/project/uvhttp/build_debug/dist/bin/test_config_full_coverage")
set_tests_properties(test_config_full_coverage PROPERTIES  _BACKTRACE_TRIPLES "/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;234;add_test;/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;0;")
add_test(test_connection_extended_coverage "/home/zhaodi-chen/project/uvhttp/build_debug/dist/bin/test_connection_extended_coverage")
set_tests_properties(test_connection_extended_coverage PROPERTIES  _BACKTRACE_TRIPLES "/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;234;add_test;/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;0;")
add_test(test_connection_full_coverage "/home/zhaodi-chen/project/uvhttp/build_debug/dist/bin/test_connection_full_coverage")
set_tests_properties(test_connection_full_coverage PROPERTIES  _BACKTRACE_TRIPLES "/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;234;add_test;/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;0;")
add_test(test_context_full_coverage "/home/zhaodi-chen/project/uvhttp/build_debug/dist/bin/test_context_full_coverage")
set_tests_properties(test_context_full_coverage PROPERTIES  _BACKTRACE_TRIPLES "/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;234;add_test;/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;0;")
add_test(test_context_simple "/home/zhaodi-chen/project/uvhttp/build_debug/dist/bin/test_context_simple")
set_tests_properties(test_context_simple PROPERTIES  _BACKTRACE_TRIPLES "/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;234;add_test;/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;0;")
add_test(test_cors_middleware_full_coverage "/home/zhaodi-chen/project/uvhttp/build_debug/dist/bin/test_cors_middleware_full_coverage")
set_tests_properties(test_cors_middleware_full_coverage PROPERTIES  _BACKTRACE_TRIPLES "/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;234;add_test;/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;0;")
add_test(test_deps_full_coverage "/home/zhaodi-chen/project/uvhttp/build_debug/dist/bin/test_deps_full_coverage")
set_tests_properties(test_deps_full_coverage PROPERTIES  _BACKTRACE_TRIPLES "/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;234;add_test;/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;0;")
add_test(test_error_coverage "/home/zhaodi-chen/project/uvhttp/build_debug/dist/bin/test_error_coverage")
set_tests_properties(test_error_coverage PROPERTIES  _BACKTRACE_TRIPLES "/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;234;add_test;/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;0;")
add_test(test_error_full_coverage "/home/zhaodi-chen/project/uvhttp/build_debug/dist/bin/test_error_full_coverage")
set_tests_properties(test_error_full_coverage PROPERTIES  _BACKTRACE_TRIPLES "/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;234;add_test;/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;0;")
add_test(test_error_handler_full_coverage "/home/zhaodi-chen/project/uvhttp/build_debug/dist/bin/test_error_handler_full_coverage")
set_tests_properties(test_error_handler_full_coverage PROPERTIES  _BACKTRACE_TRIPLES "/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;234;add_test;/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;0;")
add_test(test_error_helpers_full_coverage "/home/zhaodi-chen/project/uvhttp/build_debug/dist/bin/test_error_helpers_full_coverage")
set_tests_properties(test_error_helpers_full_coverage PROPERTIES  _BACKTRACE_TRIPLES "/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;234;add_test;/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;0;")
add_test(test_hash_full_coverage "/home/zhaodi-chen/project/uvhttp/build_debug/dist/bin/test_hash_full_coverage")
set_tests_properties(test_hash_full_coverage PROPERTIES  _BACKTRACE_TRIPLES "/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;234;add_test;/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;0;")
add_test(test_lru_cache_full_coverage "/home/zhaodi-chen/project/uvhttp/build_debug/dist/bin/test_lru_cache_full_coverage")
set_tests_properties(test_lru_cache_full_coverage PROPERTIES  _BACKTRACE_TRIPLES "/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;234;add_test;/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;0;")
add_test(test_mempool_full_coverage "/home/zhaodi-chen/project/uvhttp/build_debug/dist/bin/test_mempool_full_coverage")
set_tests_properties(test_mempool_full_coverage PROPERTIES  _BACKTRACE_TRIPLES "/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;234;add_test;/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;0;")
add_test(test_middleware_full_coverage "/home/zhaodi-chen/project/uvhttp/build_debug/dist/bin/test_middleware_full_coverage")
set_tests_properties(test_middleware_full_coverage PROPERTIES  _BACKTRACE_TRIPLES "/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;234;add_test;/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;0;")
add_test(test_network_full_coverage "/home/zhaodi-chen/project/uvhttp/build_debug/dist/bin/test_network_full_coverage")
set_tests_properties(test_network_full_coverage PROPERTIES  _BACKTRACE_TRIPLES "/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;234;add_test;/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;0;")
add_test(test_request_full_coverage "/home/zhaodi-chen/project/uvhttp/build_debug/dist/bin/test_request_full_coverage")
set_tests_properties(test_request_full_coverage PROPERTIES  _BACKTRACE_TRIPLES "/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;234;add_test;/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;0;")
add_test(test_request_null_coverage "/home/zhaodi-chen/project/uvhttp/build_debug/dist/bin/test_request_null_coverage")
set_tests_properties(test_request_null_coverage PROPERTIES  _BACKTRACE_TRIPLES "/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;234;add_test;/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;0;")
add_test(test_response_full_coverage "/home/zhaodi-chen/project/uvhttp/build_debug/dist/bin/test_response_full_coverage")
set_tests_properties(test_response_full_coverage PROPERTIES  _BACKTRACE_TRIPLES "/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;234;add_test;/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;0;")
add_test(test_router_full_coverage "/home/zhaodi-chen/project/uvhttp/build_debug/dist/bin/test_router_full_coverage")
set_tests_properties(test_router_full_coverage PROPERTIES  _BACKTRACE_TRIPLES "/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;234;add_test;/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;0;")
add_test(test_sendfile_timeout "/home/zhaodi-chen/project/uvhttp/build_debug/dist/bin/test_sendfile_timeout")
set_tests_properties(test_sendfile_timeout PROPERTIES  _BACKTRACE_TRIPLES "/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;234;add_test;/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;0;")
add_test(test_server_full_coverage "/home/zhaodi-chen/project/uvhttp/build_debug/dist/bin/test_server_full_coverage")
set_tests_properties(test_server_full_coverage PROPERTIES  _BACKTRACE_TRIPLES "/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;234;add_test;/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;0;")
add_test(test_static_coverage "/home/zhaodi-chen/project/uvhttp/build_debug/dist/bin/test_static_coverage")
set_tests_properties(test_static_coverage PROPERTIES  _BACKTRACE_TRIPLES "/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;234;add_test;/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;0;")
add_test(test_static_full_coverage "/home/zhaodi-chen/project/uvhttp/build_debug/dist/bin/test_static_full_coverage")
set_tests_properties(test_static_full_coverage PROPERTIES  _BACKTRACE_TRIPLES "/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;234;add_test;/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;0;")
add_test(test_tls_full_coverage "/home/zhaodi-chen/project/uvhttp/build_debug/dist/bin/test_tls_full_coverage")
set_tests_properties(test_tls_full_coverage PROPERTIES  _BACKTRACE_TRIPLES "/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;234;add_test;/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;0;")
add_test(test_tls_null_coverage "/home/zhaodi-chen/project/uvhttp/build_debug/dist/bin/test_tls_null_coverage")
set_tests_properties(test_tls_null_coverage PROPERTIES  _BACKTRACE_TRIPLES "/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;234;add_test;/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;0;")
add_test(test_utils_full_coverage "/home/zhaodi-chen/project/uvhttp/build_debug/dist/bin/test_utils_full_coverage")
set_tests_properties(test_utils_full_coverage PROPERTIES  _BACKTRACE_TRIPLES "/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;234;add_test;/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;0;")
add_test(test_validation_full_coverage "/home/zhaodi-chen/project/uvhttp/build_debug/dist/bin/test_validation_full_coverage")
set_tests_properties(test_validation_full_coverage PROPERTIES  _BACKTRACE_TRIPLES "/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;234;add_test;/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;0;")
add_test(test_websocket_full_coverage "/home/zhaodi-chen/project/uvhttp/build_debug/dist/bin/test_websocket_full_coverage")
set_tests_properties(test_websocket_full_coverage PROPERTIES  _BACKTRACE_TRIPLES "/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;234;add_test;/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;0;")
add_test(test_websocket_null_coverage "/home/zhaodi-chen/project/uvhttp/build_debug/dist/bin/test_websocket_null_coverage")
set_tests_properties(test_websocket_null_coverage PROPERTIES  _BACKTRACE_TRIPLES "/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;234;add_test;/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;0;")
add_test(test_whitelist_hash "/home/zhaodi-chen/project/uvhttp/build_debug/dist/bin/test_whitelist_hash")
set_tests_properties(test_whitelist_hash PROPERTIES  _BACKTRACE_TRIPLES "/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;234;add_test;/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;0;")
add_test(uvhttp_unit_tests "/home/zhaodi-chen/project/uvhttp/build_debug/dist/bin/uvhttp_unit_tests")
set_tests_properties(uvhttp_unit_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;247;add_test;/home/zhaodi-chen/project/uvhttp/CMakeLists.txt;0;")
subdirs("examples")
