const fs = require('fs');
const path = require('path');

const srcDir = '/home/zhaodi-chen/project/uvhttp/src';
const includeDir = '/home/zhaodi-chen/project/uvhttp/include';

// Get all C and H files
const srcFiles = fs.readdirSync(srcDir).filter(f => f.endsWith('.c'));
const includeFiles = fs.readdirSync(includeDir).filter(f => f.endsWith('.h'));
const allFiles = [...srcFiles.map(f => path.join(srcDir, f)), ...includeFiles.map(f => path.join(includeDir, f))];

// Fix words that were incorrectly split in comments
const wordPatterns = [
    { pattern: /val id ate/g, replacement: 'validate' },
    { pattern: /val id ation/g, replacement: 'validation' },
    { pattern: /alloca te/g, replacement: 'allocate' },
    { pattern: /alloca tor/g, replacement: 'allocator' },
    { pattern: /dynami c/g, replacement: 'dynamic' },
    { pattern: /dynami cally/g, replacement: 'dynamically' },
    { pattern: /c onne c tion/g, replacement: 'connection' },
    { pattern: /c onne c tions/g, replacement: 'connections' },
    { pattern: /c onne c ted/g, replacement: 'connected' },
    { pattern: /c onne c t/g, replacement: 'connect' },
    { pattern: /request s/g, replacement: 'requests' },
    { pattern: /se c onds/g, replacement: 'seconds' },
    { pattern: /se c ond/g, replacement: 'second' },
    { pattern: /maxi mum/g, replacement: 'maximum' },
    { pattern: /mini mum/g, replacement: 'minimum' },
    { pattern: /defau lt/g, replacement: 'default' },
    { pattern: /defau lts/g, replacement: 'defaults' },
    { pattern: /c he c k/g, replacement: 'check' },
    { pattern: /c he c king/g, replacement: 'checking' },
    { pattern: /c he c ked/g, replacement: 'checked' },
    { pattern: /s et/g, replacement: 'set' },
    { pattern: /s et ting/g, replacement: 'setting' },
    { pattern: /get ting/g, replacement: 'getting' },
    { pattern: /add ing/g, replacement: 'adding' },
    { pattern: /remov ing/g, replacement: 'removing' },
    { pattern: /find ing/g, replacement: 'finding' },
    { pattern: /handl ing/g, replacement: 'handling' },
    { pattern: /request ing/g, replacement: 'requesting' },
    { pattern: /respond ing/g, replacement: 'responding' },
    { pattern: /buff er/g, replacement: 'buffer' },
    { pattern: /buff ering/g, replacement: 'buffering' },
    { pattern: /cont ext/g, replacement: 'context' },
    { pattern: /time out/g, replacement: 'timeout' },
    { pattern: /time outs/g, replacement: 'timeouts' },
    { pattern: /c ache/g, replacement: 'cache' },
    { pattern: /c aching/g, replacement: 'caching' },
    { pattern: /rout er/g, replacement: 'router' },
    { pattern: /rout ing/g, replacement: 'routing' },
    { pattern: /head er/g, replacement: 'header' },
    { pattern: /head ers/g, replacement: 'headers' },
    { pattern: /point er/g, replacement: 'pointer' },
    { pattern: /point ers/g, replacement: 'pointers' },
    { pattern: /memor y/g, replacement: 'memory' },
    { pattern: /call back/g, replacement: 'callback' },
    { pattern: /call backs/g, replacement: 'callbacks' },
    { pattern: /fun c tion/g, replacement: 'function' },
    { pattern: /fun c tions/g, replacement: 'functions' },
    { pattern: /paramet er/g, replacement: 'parameter' },
    { pattern: /paramet ers/g, replacement: 'parameters' },
    { pattern: /valu e/g, replacement: 'value' },
    { pattern: /valu es/g, replacement: 'values' },
    { pattern: /lim it/g, replacement: 'limit' },
    { pattern: /lim its/g, replacement: 'limits' },
    { pattern: /err or/g, replacement: 'error' },
    { pattern: /err ors/g, replacement: 'errors' },
    { pattern: /updat e/g, replacement: 'update' },
    { pattern: /updat ing/g, replacement: 'updating' },
    { pattern: /clean up/g, replacement: 'cleanup' },
    { pattern: /clean ing/g, replacement: 'cleaning' },
    { pattern: /statist ics/g, replacement: 'statistics' },
    { pattern: /inform ation/g, replacement: 'information' },
    { pattern: /str ing/g, replacement: 'string' },
    { pattern: /str ings/g, replacement: 'strings' },
    { pattern: /char act er/g, replacement: 'character' },
    { pattern: /char act ers/g, replacement: 'characters' },
    { pattern: /oper ation/g, replacement: 'operation' },
    { pattern: /oper ations/g, replacement: 'operations' },
    { pattern: /con figur ation/g, replacement: 'configuration' },
    { pattern: /con figur ations/g, replacement: 'configurations' },
    { pattern: /manag ement/g, replacement: 'management' },
    { pattern: /manag ing/g, replacement: 'managing' },
    { pattern: /manag er/g, replacement: 'manager' },
    { pattern: /manag ers/g, replacement: 'managers' },
    { pattern: /implement ation/g, replacement: 'implementation' },
    { pattern: /implement ing/g, replacement: 'implementing' },
    { pattern: /initial ize/g, replacement: 'initialize' },
    { pattern: /initial ization/g, replacement: 'initialization' },
    { pattern: /initial ized/g, replacement: 'initialized' },
    { pattern: /initial izing/g, replacement: 'initializing' },
    { pattern: /cre ation/g, replacement: 'creation' },
    { pattern: /cre ating/g, replacement: 'creating' },
    { pattern: /cre ated/g, replacement: 'created' },
    { pattern: /destroy/g, replacement: 'destroy' },
    { pattern: /destro ying/g, replacement: 'destroying' },
    { pattern: /destro yed/g, replacement: 'destroyed' },
    { pattern: /releas e/g, replacement: 'release' },
    { pattern: /releas ing/g, replacement: 'releasing' },
    { pattern: /releas ed/g, replacement: 'released' },
    { pattern: /acquir e/g, replacement: 'acquire' },
    { pattern: /acquir ing/g, replacement: 'acquiring' },
    { pattern: /acquir ed/g, replacement: 'acquired' },
    { pattern: /loc k/g, replacement: 'lock' },
    { pattern: /loc king/g, replacement: 'locking' },
    { pattern: /loc ked/g, replacement: 'locked' },
    { pattern: /unloc k/g, replacement: 'unlock' },
    { pattern: /unloc king/g, replacement: 'unlocking' },
    { pattern: /unloc ked/g, replacement: 'unlocked' },
    { pattern: /thread/g, replacement: 'thread' },
    { pattern: /threads/g, replacement: 'threads' },
    { pattern: /thread ing/g, replacement: 'threading' },
    { pattern: /proces s/g, replacement: 'process' },
    { pattern: /proces ses/g, replacement: 'processes' },
    { pattern: /proces sing/g, replacement: 'processing' },
    { pattern: /event/g, replacement: 'event' },
    { pattern: /events/g, replacement: 'events' },
    { pattern: /async/g, replacement: 'async' },
    { pattern: /sync/g, replacement: 'sync' },
    { pattern: /sync hronous/g, replacement: 'synchronous' },
    { pattern: /async hronous/g, replacement: 'asynchronous' },
    { pattern: /block ing/g, replacement: 'blocking' },
    { pattern: /non-block ing/g, replacement: 'non-blocking' },
    { pattern: /safe/g, replacement: 'safe' },
    { pattern: /unsafe/g, replacement: 'unsafe' },
    { pattern: /stat ic/g, replacement: 'static' },
    { pattern: /dynam ic/g, replacement: 'dynamic' },
    { pattern: /glob al/g, replacement: 'global' },
    { pattern: /loc al/g, replacement: 'local' },
    { pattern: /pub lic/g, replacement: 'public' },
    { pattern: /priv ate/g, replacement: 'private' },
    { pattern: /intern al/g, replacement: 'internal' },
    { pattern: /extern al/g, replacement: 'external' },
    { pattern: /custom/g, replacement: 'custom' },
    { pattern: /user/g, replacement: 'user' },
    { pattern: /users/g, replacement: 'users' },
    { pattern: /syst em/g, replacement: 'system' },
    { pattern: /syst ems/g, replacement: 'systems' },
    { pattern: /applic ation/g, replacement: 'application' },
    { pattern: /applic ations/g, replacement: 'applications' },
    { pattern: /framewor k/g, replacement: 'framework' },
    { pattern: /framewor ks/g, replacement: 'frameworks' },
    { pattern: /librar y/g, replacement: 'library' },
    { pattern: /librar ies/g, replacement: 'libraries' },
    { pattern: /protoc ol/g, replacement: 'protocol' },
    { pattern: /protoc ols/g, replacement: 'protocols' },
    { pattern: /networ k/g, replacement: 'network' },
    { pattern: /networ ks/g, replacement: 'networks' },
    { pattern: /soc ket/g, replacement: 'socket' },
    { pattern: /soc kets/g, replacement: 'sockets' },
    { pattern: /optim iz ation/g, replacement: 'optimization' },
    { pattern: /optim ize/g, replacement: 'optimize' },
    { pattern: /optim izing/g, replacement: 'optimizing' },
    { pattern: /perform ance/g, replacement: 'performance' },
    { pattern: /secur ity/g, replacement: 'security' },
    { pattern: /secur e/g, replacement: 'secure' },
    { pattern: /avail able/g, replacement: 'available' },
    { pattern: /unavail able/g, replacement: 'unavailable' },
    { pattern: /compat ible/g, replacement: 'compatible' },
    { pattern: /incompat ible/g, replacement: 'incompatible' },
    { pattern: /requir ement/g, replacement: 'requirement' },
    { pattern: /requir ements/g, replacement: 'requirements' },
    { pattern: /requir ed/g, replacement: 'required' },
    { pattern: /requir ing/g, replacement: 'requiring' },
    { pattern: /suppor ted/g, replacement: 'supported' },
    { pattern: /unsuppor ted/g, replacement: 'unsupported' },
    { pattern: /suppor ting/g, replacement: 'supporting' },
    { pattern: /suppor t/g, replacement: 'support' },
    { pattern: /enabl ed/g, replacement: 'enabled' },
    { pattern: /disabl ed/g, replacement: 'disabled' },
    { pattern: /enabl ing/g, replacement: 'enabling' },
    { pattern: /disabl ing/g, replacement: 'disabling' },
    { pattern: /succe ss/g, replacement: 'success' },
    { pattern: /succe ssful/g, replacement: 'successful' },
    { pattern: /failur e/g, replacement: 'failure' },
    { pattern: /failur es/g, replacement: 'failures' },
    { pattern: /fail ed/g, replacement: 'failed' },
    { pattern: /fail ing/g, replacement: 'failing' },
    { pattern: /complet e/g, replacement: 'complete' },
    { pattern: /complet ed/g, replacement: 'completed' },
    { pattern: /complet ing/g, replacement: 'completing' },
    { pattern: /match ing/g, replacement: 'matching' },
    { pattern: /match ed/g, replacement: 'matched' },
    { pattern: /pars ing/g, replacement: 'parsing' },
    { pattern: /pars ed/g, replacement: 'parsed' },
    { pattern: /send ing/g, replacement: 'sending' },
    { pattern: /sent/g, replacement: 'sent' },
    { pattern: /receiv ing/g, replacement: 'receiving' },
    { pattern: /receiv ed/g, replacement: 'received' },
    { pattern: /read ing/g, replacement: 'reading' },
    { pattern: /read/g, replacement: 'read' },
    { pattern: /writ ing/g, replacement: 'writing' },
    { pattern: /wrot e/g, replacement: 'wrote' },
    { pattern: /written/g, replacement: 'written' },
    { pattern: /clos ing/g, replacement: 'closing' },
    { pattern: /clos ed/g, replacement: 'closed' },
    { pattern: /open ing/g, replacement: 'opening' },
    { pattern: /open ed/g, replacement: 'opened' },
    { pattern: /start ing/g, replacement: 'starting' },
    { pattern: /start ed/g, replacement: 'started' },
    { pattern: /stop ping/g, replacement: 'stopping' },
    { pattern: /stop ped/g, replacement: 'stopped' },
    { pattern: /reset ting/g, replacement: 'resetting' },
    { pattern: /reset/g, replacement: 'reset' },
    { pattern: /clear ing/g, replacement: 'clearing' },
    { pattern: /cleared/g, replacement: 'cleared' },
    { pattern: /cop ying/g, replacement: 'copying' },
    { pattern: /cop ied/g, replacement: 'copied' },
    { pattern: /cop y/g, replacement: 'copy' },
    { pattern: /mov ing/g, replacement: 'moving' },
    { pattern: /mov ed/g, replacement: 'moved' },
    { pattern: /build ing/g, replacement: 'building' },
    { pattern: /built/g, replacement: 'built' },
    { pattern: /creat ing/g, replacement: 'creating' },
    { pattern: /created/g, replacement: 'created' },
    { pattern: /create/g, replacement: 'create' },
    { pattern: /destro ying/g, replacement: 'destroying' },
    { pattern: /destroyed/g, replacement: 'destroyed' },
    { pattern: /destroy/g, replacement: 'destroy' },
    { pattern: /releas ing/g, replacement: 'releasing' },
    { pattern: /released/g, replacement: 'released' },
    { pattern: /release/g, replacement: 'release' },
    { pattern: /acquir ing/g, replacement: 'acquiring' },
    { pattern: /acquired/g, replacement: 'acquired' },
    { pattern: /acquire/g, replacement: 'acquire' },
    { pattern: /loc king/g, replacement: 'locking' },
    { pattern: /locked/g, replacement: 'locked' },
    { pattern: /lock/g, replacement: 'lock' },
    { pattern: /unloc king/g, replacement: 'unlocking' },
    { pattern: /unlocked/g, replacement: 'unlocked' },
    { pattern: /unlock/g, replacement: 'unlock' },
    { pattern: /thread ing/g, replacement: 'threading' },
    { pattern: /process ing/g, replacement: 'processing' },
    { pattern: /process ed/g, replacement: 'processed' },
    { pattern: /process/g, replacement: 'process' },
    { pattern: /optim izing/g, replacement: 'optimizing' },
    { pattern: /optimized/g, replacement: 'optimized' },
    { pattern: /optimize/g, replacement: 'optimize' }
];

let totalFixed = 0;

allFiles.forEach(filePath => {
    const content = fs.readFileSync(filePath, 'utf8');
    let result = content;

    wordPatterns.forEach(({pattern, replacement}) => {
        result = result.replace(pattern, replacement);
    });

    if (content !== result) {
        fs.writeFileSync(filePath, result, 'utf8');
        console.log('Fixed:', path.basename(filePath));
        totalFixed++;
    }
});

console.log('\nTotal files fixed:', totalFixed);