const fs = require('fs');
const path = require('path');

const srcDir = '/home/zhaodi-chen/project/uvhttp/src';
const includeDir = '/home/zhaodi-chen/project/uvhttp/include';

// Get all C and H files
const srcFiles = fs.readdirSync(srcDir).filter(f => f.endsWith('.c'));
const includeFiles = fs.readdirSync(includeDir).filter(f => f.endsWith('.h'));
const allFiles = [...srcFiles.map(f => path.join(srcDir, f)), ...includeFiles.map(f => path.join(includeDir, f))];

// Complete phrase translations - sorted by length (longest first)
const phraseTranslations = [
    // Documentation comments
    ['@brief UVHTTP 可配置常量定义', '@brief UVHTTP configurable constant definitions'],
    ['本文件集中了所有可配置的常量，按功能模块分类。', 'This file centralizes all configurable constants, organized by functional modules.'],
    ['==================== 配置指南 ====================', '==================== Configuration Guide ===================='],
    ['通过 CMake 编译选项或直接修改本文件中的宏定义来配置', 'Configure through CMake compile options or directly modify macro definitions in this file'],
    ['推荐使用 CMake 选项，便于维护和版本控制', 'Recommended to use CMake options for easier maintenance and version control'],
    ['性能调优建议', 'Performance tuning recommendations'],
    ['小型应用（< 1000 RPS）：使用默认配置', 'Small applications (< 1000 RPS): use default configuration'],
    ['中型应用（1000-10000 RPS）：增加连接数和缓冲区大小', 'Medium applications (1000-10000 RPS): increase connection count and buffer size'],
    ['大型应用（> 10000 RPS）：需要系统调优，参考下面的大型应用配置', 'Large applications (> 10000 RPS): require system tuning, refer to large application configuration below'],
    ['内存优化', 'Memory optimization'],
    ['内存受限环境：减小缓冲区大小，禁用缓存', 'Memory-constrained environments: reduce buffer size, disable cache'],
    ['高性能环境：增加缓冲区大小，启用所有缓存', 'High-performance environments: increase buffer size, enable all caches'],
    ['==================== 配置示例 ====================', '==================== Configuration Examples ===================='],
    ['小型应用配置（内存优先）：', 'Small application configuration (memory priority):'],
    ['中型应用配置（平衡）：', 'Medium application configuration (balanced):'],
    ['大型应用配置（性能优先）：', 'Large application configuration (performance priority):'],
    ['==================== 系统调优 ====================', '==================== System Tuning ===================='],
    ['对于大型应用（> 10000 RPS），需要调整系统参数：', 'For large applications (> 10000 RPS), system parameters need to be adjusted:'],
    ['Linux 系统参数优化：', 'Linux system parameter optimization:'],
    ['应用限制', 'Application limits'],
    ['==================== 注意事项 ====================', '==================== Notes ===================='],
    ['修改常量后需要重新编译', 'Recompilation required after modifying constants'],
    ['某些常量的修改可能影响二进制兼容性', 'Modifying certain constants may affect binary compatibility'],
    ['增加缓冲区大小会增加内存使用', 'Increasing buffer size will increase memory usage'],
    ['连接数受限于系统文件描述符数量', 'Connection count is limited by system file descriptor count'],
    ['包含默认配置值', 'Contains default configuration values'],
    
    // Server comments
    ['单线程事件驱动连接处理回调', 'Single-threaded event-driven connection handling callback'],
    ['这是libuv事件循环的核心回调函数，处理所有新连接', 'This is the core callback function of the libuv event loop, handling all new connections'],
    ['单线程模型优势：无需锁，数据访问安全，执行流可预测', 'Single-threaded model advantages: no locks needed, safe data access, predictable execution flow'],
    ['写请求对象', 'write request object'],
    ['写操作状态', 'write operation status'],
    ['服务器句柄', 'server handle'],
    ['连接状态', 'connection status'],
    ['单线程连接数检查 - 使用服务器特定配置', 'Single-threaded connection count check - using server-specific configuration'],
    ['默认值', 'default value'],
    ['回退到全局配置(使用 server->context)', 'Fallback to global configuration (using server->context)'],
    ['创建临时连接以发送503响应', 'Create temporary connection to send 503 response'],
    ['发送HTTP 503响应 - 使用静态常量避免重复分配', 'Send HTTP 503 response - using static constants to avoid repeated allocation'],
    ['如果写入失败,立即释放write_req并关闭连接', 'If write fails, immediately free write_req and close connection'],
    ['创建新的连接对象 - 单线程分配,无需同步', 'Create new connection object - single-threaded allocation, no synchronization needed'],
    ['接受连接', 'Accept connection'],
    ['请求和响应对象已在连接创建时初始化', 'Request and response objects are initialized when connection is created'],
    ['单线程安全的连接计数递增', 'Single-threaded safe connection count increment'],
    ['开始连接处理(TLS握手或HTTP读取)', 'Start connection processing (TLS handshake or HTTP read)'],
    ['所有后续处理都通过libuv回调在事件循环中异步进行', 'All subsequent processing is done asynchronously through libuv callbacks in the event loop'],
    ['创建基于单线程事件驱动的HTTP服务器', 'Create single-threaded event-driven HTTP server'],
    ['libuv事件循环，如果为NULL则创建新的事件循环', 'libuv event loop, create new event loop if NULL'],
    ['服务器对象，所有操作都在单个事件循环线程中进行', 'Server object, all operations are performed in a single event loop thread'],
    ['单线程设计优势：', 'Single-threaded design advantages:'],
    ['无需锁机制，避免死锁和竞态条件', 'No locking mechanism needed, avoid deadlocks and race conditions'],
    ['内存访问更安全，无需原子操作', 'Memory access is safer, no atomic operations needed'],
    ['性能可预测，避免线程切换开销', 'Performance is predictable, avoid thread switching overhead'],
    ['调试简单，执行流清晰', 'Debugging is simple, execution flow is clear'],
    ['初始化TLS模块(如果还没有初始化)', 'Initialize TLS module (if not already initialized)'],
    ['使用全局变量以保持向后兼容性', 'Use global variables to maintain backward compatibility'],
    ['新项目应使用 uvhttp_context 进行 TLS 配置', 'New projects should use uvhttp_context for TLS configuration'],
    
    // Common phrases
    ['默认', 'default'],
    ['最大', 'maximum'],
    ['最小', 'minimum'],
    ['配置', 'configuration'],
    ['初始化', 'initialize'],
    ['释放', 'release'],
    ['创建', 'create'],
    ['删除', 'delete'],
    ['添加', 'add'],
    ['移除', 'remove'],
    ['获取', 'get'],
    ['设置', 'set'],
    ['检查', 'check'],
    ['验证', 'validate'],
    ['更新', 'update'],
    ['处理', 'handle'],
    ['返回', 'return'],
    ['参数', 'parameter'],
    ['值', 'value'],
    ['错误', 'error'],
    ['成功', 'success'],
    ['失败', 'failure'],
    ['警告', 'warning'],
    ['注意', 'note'],
    ['建议', 'recommendation'],
    ['示例', 'example'],
    ['包含', 'include'],
    ['支持', 'support'],
    ['禁用', 'disable'],
    ['启用', 'enable'],
    ['可选', 'optional'],
    ['必需', 'required'],
    ['建议', 'suggested'],
    ['推荐', 'recommended'],
    ['基于', 'based on'],
    ['用于', 'used for'],
    ['适用于', 'applicable to'],
    ['如果', 'if'],
    ['否则', 'else'],
    ['当', 'when'],
    ['然后', 'then'],
    ['之后', 'after'],
    ['之前', 'before'],
    ['同时', 'simultaneously'],
    ['另外', 'additionally'],
    ['此外', 'furthermore'],
    ['因此', 'therefore'],
    ['所以', 'so'],
    ['但是', 'however'],
    ['虽然', 'although'],
    ['因为', 'because'],
    ['由于', 'due to'],
    ['通过', 'through'],
    ['使用', 'use'],
    ['利用', 'utilize'],
    ['采用', 'adopt'],
    ['实现', 'implement'],
    ['执行', 'execute'],
    ['运行', 'run'],
    ['启动', 'start'],
    ['停止', 'stop'],
    ['关闭', 'close'],
    ['打开', 'open'],
    ['读取', 'read'],
    ['写入', 'write'],
    ['发送', 'send'],
    ['接收', 'receive'],
    ['连接', 'connect'],
    ['断开', 'disconnect'],
    ['请求', 'request'],
    ['响应', 'response'],
    ['服务器', 'server'],
    ['客户端', 'client'],
    ['网络', 'network'],
    ['协议', 'protocol'],
    ['接口', 'interface'],
    ['函数', 'function'],
    ['方法', 'method'],
    ['变量', 'variable'],
    ['常量', 'constant'],
    ['类型', 'type'],
    ['结构', 'structure'],
    ['对象', 'object'],
    ['指针', 'pointer'],
    ['缓冲区', 'buffer'],
    ['内存', 'memory'],
    ['线程', 'thread'],
    ['进程', 'process'],
    ['事件', 'event'],
    ['循环', 'loop'],
    ['回调', 'callback'],
    ['处理', 'handler'],
    ['管理器', 'manager'],
    ['上下文', 'context'],
    ['状态', 'state'],
    ['模式', 'mode'],
    ['选项', 'option'],
    ['特性', 'feature'],
    ['模块', 'module'],
    ['组件', 'component'],
    ['系统', 'system'],
    ['应用程序', 'application'],
    ['框架', 'framework'],
    ['库', 'library'],
    ['工具', 'tool'],
    ['脚本', 'script'],
    ['文档', 'documentation'],
    ['注释', 'comment'],
    ['代码', 'code'],
    ['测试', 'test'],
    ['调试', 'debug'],
    ['日志', 'log'],
    ['错误处理', 'error handling'],
    ['资源管理', 'resource management'],
    ['内存管理', 'memory management'],
    ['连接管理', 'connection management'],
    ['线程安全', 'thread safety'],
    ['性能优化', 'performance optimization'],
    ['安全', 'security'],
    ['稳定性', 'stability'],
    
    // Technical terms
    ['事件循环', 'event loop'],
    ['单线程', 'single-threaded'],
    ['多线程', 'multi-threaded'],
    ['异步', 'asynchronous'],
    ['同步', 'synchronous'],
    ['阻塞', 'blocking'],
    ['非阻塞', 'non-blocking'],
    ['并发', 'concurrent'],
    ['串行', 'serial'],
    ['并发数', 'concurrency'],
    ['吞吐量', 'throughput'],
    ['延迟', 'latency'],
    ['超时', 'timeout'],
    ['重试', 'retry'],
    ['缓冲', 'buffering'],
    ['缓存', 'cache'],
    ['路由', 'routing'],
    ['路由器', 'router'],
    ['中间件', 'middleware'],
    ['处理器', 'handler'],
    ['拦截器', 'interceptor'],
    ['过滤器', 'filter'],
    ['验证器', 'validator'],
    ['解析器', 'parser'],
    ['生成器', 'generator'],
    ['序列化', 'serialization'],
    ['反序列化', 'deserialization'],
    ['编码', 'encoding'],
    ['解码', 'decoding'],
    ['加密', 'encryption'],
    ['解密', 'decryption'],
    ['签名', 'signature'],
    ['验证', 'verification'],
    ['认证', 'authentication'],
    ['授权', 'authorization'],
    ['权限', 'permission'],
    ['角色', 'role'],
    ['用户', 'user'],
    ['会话', 'session'],
    ['令牌', 'token'],
    ['密钥', 'key'],
    ['证书', 'certificate'],
    ['握手', 'handshake'],
    ['连接池', 'connection pool'],
    ['线程池', 'thread pool'],
    ['对象池', 'object pool'],
    ['内存池', 'memory pool'],
    ['文件描述符', 'file descriptor'],
    ['套接字', 'socket'],
    ['端口', 'port'],
    ['主机', 'host'],
    ['地址', 'address'],
    ['路径', 'path'],
    ['查询参数', 'query parameter'],
    ['请求体', 'request body'],
    ['响应体', 'response body'],
    ['请求头', 'request header'],
    ['响应头', 'response header'],
    ['状态码', 'status code'],
    ['内容类型', 'content type'],
    ['内容长度', 'content length'],
    ['长连接', 'keep-alive'],
    ['短连接', 'short connection'],
    
    // Adjectives
    ['有效的', 'valid'],
    ['无效的', 'invalid'],
    ['安全的', 'safe'],
    ['不安全的', 'unsafe'],
    ['可用的', 'available'],
    ['不可用的', 'unavailable'],
    ['必需的', 'required'],
    ['可选的', 'optional'],
    ['推荐的', 'recommended'],
    ['建议的', 'suggested'],
    ['默认的', 'default'],
    ['自定义的', 'custom'],
    ['标准的', 'standard'],
    ['规范的', 'standardized'],
    ['优化的', 'optimized'],
    ['高效的', 'efficient'],
    ['高性能的', 'high-performance'],
    ['低延迟的', 'low-latency'],
    ['高吞吐量的', 'high-throughput'],
    ['可扩展的', 'scalable'],
    ['可维护的', 'maintainable'],
    ['可读的', 'readable'],
    ['可靠的', 'reliable'],
    ['稳定的', 'stable'],
    ['不稳定的', 'unstable'],
    ['兼容的', 'compatible'],
    ['不兼容的', 'incompatible'],
    ['独立的', 'independent'],
    ['依赖的', 'dependent'],
    ['相关的', 'related'],
    ['无关的', 'unrelated'],
    ['相似的', 'similar'],
    ['不同的', 'different'],
    ['相同的', 'same'],
    ['相等的', 'equal'],
    ['不等的', 'unequal'],
    
    // Action verbs
    ['分配', 'allocate'],
    ['构建', 'build'],
    ['编译', 'compile'],
    ['链接', 'link'],
    ['加载', 'load'],
    ['卸载', 'unload'],
    ['安装', 'install'],
    ['配置', 'configure'],
    ['启动', 'start'],
    ['停止', 'stop'],
    ['暂停', 'pause'],
    ['恢复', 'resume'],
    ['重启', 'restart'],
    ['重载', 'reload'],
    ['刷新', 'refresh'],
    ['升级', 'upgrade'],
    ['降级', 'downgrade'],
    ['迁移', 'migrate'],
    ['转换', 'convert'],
    ['格式化', 'format'],
    ['渲染', 'render'],
    ['显示', 'display'],
    ['隐藏', 'hide'],
    ['允许', 'allow'],
    ['禁止', 'forbid'],
    ['拒绝', 'reject'],
    ['接受', 'accept'],
    ['忽略', 'ignore'],
    ['跳过', 'skip'],
    ['继续', 'continue'],
    ['中断', 'interrupt'],
    ['中止', 'abort'],
    ['终止', 'terminate'],
    ['完成', 'complete'],
    ['出错', 'error out'],
    ['崩溃', 'crash'],
    ['挂起', 'hang'],
    ['阻塞', 'block'],
    ['等待', 'wait'],
    ['通知', 'notify'],
    ['触发', 'trigger'],
    ['调用', 'call'],
    ['操作', 'operate'],
    ['管理', 'manage'],
    ['控制', 'control'],
    ['监控', 'monitor'],
    ['观察', 'observe'],
    ['记录', 'record'],
    ['跟踪', 'track'],
    ['调试', 'debug'],
    ['测试', 'test'],
    ['验证', 'verify'],
    ['确认', 'confirm'],
    ['确定', 'determine'],
    ['决定', 'decide'],
    ['选择', 'choose'],
    
    // Single characters
    ['（', '('],
    ['）', ')'],
    ['，', ','],
    ['。', '.'],
    ['：', ':'],
    ['；', ';'],
    ['【', '['],
    ['】', ']'],
    ['《', '<'],
    ['》', '>'],
    ['"', '"'],
    ['"', '"'],
    ['\'', '\''],
    ['\'', '\'']
];

let totalTranslated = 0;

allFiles.forEach(filePath => {
    const content = fs.readFileSync(filePath, 'utf8');
    let result = content;
    let changes = 0;
    
    // Only process lines that are comments
    const lines = result.split('\n');
    const processedLines = lines.map(line => {
        // Check if line contains Chinese characters
        if (/[一-龥]/.test(line)) {
            let processedLine = line;
            
            // Apply translations
            phraseTranslations.forEach(([chinese, english]) => {
                const regex = new RegExp(chinese.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g');
                if (regex.test(processedLine)) {
                    processedLine = processedLine.replace(regex, english);
                    changes++;
                }
            });
            
            return processedLine;
        }
        return line;
    });

    result = processedLines.join('\n');

    if (content !== result) {
        fs.writeFileSync(filePath, result, 'utf8');
        console.log('Translated:', path.basename(filePath), `(${changes} changes)`);
        totalTranslated++;
    }
});

console.log('\nTotal files translated:', totalTranslated);
console.log('Total translation patterns:', phraseTranslations.length);
