const fs = require('fs');
const path = require('path');

// Comprehensive translation dictionary for remaining Chinese comments
const translations = {
    // Configuration documentation
    '配置建议': 'Configuration recommendation',
    '配置说明': 'Configuration description',
    '配置选项': 'Configuration option',
    '配置参数': 'Configuration parameter',
    '配置值': 'Configuration value',
    '配置文件': 'Configuration file',
    '配置项': 'Configuration item',
    
    // Impact and effects
    '影响': 'Impact',
    '影响范围': 'Impact scope',
    '影响性能': 'Impact performance',
    '影响内存': 'Impact memory',
    '影响延迟': 'Impact latency',
    
    // CMake configuration
    'CMake 配置': 'CMake configuration',
    'CMake 选项': 'CMake option',
    '编译选项': 'Compile option',
    '编译配置': 'Compile configuration',
    '编译宏': 'Compile macro',
    
    // Safety and limits
    '安全边距': 'Safety margin',
    '安全限制': 'Safety limit',
    '安全检查': 'Safety check',
    '安全边界': 'Safety boundary',
    '最大值': 'Maximum value',
    '最小值': 'Minimum value',
    '默认值': 'Default value',
    '推荐值': 'Recommended value',
    
    // Performance
    '性能优先': 'Performance priority',
    '内存优先': 'Memory priority',
    '性能优化': 'Performance optimization',
    '性能影响': 'Performance impact',
    '性能指标': 'Performance metric',
    
    // Buffer and memory
    '缓冲区': 'Buffer',
    '缓冲区大小': 'Buffer size',
    '缓冲区溢出': 'Buffer overflow',
    '内存分配': 'Memory allocation',
    '内存释放': 'Memory deallocation',
    '内存泄漏': 'Memory leak',
    
    // Network
    '网络连接': 'Network connection',
    '网络接口': 'Network interface',
    '网络地址': 'Network address',
    '网络协议': 'Network protocol',
    
    // Server
    '服务器': 'Server',
    '服务器实例': 'Server instance',
    '服务器配置': 'Server configuration',
    '服务器启动': 'Server startup',
    
    // Client
    '客户端': 'Client',
    '客户端连接': 'Client connection',
    '客户端请求': 'Client request',
    
    // Request and response
    '请求': 'Request',
    '请求处理': 'Request handling',
    '请求头': 'Request header',
    '请求体': 'Request body',
    '响应': 'Response',
    '响应处理': 'Response handling',
    '响应头': 'Response header',
    '响应体': 'Response body',
    
    // Router
    '路由': 'Router',
    '路由匹配': 'Route matching',
    '路由参数': 'Route parameter',
    '路由表': 'Route table',
    
    // Cache
    '缓存': 'Cache',
    '缓存命中': 'Cache hit',
    '缓存未命中': 'Cache miss',
    '缓存策略': 'Cache policy',
    '缓存大小': 'Cache size',
    
    // TLS
    'TLS 上下文': 'TLS context',
    'TLS 配置': 'TLS configuration',
    'TLS 连接': 'TLS connection',
    
    // Static files
    '静态文件': 'Static file',
    '静态文件服务': 'Static file serving',
    '文件路径': 'File path',
    '文件大小': 'File size',
    
    // WebSocket
    'WebSocket 连接': 'WebSocket connection',
    'WebSocket 消息': 'WebSocket message',
    'WebSocket 帧': 'WebSocket frame',
    
    // Error handling
    '错误处理': 'Error handling',
    '错误码': 'Error code',
    '错误信息': 'Error message',
    '错误恢复': 'Error recovery',
    
    // Logging
    '日志级别': 'Log level',
    '日志输出': 'Log output',
    '日志格式': 'Log format',
    
    // Validation
    '输入验证': 'Input validation',
    '参数验证': 'Parameter validation',
    '数据验证': 'Data validation',
    
    // Middleware
    '中间件': 'Middleware',
    '中间件链': 'Middleware chain',
    '中间件上下文': 'Middleware context',
    
    // Connection
    '连接': 'Connection',
    '连接管理': 'Connection management',
    '连接池': 'Connection pool',
    '连接超时': 'Connection timeout',
    
    // Common phrases
    '支持': 'Support',
    '不支持': 'Not supported',
    '可选': 'Optional',
    '必需': 'Required',
    '默认': 'Default',
    '自动': 'Automatic',
    '手动': 'Manual',
    '启用': 'Enable',
    '禁用': 'Disable',
    '启用状态': 'Enabled',
    '禁用状态': 'Disabled',
    '仅用于': 'Only used for',
    '主要用于': 'Mainly used for',
    '用于': 'Used for',
    '使用': 'Use',
    '使用方式': 'Usage',
    '使用示例': 'Usage example',
    '注意事项': 'Note',
    '注意': 'Note',
    '警告': 'Warning',
    '错误': 'Error',
    '成功': 'Success',
    '失败': 'Failure',
    '返回': 'Return',
    '返回值': 'Return value',
    '参数': 'Parameter',
    '参数列表': 'Parameter list',
    '参数说明': 'Parameter description',
    '字段': 'Field',
    '字段说明': 'Field description',
    '结构体': 'Structure',
    '结构体定义': 'Structure definition',
    '枚举': 'Enum',
    '枚举值': 'Enum value',
    '常量': 'Constant',
    '常量定义': 'Constant definition',
    '宏定义': 'Macro definition',
    '函数': 'Function',
    '函数说明': 'Function description',
    '函数原型': 'Function prototype',
    '函数参数': 'Function parameter',
    '函数返回值': 'Function return value',
    '回调函数': 'Callback function',
    '事件': 'Event',
    '事件处理': 'Event handling',
    '事件监听': 'Event listener',
    '事件触发': 'Event trigger',
    '异步': 'Asynchronous',
    '同步': 'Synchronous',
    '线程': 'Thread',
    '线程安全': 'Thread safe',
    '进程': 'Process',
    '并发': 'Concurrency',
    '并行': 'Parallel',
    '阻塞': 'Blocking',
    '非阻塞': 'Non-blocking',
    '超时': 'Timeout',
    '超时时间': 'Timeout duration',
    '超时处理': 'Timeout handling',
    '重试': 'Retry',
    '重试机制': 'Retry mechanism',
    '重试次数': 'Retry count',
    '限流': 'Rate limit',
    '限流策略': 'Rate limit policy',
    '限流器': 'Rate limiter',
    '令牌桶': 'Token bucket',
    '令牌桶算法': 'Token bucket algorithm',
    '白名单': 'Whitelist',
    '黑名单': 'Blacklist',
    '访问控制': 'Access control',
    '权限管理': 'Permission management',
    '认证': 'Authentication',
    '授权': 'Authorization',
    '会话': 'Session',
    '会话管理': 'Session management',
    '会话超时': 'Session timeout',
    'Cookie': 'Cookie',
    'Cookie 管理': 'Cookie management',
    '会话 ID': 'Session ID',
    '用户': 'User',
    '用户代理': 'User agent',
    '浏览器': 'Browser',
    '客户端类型': 'Client type',
    '平台': 'Platform',
    '操作系统': 'Operating system',
    '系统': 'System',
    '系统调用': 'System call',
    '内核': 'Kernel',
    '内核空间': 'Kernel space',
    '用户空间': 'User space',
    '内核态': 'Kernel mode',
    '用户态': 'User mode',
    '中断': 'Interrupt',
    '异常': 'Exception',
    '异常处理': 'Exception handling',
    '信号': 'Signal',
    '信号处理': 'Signal handling',
    '管道': 'Pipe',
    '管道通信': 'Pipe communication',
    '进程间通信': 'Inter-process communication',
    '网络通信': 'Network communication',
    '网络协议栈': 'Network protocol stack',
    'TCP/IP': 'TCP/IP',
    'TCP 连接': 'TCP connection',
    'TCP 协议': 'TCP protocol',
    'UDP 协议': 'UDP protocol',
    'HTTP 协议': 'HTTP protocol',
    'HTTPS 协议': 'HTTPS protocol',
    'HTTP/1.1': 'HTTP/1.1',
    'HTTP/2': 'HTTP/2',
    'HTTP 方法': 'HTTP method',
    'HTTP 状态码': 'HTTP status code',
    'GET 请求': 'GET request',
    'POST 请求': 'POST request',
    'PUT 请求': 'PUT request',
    'DELETE 请求': 'DELETE request',
    'HEAD 请求': 'HEAD request',
    'OPTIONS 请求': 'OPTIONS request',
    'PATCH 请求': 'PATCH request',
    '状态码': 'Status code',
    '状态码 200': 'Status code 200',
    '状态码 404': 'Status code 404',
    '状态码 500': 'Status code 500',
    '重定向': 'Redirect',
    '重定向 URL': 'Redirect URL',
    '永久重定向': 'Permanent redirect',
    '临时重定向': 'Temporary redirect',
    '内容类型': 'Content type',
    '内容长度': 'Content length',
    '内容编码': 'Content encoding',
    '内容语言': 'Content language',
    '内容位置': 'Content location',
    '内容范围': 'Content range',
    '内容摘要': 'Content digest',
    '内容协商': 'Content negotiation',
    '字符集': 'Character set',
    '字符编码': 'Character encoding',
    'UTF-8': 'UTF-8',
    'ASCII': 'ASCII',
    'ISO-8859-1': 'ISO-8859-1',
    'Base64': 'Base64',
    'URL 编码': 'URL encoding',
    'URL 解码': 'URL decoding',
    'JSON 格式': 'JSON format',
    'XML 格式': 'XML format',
    'HTML 格式': 'HTML format',
    '文本格式': 'Text format',
    '二进制格式': 'Binary format',
    '数据格式': 'Data format',
    '数据类型': 'Data type',
    '数据结构': 'Data structure',
    '数据模型': 'Data model',
    '数据存储': 'Data storage',
    '数据库': 'Database',
    '数据库连接': 'Database connection',
    '数据库查询': 'Database query',
    '数据库事务': 'Database transaction',
    '数据库索引': 'Database index',
    '数据库表': 'Database table',
    '数据库字段': 'Database field',
    '数据库记录': 'Database record',
    '数据库备份': 'Database backup',
    '数据库恢复': 'Database recovery',
    '文件系统': 'File system',
    '文件操作': 'File operation',
    '文件读写': 'File read/write',
    '文件权限': 'File permission',
    '文件所有者': 'File owner',
    '文件组': 'File group',
    '文件属性': 'File attribute',
    '文件元数据': 'File metadata',
    '目录': 'Directory',
    '目录结构': 'Directory structure',
    '目录遍历': 'Directory traversal',
    '路径': 'Path',
    '路径分隔符': 'Path separator',
    '相对路径': 'Relative path',
    '绝对路径': 'Absolute path',
    '路径解析': 'Path resolution',
    '路径拼接': 'Path concatenation',
    '路径规范化': 'Path normalization',
    '路径编码': 'Path encoding',
    '路径解码': 'Path decoding',
    '时间戳': 'Timestamp',
    '日期时间': 'Date time',
    '时间格式': 'Time format',
    '时区': 'Time zone',
    'UTC 时间': 'UTC time',
    '本地时间': 'Local time',
    '时间差': 'Time difference',
    '时间间隔': 'Time interval',
    '持续时间': 'Duration',
    '延迟': 'Latency',
    '响应时间': 'Response time',
    '处理时间': 'Processing time',
    '等待时间': 'Waiting time',
    '执行时间': 'Execution time',
    '运行时间': 'Runtime',
    '启动时间': 'Startup time',
    '关闭时间': 'Shutdown time',
    '重启时间': 'Restart time',
    '性能测试': 'Performance test',
    '压力测试': 'Stress test',
    '负载测试': 'Load test',
    '单元测试': 'Unit test',
    '集成测试': 'Integration test',
    '系统测试': 'System test',
    '回归测试': 'Regression test',
    '测试用例': 'Test case',
    '测试覆盖率': 'Test coverage',
    '测试框架': 'Test framework',
    '测试工具': 'Test tool',
    '测试环境': 'Test environment',
    '生产环境': 'Production environment',
    '开发环境': 'Development environment',
    '预发布环境': 'Pre-production environment',
    '环境变量': 'Environment variable',
    '环境配置': 'Environment configuration',
    '配置文件': 'Configuration file',
    '配置管理': 'Configuration management',
    '配置加载': 'Configuration loading',
    '配置保存': 'Configuration saving',
    '配置更新': 'Configuration update',
    '配置热更新': 'Configuration hot reload',
    '配置版本': 'Configuration version',
    '配置验证': 'Configuration validation',
    '配置同步': 'Configuration synchronization',
    '配置备份': 'Configuration backup',
    '配置恢复': 'Configuration restore',
    '配置迁移': 'Configuration migration',
    '配置兼容性': 'Configuration compatibility',
    '配置文档': 'Configuration documentation',
    '配置示例': 'Configuration example',
    '配置模板': 'Configuration template',
    '配置生成器': 'Configuration generator',
    '配置解析器': 'Configuration parser',
    '配置序列化': 'Configuration serialization',
    '配置反序列化': 'Configuration deserialization',
    '配置加密': 'Configuration encryption',
    '配置解密': 'Configuration decryption',
    '配置签名': 'Configuration signing',
    '配置验证签名': 'Configuration signature verification',
    '配置哈希': 'Configuration hash',
    '配置校验和': 'Configuration checksum',
    '配置压缩': 'Configuration compression',
    '配置解压': 'Configuration decompression',
    '配置编码': 'Configuration encoding',
    '配置解码': 'Configuration decoding',
    '配置格式': 'Configuration format',
    '配置语法': 'Configuration syntax',
    '配置语义': 'Configuration semantics',
    '配置规则': 'Configuration rule',
    '配置约束': 'Configuration constraint',
    '配置限制': 'Configuration limitation',
    '配置要求': 'Configuration requirement',
    '配置规范': 'Configuration specification',
    '配置标准': 'Configuration standard',
    '配置最佳实践': 'Configuration best practice',
    '配置建议': 'Configuration recommendation',
    '配置指导': 'Configuration guideline',
    '配置教程': 'Configuration tutorial',
    '配置手册': 'Configuration manual',
    '配置指南': 'Configuration guide',
    '配置参考': 'Configuration reference',
    '配置文档': 'Configuration documentation',
    '配置说明': 'Configuration description',
    '配置注释': 'Configuration comment',
    '配置提示': 'Configuration hint',
    '配置警告': 'Configuration warning',
    '配置错误': 'Configuration error',
    '配置异常': 'Configuration exception',
    '配置失败': 'Configuration failure',
    '配置成功': 'Configuration success',
    '配置状态': 'Configuration status',
    '配置信息': 'Configuration information',
    '配置详情': 'Configuration details',
    '配置摘要': 'Configuration summary',
    '配置概述': 'Configuration overview',
    '配置简介': 'Configuration introduction',
    '配置背景': 'Configuration background',
    '配置历史': 'Configuration history',
    '配置版本': 'Configuration version',
    '配置变更': 'Configuration change',
    '配置更新': 'Configuration update',
    '配置升级': 'Configuration upgrade',
    '配置降级': 'Configuration downgrade',
    '配置回滚': 'Configuration rollback',
    '配置迁移': 'Configuration migration',
    '配置转换': 'Configuration conversion',
    '配置适配': 'Configuration adaptation',
    '配置优化': 'Configuration optimization',
    '配置调整': 'Configuration adjustment',
    '配置修改': 'Configuration modification',
    '配置编辑': 'Configuration editing',
    '配置查看': 'Configuration viewing',
    '配置搜索': 'Configuration searching',
    '配置过滤': 'Configuration filtering',
    '配置排序': 'Configuration sorting',
    '配置分组': 'Configuration grouping',
    '配置分类': 'Configuration categorization',
    '配置标签': 'Configuration tagging',
    '配置标记': 'Configuration marking',
    '配置注释': 'Configuration annotation',
    '配置文档': 'Configuration documentation',
    '配置帮助': 'Configuration help',
    '配置支持': 'Configuration support',
    '配置服务': 'Configuration service',
    '配置接口': 'Configuration interface',
    '配置 API': 'Configuration API',
    '配置 SDK': 'Configuration SDK',
    '配置库': 'Configuration library',
    '配置框架': 'Configuration framework',
    '配置工具': 'Configuration tool',
    '配置平台': 'Configuration platform',
    '配置系统': 'Configuration system',
    '配置解决方案': 'Configuration solution',
    '配置方案': 'Configuration scheme',
    '配置策略': 'Configuration strategy',
    '配置模式': 'Configuration pattern',
    '配置架构': 'Configuration architecture',
    '配置设计': 'Configuration design',
    '配置实现': 'Configuration implementation',
    '配置部署': 'Configuration deployment',
    '配置运维': 'Configuration operation',
    '配置监控': 'Configuration monitoring',
    '配置日志': 'Configuration logging',
    '配置审计': 'Configuration auditing',
    '配置安全': 'Configuration security',
    '配置隐私': 'Configuration privacy',
    '配置合规': 'Configuration compliance',
    '配置治理': 'Configuration governance',
    '配置管理': 'Configuration management',
    '配置控制': 'Configuration control',
    '配置治理': 'Configuration governance',
    '配置策略': 'Configuration policy',
    '配置规划': 'Configuration planning',
    '配置设计': 'Configuration design',
    '配置开发': 'Configuration development',
    '配置测试': 'Configuration testing',
    '配置发布': 'Configuration release',
    '配置维护': 'Configuration maintenance',
    '配置支持': 'Configuration support',
    '配置培训': 'Configuration training',
    '配置文档': 'Configuration documentation',
    '配置知识库': 'Configuration knowledge base',
    '配置社区': 'Configuration community',
    '配置生态': 'Configuration ecosystem',
    '配置未来': 'Configuration future',
    '配置趋势': 'Configuration trend',
    '配置发展': 'Configuration development',
    '配置创新': 'Configuration innovation',
    '配置演进': 'Configuration evolution',
    '配置变革': 'Configuration transformation',
    '配置革命': 'Configuration revolution',
    '配置颠覆': 'Configuration disruption',
    '配置突破': 'Configuration breakthrough',
    '配置里程碑': 'Configuration milestone',
    '配置成就': 'Configuration achievement',
    '配置贡献': 'Configuration contribution',
    '配置价值': 'Configuration value',
    '配置效益': 'Configuration benefit',
    '配置影响': 'Configuration impact',
    '配置意义': 'Configuration significance',
    '配置重要性': 'Configuration importance',
    '配置必要性': 'Configuration necessity',
    '配置可行性': 'Configuration feasibility',
    '配置可行性研究': 'Configuration feasibility study',
    '配置需求分析': 'Configuration requirement analysis',
    '配置需求调研': 'Configuration requirement research',
    '配置需求收集': 'Configuration requirement collection',
    '配置需求整理': 'Configuration requirement organization',
    '配置需求分析报告': 'Configuration requirement analysis report',
    '配置需求文档': 'Configuration requirement document',
    '配置需求规格说明书': 'Configuration requirement specification',
    '配置设计文档': 'Configuration design document',
    '配置技术方案': 'Configuration technical solution',
    '配置实施方案': 'Configuration implementation plan',
    '配置测试计划': 'Configuration test plan',
    '配置测试报告': 'Configuration test report',
    '配置部署方案': 'Configuration deployment plan',
    '配置运维手册': 'Configuration operation manual',
    '配置用户手册': 'Configuration user manual',
    '配置开发手册': 'Configuration development manual',
    '配置管理手册': 'Configuration management manual',
    '配置架构文档': 'Configuration architecture document',
    '配置设计模式': 'Configuration design pattern',
    '配置最佳实践': 'Configuration best practice',
    '配置编码规范': 'Configuration coding standard',
    '配置命名规范': 'Configuration naming convention',
    '配置注释规范': 'Configuration comment standard',
    '配置文档规范': 'Configuration documentation standard',
    '配置测试规范': 'Configuration testing standard',
    '配置部署规范': 'Configuration deployment standard',
    '配置运维规范': 'Configuration operation standard',
    '配置安全规范': 'Configuration security standard',
    '配置性能规范': 'Configuration performance standard',
    '配置质量标准': 'Configuration quality standard',
    '配置标准': 'Configuration standard',
    '配置规范': 'Configuration specification',
    '配置指南': 'Configuration guide',
    '配置教程': 'Configuration tutorial',
    '配置示例': 'Configuration example',
    '配置模板': 'Configuration template',
    '配置工具': 'Configuration tool',
    '配置平台': 'Configuration platform',
    '配置系统': 'Configuration system',
    '配置框架': 'Configuration framework',
    '配置库': 'Configuration library',
    '配置 SDK': 'Configuration SDK',
    '配置 API': 'Configuration API',
    '配置接口': 'Configuration interface',
    '配置服务': 'Configuration service',
    '配置支持': 'Configuration support',
    '配置帮助': 'Configuration help',
    '配置文档': 'Configuration documentation',
    '配置注释': 'Configuration comment',
    '配置提示': 'Configuration hint',
    '配置警告': 'Configuration warning',
    '配置错误': 'Configuration error',
    '配置异常': 'Configuration exception',
    '配置失败': 'Configuration failure',
    '配置成功': 'Configuration success',
    '配置状态': 'Configuration status',
    '配置信息': 'Configuration information',
    '配置详情': 'Configuration details',
    '配置摘要': 'Configuration summary',
    '配置概述': 'Configuration overview',
    '配置简介': 'Configuration introduction',
    '配置背景': 'Configuration background',
    '配置历史': 'Configuration history',
    '配置版本': 'Configuration version',
    '配置变更': 'Configuration change',
    '配置更新': 'Configuration update',
    '配置升级': 'Configuration upgrade',
    '配置降级': 'Configuration downgrade',
    '配置回滚': 'Configuration rollback',
    '配置迁移': 'Configuration migration',
    '配置转换': 'Configuration conversion',
    '配置适配': 'Configuration adaptation',
    '配置优化': 'Configuration optimization',
    '配置调整': 'Configuration adjustment',
    '配置修改': 'Configuration modification',
    '配置编辑': 'Configuration editing',
    '配置查看': 'Configuration viewing',
    '配置搜索': 'Configuration searching',
    '配置过滤': 'Configuration filtering',
    '配置排序': 'Configuration sorting',
    '配置分组': 'Configuration grouping',
    '配置分类': 'Configuration categorization',
    '配置标签': 'Configuration tagging',
    '配置标记': 'Configuration marking',
};

// Function to translate a file
function translateFile(filePath) {
    console.log(`Processing: ${filePath}`);
    
    let content = fs.readFileSync(filePath, 'utf8');
    let originalLength = content.length;
    let changes = 0;
    
    // Apply all translations
    for (const [chinese, english] of Object.entries(translations)) {
        const regex = new RegExp(chinese, 'g');
        const matches = content.match(regex);
        if (matches) {
            content = content.replace(regex, english);
            changes += matches.length;
        }
    }
    
    // Only write if changes were made
    if (content !== fs.readFileSync(filePath, 'utf8')) {
        fs.writeFileSync(filePath, content, 'utf8');
        console.log(`  ✓ Translated ${changes} phrases`);
        return changes;
    }
    
    console.log(`  No changes`);
    return 0;
}

// Get all header files
const includeDir = path.join(__dirname, '..', 'include');
const files = fs.readdirSync(includeDir).filter(f => f.endsWith('.h') && f.startsWith('uvhttp_'));

console.log(`Found ${files.length} header files to translate\n`);

let totalChanges = 0;
for (const file of files) {
    const filePath = path.join(includeDir, file);
    totalChanges += translateFile(filePath);
}

console.log(`\nTotal translations: ${totalChanges} phrases`);
