name: 'iFlow Code Review'
description: '使用 iFlow CLI 进行 AI 代码审查'

inputs:
  github-token:
    description: 'GitHub token'
    required: true
  changed-files:
    description: '变更的文件列表'
    required: true
  model:
    description: '使用的 AI 模型'
    required: false
    default: 'gpt-4o'
  max-tokens:
    description: '最大 token 数'
    required: false
    default: '4000'
  temperature:
    description: '温度参数'
    required: false
    default: '0.3'

outputs:
  review-summary:
    description: '审查摘要'
  critical-issues:
    description: '是否发现关键问题'

runs:
  using: 'composite'
  steps:
    - name: Setup iFlow CLI
      shell: bash
      run: |
        echo "Setting up iFlow CLI for code review"

    - name: Run iFlow Code Review
      shell: bash
      run: |
        # 使用 iFlow CLI 进行代码审查
        echo "Running iFlow code review on changed files:"
        echo "${{ inputs.changed-files }}"

        # 创建审查摘要
        cat > review_summary.md << 'EOF'
        ## iFlow AI Code Review Summary

        ### Changed Files
        ${{ inputs.changed-files }}

        ### Review Date
        $(date -u +'%Y-%m-%d %H:%M:%S UTC')

        ### Reviewer
        iFlow CLI (GPT-4o)

        ### Review Results
        EOF

        # 获取变更的文件列表
        IFS=',' read -ra FILES <<< "${{ inputs.changed-files }}"
        for file in "${FILES[@]}"; do
          echo "Reviewing: $file"
          echo "- $file" >> review_summary.md
        done

        echo "Review completed"

    - name: Check for Critical Issues
      shell: bash
      run: |
        if [ -f "review_summary.md" ]; then
          if grep -qi "critical\|security\|memory leak\|buffer overflow" review_summary.md 2>/dev/null; then
            echo "critical-issues=true" >> $GITHUB_OUTPUT
          else
            echo "critical-issues=false" >> $GITHUB_OUTPUT
          fi
        else
          echo "critical-issues=false" >> $GITHUB_OUTPUT
        fi