name: 'Setup Build Environment'
description: 'Setup build environment for different operating systems'

inputs:
  os:
    description: 'Operating system (ubuntu-latest, macos-latest, windows-latest)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install dependencies (Ubuntu)
      if: inputs.os == 'ubuntu-latest'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential valgrind wrk lcov python3 python3-pip
        pip3 install matplotlib numpy

    - name: Install dependencies (macOS)
      if: inputs.os == 'macos-latest'
      shell: bash
      run: |
        brew install cmake wrk lcov python3
        pip3 install matplotlib numpy

    - name: Install dependencies (Windows)
      if: inputs.os == 'windows-latest'
      shell: pwsh
      run: |
        choco install cmake -y
        choco install wrk -y