name: 'Setup Build Environment'
description: 'Setup build environment for Linux'

inputs:
  os:
    description: 'Operating system (ubuntu-latest)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install dependencies (Ubuntu)
      if: inputs.os == 'ubuntu-latest'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential valgrind wrk lcov python3 python3-pip
        pip3 install matplotlib numpy