name: 'Cache Dependencies'
description: 'Cache CMake dependencies to speed up builds'

inputs:
  cache-key:
    description: 'Unique cache key for this build'
    required: true
  build-type:
    description: 'Build type (Release, Debug)'
    required: false
    default: 'Release'

runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        # 只缓存依赖，不缓存构建产物
        path: |
          deps/libuv/build
          deps/mbedtls/build
          deps/xxhash/libxxhash.a
          deps/cllhttp/build
          deps/mimalloc/build
          deps/googletest/build
          deps/cjson/build
        # 使用主 CMakeLists.txt 和关键配置文件的哈希作为缓存键
        # 移除 inputs.cache-key 中的 github.sha，以便缓存可以被恢复
        key: deps-${{ runner.os }}-${{ inputs.build-type }}-${{ hashFiles('CMakeLists.txt', 'cmake/Dependencies.cmake') }}
        restore-keys: |
          deps-${{ runner.os }}-${{ inputs.build-type }}-