name: 'Cache Dependencies'
description: 'Cache CMake dependencies to speed up builds'

inputs:
  cache-key:
    description: 'Unique cache key for this build'
    required: true
  build-type:
    description: 'Build type (Release, Debug)'
    required: false
    default: 'Release'

runs:
  using: 'composite'
  steps:
    - name: Cache CMake build
      uses: actions/cache@v4
      with:
        path: |
          build-${{ inputs.build-type }}
          build-${{ inputs.build-type }}/CMakeFiles
          build-${{ inputs.build-type }}/deps
        key: ${{ inputs.cache-key }}-${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt', 'cmake/**') }}
        restore-keys: |
          ${{ inputs.cache-key }}-${{ runner.os }}-cmake-