.TH "array_route_t" 3 "Fri Jan 23 2026" "Version 2.0.0" "UVHTTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
array_route_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <uvhttp_router\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBpath\fP [256]"
.br
.ti -1c
.RI "\fBuvhttp_method_t\fP \fBmethod\fP"
.br
.ti -1c
.RI "\fBuvhttp_request_handler_t\fP \fBhandler\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBuvhttp_request_handler_t\fP array_route_t::handler"

.SS "\fBuvhttp_method_t\fP array_route_t::method"

.SS "char array_route_t::path[256]"


.SH "Author"
.PP 
Generated automatically by Doxygen for UVHTTP from the source code\&.
