.TH "ip_entry" 3 "Fri Jan 23 2026" "Version 2.0.0" "UVHTTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ip_entry
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <uvhttp_websocket_auth\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBip\fP [64]"
.br
.ti -1c
.RI "struct \fBip_entry\fP * \fBnext\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "char ip_entry::ip[64]"

.SS "struct \fBip_entry\fP* ip_entry::next"


.SH "Author"
.PP 
Generated automatically by Doxygen for UVHTTP from the source code\&.
