.TH "test_file_data_t" 3 "Fri Jan 23 2026" "Version 2.0.0" "UVHTTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_file_data_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char ** \fBvirtual_files\fP"
.br
.ti -1c
.RI "char ** \fBvirtual_content\fP"
.br
.ti -1c
.RI "size_t * \fBvirtual_sizes\fP"
.br
.ti -1c
.RI "size_t \fBvirtual_count\fP"
.br
.ti -1c
.RI "bool \fBvirtual_enabled\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "char** test_file_data_t::virtual_content"

.SS "size_t test_file_data_t::virtual_count"

.SS "bool test_file_data_t::virtual_enabled"

.SS "char** test_file_data_t::virtual_files"

.SS "size_t* test_file_data_t::virtual_sizes"


.SH "Author"
.PP 
Generated automatically by Doxygen for UVHTTP from the source code\&.
