.TH "test_network_data_t" 3 "Fri Jan 23 2026" "Version 2.0.0" "UVHTTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_network_data_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBmock_socket_result\fP"
.br
.ti -1c
.RI "ssize_t \fBmock_send_result\fP"
.br
.ti -1c
.RI "ssize_t \fBmock_recv_result\fP"
.br
.ti -1c
.RI "bool \fBmock_enabled\fP"
.br
.ti -1c
.RI "char * \fBrecv_buffer\fP"
.br
.ti -1c
.RI "size_t \fBrecv_buffer_size\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "bool test_network_data_t::mock_enabled"

.SS "ssize_t test_network_data_t::mock_recv_result"

.SS "ssize_t test_network_data_t::mock_send_result"

.SS "int test_network_data_t::mock_socket_result"

.SS "char* test_network_data_t::recv_buffer"

.SS "size_t test_network_data_t::recv_buffer_size"


.SH "Author"
.PP 
Generated automatically by Doxygen for UVHTTP from the source code\&.
