.TH "src/uvhttp_hash.c" 3 "Fri Jan 23 2026" "Version 2.0.0" "UVHTTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/uvhttp_hash.c
.SH SYNOPSIS
.br
.PP
\fC#include 'uvhttp_hash\&.h'\fP
.br
\fC#include 'xxhash\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "uint64_t \fBuvhttp_hash\fP (const void *data, size_t length, uint64_t seed)"
.br
.ti -1c
.RI "uint64_t \fBuvhttp_hash_string\fP (const char *str)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "uint64_t uvhttp_hash (const void * data, size_t length, uint64_t seed)"

.SS "uint64_t uvhttp_hash_string (const char * str)"

.SH "Author"
.PP 
Generated automatically by Doxygen for UVHTTP from the source code\&.
