.TH "uvhttp_cors_config" 3 "Fri Jan 23 2026" "Version 2.0.0" "UVHTTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uvhttp_cors_config
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <uvhttp_cors_middleware\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBallow_origin\fP"
.br
.ti -1c
.RI "char * \fBallow_methods\fP"
.br
.ti -1c
.RI "char * \fBallow_headers\fP"
.br
.ti -1c
.RI "char * \fBexpose_headers\fP"
.br
.ti -1c
.RI "char * \fBallow_credentials\fP"
.br
.ti -1c
.RI "char * \fBmax_age\fP"
.br
.ti -1c
.RI "int \fBallow_all_origins\fP"
.br
.ti -1c
.RI "int \fBallow_credentials_enabled\fP"
.br
.ti -1c
.RI "int \fBowns_strings\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int uvhttp_cors_config::allow_all_origins"

.SS "char* uvhttp_cors_config::allow_credentials"

.SS "int uvhttp_cors_config::allow_credentials_enabled"

.SS "char* uvhttp_cors_config::allow_headers"

.SS "char* uvhttp_cors_config::allow_methods"

.SS "char* uvhttp_cors_config::allow_origin"

.SS "char* uvhttp_cors_config::expose_headers"

.SS "char* uvhttp_cors_config::max_age"

.SS "int uvhttp_cors_config::owns_strings"


.SH "Author"
.PP 
Generated automatically by Doxygen for UVHTTP from the source code\&.
