.TH "uvhttp_server_builder_t" 3 "Fri Jan 23 2026" "Version 2.0.0" "UVHTTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uvhttp_server_builder_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <uvhttp_server\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBuvhttp_server_t\fP * \fBserver\fP"
.br
.ti -1c
.RI "\fBuvhttp_router_t\fP * \fBrouter\fP"
.br
.ti -1c
.RI "\fBuvhttp_config_t\fP * \fBconfig\fP"
.br
.ti -1c
.RI "uv_loop_t * \fBloop\fP"
.br
.ti -1c
.RI "int \fBauto_cleanup\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int uvhttp_server_builder_t::auto_cleanup"

.SS "\fBuvhttp_config_t\fP* uvhttp_server_builder_t::config"

.SS "uv_loop_t* uvhttp_server_builder_t::loop"

.SS "\fBuvhttp_router_t\fP* uvhttp_server_builder_t::router"

.SS "\fBuvhttp_server_t\fP* uvhttp_server_builder_t::server"


.SH "Author"
.PP 
Generated automatically by Doxygen for UVHTTP from the source code\&.
