.TH "uvhttp_tls_write_data_t" 3 "Fri Jan 23 2026" "Version 2.0.0" "UVHTTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uvhttp_tls_write_data_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <uvhttp_response\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBdata\fP"
.br
.ti -1c
.RI "size_t \fBlength\fP"
.br
.ti -1c
.RI "\fBuvhttp_response_t\fP * \fBresponse\fP"
.br
.ti -1c
.RI "\fBuvhttp_connection_t\fP * \fBconnection\fP"
.br
.ti -1c
.RI "size_t \fBoffset\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBuvhttp_connection_t\fP* uvhttp_tls_write_data_t::connection"

.SS "char* uvhttp_tls_write_data_t::data"

.SS "size_t uvhttp_tls_write_data_t::length"

.SS "size_t uvhttp_tls_write_data_t::offset"

.SS "\fBuvhttp_response_t\fP* uvhttp_tls_write_data_t::response"


.SH "Author"
.PP 
Generated automatically by Doxygen for UVHTTP from the source code\&.
