.TH "uvhttp_middleware_context" 3 "Fri Jan 23 2026" "Version 2.0.0" "UVHTTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uvhttp_middleware_context
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <uvhttp_middleware\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBdata\fP"
.br
.ti -1c
.RI "void(* \fBcleanup\fP )(void *\fBdata\fP)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "void(* uvhttp_middleware_context::cleanup) (void *\fBdata\fP)"

.SS "void* uvhttp_middleware_context::data"


.SH "Author"
.PP 
Generated automatically by Doxygen for UVHTTP from the source code\&.
