.TH "uvhttp_mime_mapping" 3 "Fri Jan 23 2026" "Version 2.0.0" "UVHTTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uvhttp_mime_mapping
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <uvhttp_static\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBextension\fP"
.br
.ti -1c
.RI "const char * \fBmime_type\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const char* uvhttp_mime_mapping::extension"

.SS "const char* uvhttp_mime_mapping::mime_type"


.SH "Author"
.PP 
Generated automatically by Doxygen for UVHTTP from the source code\&.
