.TH "uvhttp_tls_stats" 3 "Fri Jan 23 2026" "Version 2.0.0" "UVHTTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uvhttp_tls_stats
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <uvhttp_tls\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned long long \fBhandshake_count\fP"
.br
.ti -1c
.RI "unsigned long long \fBhandshake_errors\fP"
.br
.ti -1c
.RI "unsigned long long \fBbytes_sent\fP"
.br
.ti -1c
.RI "unsigned long long \fBbytes_received\fP"
.br
.ti -1c
.RI "unsigned long long \fBsession_hits\fP"
.br
.ti -1c
.RI "unsigned long long \fBsession_misses\fP"
.br
.ti -1c
.RI "double \fBavg_handshake_time_ms\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "double uvhttp_tls_stats::avg_handshake_time_ms"

.SS "unsigned long long uvhttp_tls_stats::bytes_received"

.SS "unsigned long long uvhttp_tls_stats::bytes_sent"

.SS "unsigned long long uvhttp_tls_stats::handshake_count"

.SS "unsigned long long uvhttp_tls_stats::handshake_errors"

.SS "unsigned long long uvhttp_tls_stats::session_hits"

.SS "unsigned long long uvhttp_tls_stats::session_misses"


.SH "Author"
.PP 
Generated automatically by Doxygen for UVHTTP from the source code\&.
