.TH "uvhttp_string_entry" 3 "Fri Jan 23 2026" "Version 2.0.0" "UVHTTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uvhttp_string_entry
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <uvhttp_string_pool\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBuvhttp_string_entry\fP * \fBnext\fP"
.br
.ti -1c
.RI "uint32_t \fBhash\fP"
.br
.ti -1c
.RI "uint32_t \fBlength\fP"
.br
.ti -1c
.RI "uint32_t \fBref_count\fP"
.br
.ti -1c
.RI "char \fBdata\fP []"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "char uvhttp_string_entry::data[]"

.SS "uint32_t uvhttp_string_entry::hash"

.SS "uint32_t uvhttp_string_entry::length"

.SS "struct \fBuvhttp_string_entry\fP* uvhttp_string_entry::next"

.SS "uint32_t uvhttp_string_entry::ref_count"


.SH "Author"
.PP 
Generated automatically by Doxygen for UVHTTP from the source code\&.
