.TH "src/uvhttp_allocator.c" 3 "Fri Jan 23 2026" "Version 2.0.0" "UVHTTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/uvhttp_allocator.c
.SH SYNOPSIS
.br
.PP
\fC#include 'uvhttp_allocator\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBuvhttp_test_malloc\fP (size_t size, const char *file, int line)"
.br
.ti -1c
.RI "void \fBuvhttp_test_free\fP (void *ptr, const char *file, int line)"
.br
.ti -1c
.RI "void * \fBuvhttp_test_realloc\fP (void *ptr, size_t size, const char *file, int line)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void uvhttp_test_free (void * ptr, const char * file, int line)"

.SS "void* uvhttp_test_malloc (size_t size, const char * file, int line)"

.SS "void* uvhttp_test_realloc (void * ptr, size_t size, const char * file, int line)"

.SH "Author"
.PP 
Generated automatically by Doxygen for UVHTTP from the source code\&.
