.TH "uvhttp_memory_provider_t" 3 "Fri Jan 23 2026" "Version 2.0.0" "UVHTTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uvhttp_memory_provider_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <uvhttp_deps\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void *(* \fBmalloc\fP )(size_t size, void *\fBuser_data\fP)"
.br
.ti -1c
.RI "void *(* \fBcalloc\fP )(size_t nmemb, size_t size, void *\fBuser_data\fP)"
.br
.ti -1c
.RI "void(* \fBfree\fP )(void *ptr, void *\fBuser_data\fP)"
.br
.ti -1c
.RI "void *(* \fBrealloc\fP )(void *ptr, size_t size, void *\fBuser_data\fP)"
.br
.ti -1c
.RI "size_t(* \fBget_allocated_size\fP )(void *ptr, void *\fBuser_data\fP)"
.br
.ti -1c
.RI "void * \fBuser_data\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "void*(* uvhttp_memory_provider_t::calloc) (size_t nmemb, size_t size, void *\fBuser_data\fP)"

.SS "void(* uvhttp_memory_provider_t::free) (void *ptr, void *\fBuser_data\fP)"

.SS "size_t(* uvhttp_memory_provider_t::get_allocated_size) (void *ptr, void *\fBuser_data\fP)"

.SS "void*(* uvhttp_memory_provider_t::malloc) (size_t size, void *\fBuser_data\fP)"

.SS "void*(* uvhttp_memory_provider_t::realloc) (void *ptr, size_t size, void *\fBuser_data\fP)"

.SS "void* uvhttp_memory_provider_t::user_data"


.SH "Author"
.PP 
Generated automatically by Doxygen for UVHTTP from the source code\&.
