.TH "uvhttp_error_recovery_config_t" 3 "Fri Jan 23 2026" "Version 2.0.0" "UVHTTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uvhttp_error_recovery_config_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBmax_retries\fP"
.br
.ti -1c
.RI "int \fBbase_delay_ms\fP"
.br
.ti -1c
.RI "int \fBmax_delay_ms\fP"
.br
.ti -1c
.RI "double \fBbackoff_multiplier\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "double uvhttp_error_recovery_config_t::backoff_multiplier"

.SS "int uvhttp_error_recovery_config_t::base_delay_ms"

.SS "int uvhttp_error_recovery_config_t::max_delay_ms"

.SS "int uvhttp_error_recovery_config_t::max_retries"


.SH "Author"
.PP 
Generated automatically by Doxygen for UVHTTP from the source code\&.
