.TH "uvhttp_ws_middleware_t" 3 "Fri Jan 23 2026" "Version 2.0.0" "UVHTTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uvhttp_ws_middleware_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <uvhttp_websocket_middleware\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBpath\fP"
.br
.ti -1c
.RI "\fBuvhttp_ws_middleware_config_t\fP \fBconfig\fP"
.br
.ti -1c
.RI "\fBuvhttp_ws_middleware_callbacks_t\fP \fBcallbacks\fP"
.br
.ti -1c
.RI "\fBuvhttp_http_middleware_t\fP * \fBhttp_middleware\fP"
.br
.ti -1c
.RI "void * \fBinternal_data\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBuvhttp_ws_middleware_callbacks_t\fP uvhttp_ws_middleware_t::callbacks"

.SS "\fBuvhttp_ws_middleware_config_t\fP uvhttp_ws_middleware_t::config"

.SS "\fBuvhttp_http_middleware_t\fP* uvhttp_ws_middleware_t::http_middleware"

.SS "void* uvhttp_ws_middleware_t::internal_data"

.SS "const char* uvhttp_ws_middleware_t::path"


.SH "Author"
.PP 
Generated automatically by Doxygen for UVHTTP from the source code\&.
