.TH "uvhttp_mempool_block" 3 "Fri Jan 23 2026" "Version 2.0.0" "UVHTTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uvhttp_mempool_block
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <uvhttp_mempool\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBuvhttp_mempool_block\fP * \fBnext\fP"
.br
.ti -1c
.RI "uint8_t \fBdata\fP [4096]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "uint8_t uvhttp_mempool_block::data[4096]"

.SS "struct \fBuvhttp_mempool_block\fP* uvhttp_mempool_block::next"


.SH "Author"
.PP 
Generated automatically by Doxygen for UVHTTP from the source code\&.
