.TH "uvhttp_connection_pool_entry" 3 "Fri Jan 23 2026" "Version 2.0.0" "UVHTTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uvhttp_connection_pool_entry
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBuvhttp_connection_t\fP * \fBconnection\fP"
.br
.ti -1c
.RI "time_t \fBlast_used\fP"
.br
.ti -1c
.RI "struct \fBuvhttp_connection_pool_entry\fP * \fBnext\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBuvhttp_connection_t\fP* uvhttp_connection_pool_entry::connection"

.SS "time_t uvhttp_connection_pool_entry::last_used"

.SS "struct \fBuvhttp_connection_pool_entry\fP* uvhttp_connection_pool_entry::next"


.SH "Author"
.PP 
Generated automatically by Doxygen for UVHTTP from the source code\&.
