.TH "src/uvhttp_config.c" 3 "Fri Jan 23 2026" "Version 2.0.0" "UVHTTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/uvhttp_config.c \- 配置管理系统实现  

.SH SYNOPSIS
.br
.PP
\fC#include 'uvhttp_config\&.h'\fP
.br
\fC#include 'uvhttp_allocator\&.h'\fP
.br
\fC#include 'uvhttp_error_handler\&.h'\fP
.br
\fC#include 'uvhttp_context\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <ctype\&.h>\fP
.br
\fC#include <sys/resource\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUVHTTP_MAX_BODY_SIZE_CONFIG\fP   (100 * 1024 * 1024)  /* 避免与头文件中的宏冲突 */"
.br
.ti -1c
.RI "#define \fBUVHTTP_MIN_CONNECTIONS\fP   1"
.br
.ti -1c
.RI "#define \fBUVHTTP_MAX_CONNECTIONS_HARD\fP   65535  /* 基于系统限制 */"
.br
.ti -1c
.RI "#define \fBUVHTTP_MIN_BUFFER_SIZE\fP   1024"
.br
.ti -1c
.RI "#define \fBUVHTTP_MAX_BUFFER_SIZE\fP   (1024 * 1024)"
.br
.ti -1c
.RI "#define \fBUVHTTP_MIN_BODY_SIZE\fP   1024"
.br
.ti -1c
.RI "#define \fBUVHTTP_MAX_BODY_SIZE_CONFIG\fP   (100 * 1024 * 1024)  /* 避免与头文件中的宏冲突 */"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBuvhttp_config_t\fP * \fBuvhttp_config_new\fP (void)"
.br
.ti -1c
.RI "void \fBuvhttp_config_free\fP (\fBuvhttp_config_t\fP *config)"
.br
.ti -1c
.RI "void \fBuvhttp_config_set_defaults\fP (\fBuvhttp_config_t\fP *config)"
.br
.ti -1c
.RI "int \fBuvhttp_config_load_file\fP (\fBuvhttp_config_t\fP *config, const char *filename)"
.br
.ti -1c
.RI "int \fBuvhttp_config_save_file\fP (const \fBuvhttp_config_t\fP *config, const char *filename)"
.br
.ti -1c
.RI "int \fBuvhttp_config_load_env\fP (\fBuvhttp_config_t\fP *config)"
.br
.ti -1c
.RI "int \fBuvhttp_config_validate\fP (const \fBuvhttp_config_t\fP *config)"
.br
.ti -1c
.RI "void \fBuvhttp_config_print\fP (const \fBuvhttp_config_t\fP *config)"
.br
.ti -1c
.RI "const \fBuvhttp_config_t\fP * \fBuvhttp_config_get_current\fP (\fBuvhttp_context_t\fP *context)"
.br
.ti -1c
.RI "int \fBuvhttp_config_update_max_connections\fP (\fBuvhttp_context_t\fP *context, int max_connections)"
.br
.ti -1c
.RI "int \fBuvhttp_config_update_read_buffer_size\fP (\fBuvhttp_context_t\fP *context, int buffer_size)"
.br
.ti -1c
.RI "int \fBuvhttp_config_update_size_limits\fP (\fBuvhttp_context_t\fP *context, size_t max_body_size, size_t max_header_size)"
.br
.ti -1c
.RI "int \fBuvhttp_config_monitor_changes\fP (\fBuvhttp_context_t\fP *context, \fBuvhttp_config_change_callback_t\fP callback)"
.br
.ti -1c
.RI "int \fBuvhttp_config_reload\fP (\fBuvhttp_context_t\fP *context)"
.br
.ti -1c
.RI "void \fBuvhttp_config_set_current\fP (\fBuvhttp_context_t\fP *context, \fBuvhttp_config_t\fP *config)"
.br
.in -1c
.SH "Detailed Description"
.PP 
配置管理系统实现 


.SH "Macro Definition Documentation"
.PP 
.SS "#define UVHTTP_MAX_BODY_SIZE_CONFIG   (100 * 1024 * 1024)  /* 避免与头文件中的宏冲突 */"

.SS "#define UVHTTP_MAX_BODY_SIZE_CONFIG   (100 * 1024 * 1024)  /* 避免与头文件中的宏冲突 */"

.SS "#define UVHTTP_MAX_BUFFER_SIZE   (1024 * 1024)"

.SS "#define UVHTTP_MAX_CONNECTIONS_HARD   65535  /* 基于系统限制 */"

.SS "#define UVHTTP_MIN_BODY_SIZE   1024"

.SS "#define UVHTTP_MIN_BUFFER_SIZE   1024"

.SS "#define UVHTTP_MIN_CONNECTIONS   1"

.SH "Function Documentation"
.PP 
.SS "void uvhttp_config_free (\fBuvhttp_config_t\fP * config)"

.SS "const \fBuvhttp_config_t\fP* uvhttp_config_get_current (\fBuvhttp_context_t\fP * context)"

.SS "int uvhttp_config_load_env (\fBuvhttp_config_t\fP * config)"

.SS "int uvhttp_config_load_file (\fBuvhttp_config_t\fP * config, const char * filename)"

.SS "int uvhttp_config_monitor_changes (\fBuvhttp_context_t\fP * context, \fBuvhttp_config_change_callback_t\fP callback)"

.SS "\fBuvhttp_config_t\fP* uvhttp_config_new (void)"

.SS "void uvhttp_config_print (const \fBuvhttp_config_t\fP * config)"

.SS "int uvhttp_config_reload (\fBuvhttp_context_t\fP * context)"

.SS "int uvhttp_config_save_file (const \fBuvhttp_config_t\fP * config, const char * filename)"

.SS "void uvhttp_config_set_current (\fBuvhttp_context_t\fP * context, \fBuvhttp_config_t\fP * config)"

.SS "void uvhttp_config_set_defaults (\fBuvhttp_config_t\fP * config)"

.SS "int uvhttp_config_update_max_connections (\fBuvhttp_context_t\fP * context, int max_connections)"

.SS "int uvhttp_config_update_read_buffer_size (\fBuvhttp_context_t\fP * context, int buffer_size)"

.SS "int uvhttp_config_update_size_limits (\fBuvhttp_context_t\fP * context, size_t max_body_size, size_t max_header_size)"

.SS "int uvhttp_config_validate (const \fBuvhttp_config_t\fP * config)"

.SH "Author"
.PP 
Generated automatically by Doxygen for UVHTTP from the source code\&.
