.TH "include/uvhttp.h" 3 "Fri Jan 23 2026" "Version 2.0.0" "UVHTTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/uvhttp.h
.SH SYNOPSIS
.br
.PP
\fC#include 'uvhttp_features\&.h'\fP
.br
\fC#include 'uvhttp_constants\&.h'\fP
.br
\fC#include 'uvhttp_error\&.h'\fP
.br
\fC#include 'uvhttp_utils\&.h'\fP
.br
\fC#include 'uvhttp_server\&.h'\fP
.br
\fC#include 'uvhttp_request\&.h'\fP
.br
\fC#include 'uvhttp_response\&.h'\fP
.br
\fC#include 'uvhttp_router\&.h'\fP
.br
\fC#include 'uvhttp_websocket\&.h'\fP
.br
\fC#include 'uvhttp_tls\&.h'\fP
.br
\fC#include 'uvhttp_static\&.h'\fP
.br
\fC#include 'uvhttp_allocator\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUVHTTP_VERSION_MAJOR\fP   2"
.br
.ti -1c
.RI "#define \fBUVHTTP_VERSION_MINOR\fP   0"
.br
.ti -1c
.RI "#define \fBUVHTTP_VERSION_PATCH\fP   0"
.br
.ti -1c
.RI "#define \fBUVHTTP_VERSION_STRING\fP   '2\&.0\&.0'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define UVHTTP_VERSION_MAJOR   2"

.SS "#define UVHTTP_VERSION_MINOR   0"

.SS "#define UVHTTP_VERSION_PATCH   0"

.SS "#define UVHTTP_VERSION_STRING   '2\&.0\&.0'"

.SH "Author"
.PP 
Generated automatically by Doxygen for UVHTTP from the source code\&.
