.TH "uvhttp_test_connection_provider_t" 3 "Fri Jan 23 2026" "Version 2.0.0" "UVHTTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uvhttp_test_connection_provider_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBuvhttp_connection_provider_t\fP \fBbase\fP"
.br
.ti -1c
.RI "struct \fBuvhttp_connection\fP * \fBtest_connection\fP"
.br
.ti -1c
.RI "int \fBsimulate_connection_failure\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBuvhttp_connection_provider_t\fP uvhttp_test_connection_provider_t::base"

.SS "int uvhttp_test_connection_provider_t::simulate_connection_failure"

.SS "struct \fBuvhttp_connection\fP* uvhttp_test_connection_provider_t::test_connection"


.SH "Author"
.PP 
Generated automatically by Doxygen for UVHTTP from the source code\&.
