.TH "uvhttp_route_match_t" 3 "Fri Jan 23 2026" "Version 2.0.0" "UVHTTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uvhttp_route_match_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <uvhttp_router\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBuvhttp_request_handler_t\fP \fBhandler\fP"
.br
.ti -1c
.RI "\fBuvhttp_param_t\fP \fBparams\fP [16]"
.br
.ti -1c
.RI "size_t \fBparam_count\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBuvhttp_request_handler_t\fP uvhttp_route_match_t::handler"

.SS "size_t uvhttp_route_match_t::param_count"

.SS "\fBuvhttp_param_t\fP uvhttp_route_match_t::params[16]"


.SH "Author"
.PP 
Generated automatically by Doxygen for UVHTTP from the source code\&.
