.TH "uvhttp_ws_config_t" 3 "Fri Jan 23 2026" "Version 2.0.0" "UVHTTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uvhttp_ws_config_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <uvhttp_websocket_native\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBmax_frame_size\fP"
.br
.ti -1c
.RI "int \fBmax_message_size\fP"
.br
.ti -1c
.RI "int \fBping_interval\fP"
.br
.ti -1c
.RI "int \fBping_timeout\fP"
.br
.ti -1c
.RI "int \fBenable_compression\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int uvhttp_ws_config_t::enable_compression"

.SS "int uvhttp_ws_config_t::max_frame_size"

.SS "int uvhttp_ws_config_t::max_message_size"

.SS "int uvhttp_ws_config_t::ping_interval"

.SS "int uvhttp_ws_config_t::ping_timeout"


.SH "Author"
.PP 
Generated automatically by Doxygen for UVHTTP from the source code\&.
