.TH "uvhttp_header_t" 3 "Fri Jan 23 2026" "Version 2.0.0" "UVHTTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uvhttp_header_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <uvhttp_common\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBname\fP [256]"
.br
.ti -1c
.RI "char \fBvalue\fP [4096]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "char uvhttp_header_t::name[256]"

.SS "char uvhttp_header_t::value[4096]"


.SH "Author"
.PP 
Generated automatically by Doxygen for UVHTTP from the source code\&.
