.TH "uvhttp_param_t" 3 "Fri Jan 23 2026" "Version 2.0.0" "UVHTTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uvhttp_param_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <uvhttp_router\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBname\fP [64]"
.br
.ti -1c
.RI "char \fBvalue\fP [256]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "char uvhttp_param_t::name[64]"

.SS "char uvhttp_param_t::value[256]"


.SH "Author"
.PP 
Generated automatically by Doxygen for UVHTTP from the source code\&.
