.TH "whitelist_item" 3 "Fri Jan 23 2026" "Version 2.0.0" "UVHTTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
whitelist_item
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <uvhttp_server\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBip\fP [INET_ADDRSTRLEN]"
.br
.ti -1c
.RI "UT_hash_handle \fBhh\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "UT_hash_handle whitelist_item::hh"

.SS "char whitelist_item::ip[INET_ADDRSTRLEN]"


.SH "Author"
.PP 
Generated automatically by Doxygen for UVHTTP from the source code\&.
