.TH "ws_route_entry" 3 "Fri Jan 23 2026" "Version 2.0.0" "UVHTTP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ws_route_entry
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBpath\fP"
.br
.ti -1c
.RI "\fBuvhttp_ws_handler_t\fP \fBhandler\fP"
.br
.ti -1c
.RI "struct \fBws_route_entry\fP * \fBnext\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBuvhttp_ws_handler_t\fP ws_route_entry::handler"

.SS "struct \fBws_route_entry\fP* ws_route_entry::next"

.SS "char* ws_route_entry::path"


.SH "Author"
.PP 
Generated automatically by Doxygen for UVHTTP from the source code\&.
