#!/usr/bin/env node

/**
 * Batch convert Chinese comments to English using pattern matching
 */

const fs = require('fs');
const path = require('path');

// Common patterns and their replacements
const patterns = [
    // Field size comments
    { regex: /\d+\s+字节\s*-\s*([^*]+)/g, replacement: (match, desc) => `${match.replace(/字节/, 'bytes').trim()}` },
    { regex: /(\d+)\s+字节/g, replacement: '$1 bytes' },
    
    // Common prefixes
    { regex: /哈希表头/g, replacement: 'hash table head' },
    { regex: /LRU链表头/g, replacement: 'LRU list head' },
    { regex: /LRU链表尾/g, replacement: 'LRU list tail' },
    { regex: /LRU缓存管理器/g, replacement: 'LRU cache manager' },
    { regex: /响应体/g, replacement: 'response body' },
    { regex: /文件内容/g, replacement: 'file content' },
    { regex: /大块内存/g, replacement: 'large memory block' },
    { regex: /自定义响应头/g, replacement: 'custom response headers' },
    { regex: /数据缓冲区，至少1字节/g, replacement: 'data buffer, at least 1 byte' },
    { regex: /ETag值/g, replacement: 'ETag value' },
    { regex: /文件路径/g, replacement: 'file path' },
    { regex: /默认索引文件/g, replacement: 'default index file' },
    { regex: /MIME类型/g, replacement: 'MIME type' },
    { regex: /参数名/g, replacement: 'parameter name' },
    { regex: /读缓冲区指针/g, replacement: 'read buffer pointer' },
    { regex: /根目录路径/g, replacement: 'root directory path' },
    { regex: /路径段/g, replacement: 'path segment' },
    { regex: /文件扩展名/g, replacement: 'file extension' },
    { regex: /服务器配置引用/g, replacement: 'server configuration reference' },
    
    // Time units
    { regex: /(\d+)\s*秒/g, replacement: '$1s' },
    { regex: /(\d+)\s*小时/g, replacement: '$1h' },
    { regex: /(\d+)\s*分钟/g, replacement: '$1m' },
    
    // Common phrases
    { regex: /每个连接最大请求数/g, replacement: 'maximum requests per connection' },
    { regex: /硬限制/g, replacement: 'hard limit' },
    { regex: /默认值/g, replacement: 'default value' },
    { regex: /最大推荐值/g, replacement: 'maximum recommended value' },
    { regex: /默认启用/g, replacement: 'enabled by default' },
    { regex: /默认/g, replacement: 'default' },
    { regex: /优化：从/g, replacement: 'optimized: from' },
    { regex: /增加到/g, replacement: 'increased to' },
    { regex: /系统分配器（默认）/g, replacement: 'system allocator (default)' },
    { regex: /避免循环引用/g, replacement: 'avoid circular references' },
    { regex: /释放/g, replacement: 'free' },
    { regex: /创建/g, replacement: 'create' },
    { regex: /启动/g, replacement: 'start' },
    { regex: /回调函数类型/g, replacement: 'callback function type' },
    { regex: /最大缓存时间（秒）/g, replacement: 'maximum cache time (seconds)' },
    { regex: /配置/g, replacement: 'configuration' },
    { regex: /启用/g, replacement: 'enabled' },
    { regex: /禁用/g, replacement: 'disabled' },
    { regex: /模式/g, replacement: 'mode' },
    { regex: /自适应/g, replacement: 'adaptive' },
    { regex: /失败率/g, replacement: 'failure rate' },
    { regex: /平均延迟/g, replacement: 'average latency' },
    { regex: /超时率/g, replacement: 'timeout rate' },
    { regex: /误判率/g, replacement: 'false positive rate' },
    { regex: /用户体验/g, replacement: 'user experience' },
    { regex: /最优/g, replacement: 'optimal' },
    { regex: /收益递减/g, replacement: 'diminishing returns' },
    { regex: /中等访问频率/g, replacement: 'medium access frequency' },
    { regex: /热路径/g, replacement: 'hot path' },
    { regex: /可配置常量定义/g, replacement: 'configurable constant definitions' },
    { regex: /默认配置值/g, replacement: 'default configuration values' },
    { regex: /上下文/g, replacement: 'context' },
    { regex: /路由器/g, replacement: 'router' },
    { regex: /连接对象/g, replacement: 'connection object' },
    { regex: /定时器/g, replacement: 'timer' },
    { regex: /自定义超时时间/g, replacement: 'custom timeout' },
    
    // Comments about configuration
    { regex: /修改常量后需要重新编译/g, replacement: 'recompilation required after modifying constants' },
    { regex: /某些常量的修改可能影响二进制兼容性/g, replacement: 'modifying certain constants may affect binary compatibility' },
    { regex: /编译时配置/g, replacement: 'compile-time configuration' },
    { regex: /性能调优建议/g, replacement: 'performance tuning recommendations' },
    { regex: /内存优化/g, replacement: 'memory optimization' },
    { regex: /增加缓冲区大小会增加内存使用/g, replacement: 'increasing buffer size increases memory usage' },
    { regex: /连接数受限于系统文件描述符数量/g, replacement: 'connection count is limited by system file descriptor count' },
    { regex: /32位系统兼容性宏/g, replacement: '32-bit system compatibility macro' },
    { regex: /32位系统上uint64_t自然对齐为4字节（但大小仍为8字节）/g, replacement: 'uint64_t natural alignment is 4 bytes on 32-bit systems (but size is still 8 bytes)' },
    { regex: /4字节对齐字段/g, replacement: '4-byte aligned field' },
    { regex: /64位系统/g, replacement: '64-bit system' },
    { regex: /8字节对齐字段/g, replacement: '8-byte aligned field' },
    { regex: /API使用说明：/g, replacement: 'API usage instructions:' },
    { regex: /API函数/g, replacement: 'API functions' },
    
    // Performance comments
    { regex: /0次重试：失败率/g, replacement: '0 retries: failure rate' },
    { regex: /1次重试：失败率/g, replacement: '1 retry: failure rate' },
    { regex: /2次重试：失败率/g, replacement: '2 retries: failure rate' },
    { regex: /3次重试：失败率/g, replacement: '3 retries: failure rate' },
    { regex: /10秒超时：/g, replacement: '10s timeout:' },
    { regex: /30秒超时：/g, replacement: '30s timeout:' },
    { regex: /60秒超时：/g, replacement: '60s timeout:' },
    { regex: /5秒超时：/g, replacement: '5s timeout:' },
    { regex: /1秒超时：/g, replacement: '1s timeout:' },
    
    // Other comments
    { regex: /纯线性查找（路由少时最快）/g, replacement: 'pure linear search (fastest when few routes)' },
    { regex: /纯哈希查找（路由多时最快）/g, replacement: 'pure hash search (fastest when many routes)' },
    { regex: /混合策略（自适应，默认）/g, replacement: 'hybrid strategy (adaptive, default)' },
    { regex: /启用动态调整（自适应优化）/g, replacement: 'enable dynamic adjustment (adaptive optimization)' },
    { regex: /Debug 模式下启用日志/g, replacement: 'enable logging in Debug mode' },
    { regex: /Debug 模式下，日志输出到 stderr/g, replacement: 'in Debug mode, logs output to stderr' },
    
    // More translations
    { regex: /create新的/g, replacement: 'create new ' },
    { regex: /start连接超时timer/g, replacement: 'start connection timeout timer' },
    { regex: /custom timeout/g, replacement: 'custom timeout' },
    { regex: /defaultconfiguration值/g, replacement: 'default configuration values' },
    { regex: /可configuration常量定义/g, replacement: 'configurable constant definitions' },
    { regex: /超时统计callback function type/g, replacement: 'timeout statistics callback function type' },
    { regex: /create WebSocket 连接/g, replacement: 'create WebSocket connection' },
    { regex: /create静态文件服务context/g, replacement: 'create static file service context' },
    { regex: /Debug mode下enabled日志/g, replacement: 'enable logging in Debug mode' },
    { regex: /Debug mode且日志功能enabled/g, replacement: 'Debug mode and logging feature enabled' },
    { regex: /系统分配器（default）/g, replacement: 'system allocator (default)' },
    { regex: /disabled缓存/g, replacement: 'disable cache' },
    { regex: /enabled动态调整（adaptive优化）/g, replacement: 'enable dynamic adjustment (adaptive optimization)' },
    { regex: /enabled缓存（如果之前被disabled）/g, replacement: 'enable cache (if previously disabled)' },
    { regex: /file path长度限制/g, replacement: 'file path length limit' },
    { regex: /Free WebSocket 连接/g, replacement: 'Free WebSocket connection' },
    { regex: /Free静态文件服务context/g, replacement: 'Free static file service context' },
    { regex: /Header 名称和值的缓冲区大小（包括空终止符）/g, replacement: 'Header name and value buffer size (including null terminator)' },
    { regex: /Header 名称和值缓冲区大小/g, replacement: 'Header name and value buffer size' },
    { regex: /Header 最大数量限制/g, replacement: 'Header maximum count limit' },
    { regex: /hot path字段（频繁访问）- 优化内存局部性/g, replacement: 'hot path fields (frequently accessed) - optimize memory locality' },
    { regex: /使用uvhttp_request.h中的定义/g, replacement: 'use definitions from uvhttp_request.h' },
    { regex: /HTTP 协议相关/g, replacement: 'HTTP protocol related' },
    { regex: /HTTP 头部configuration/g, replacement: 'HTTP header configuration' },
    { regex: /HTTP 头部常量/g, replacement: 'HTTP header constants' },
    { regex: /HTTP 方法/g, replacement: 'HTTP methods' },
    { regex: /HTTP 版本/g, replacement: 'HTTP version' },
    { regex: /HTTP 状态码/g, replacement: 'HTTP status codes' },
    { regex: /缓存 TTL（秒）/g, replacement: 'cache TTL (seconds)' },
    { regex: /缓存TTL（秒）/g, replacement: 'cache TTL (seconds)' },
    { regex: /是否使用分块传输/g, replacement: 'whether to use chunked transfer encoding' },
    { regex: /待关闭的 handle 计数/g, replacement: 'pending close handle count' },
    { regex: /是否enabled压缩/g, replacement: 'whether compression is enabled' },
    { regex: /连接计数/g, replacement: 'connection count' },
    { regex: /当前头部是否重要/g, replacement: 'whether current header is important' },
    { regex: /是否enabled目录列表/g, replacement: 'whether directory listing is enabled' },
    { regex: /是否enabled连接管理/g, replacement: 'whether connection management is enabled' },
    { regex: /是否enabledETag/g, replacement: 'whether ETag is enabled' },
    { regex: /是否enabledLast-Modified/g, replacement: 'whether Last-Modified is enabled' },
    { regex: /是否enabled sendfile 零拷贝优化/g, replacement: 'whether sendfile zero-copy optimization is enabled' },
    { regex: /缓存条目数/g, replacement: 'cache entry count' },
    { regex: /驱逐次数/g, replacement: 'eviction count' },
    { regex: /响应是否完成/g, replacement: 'whether response is complete' },
    { regex: /头部是否已发送/g, replacement: 'whether headers have been sent' },
    { regex: /心跳间隔（秒）/g, replacement: 'heartbeat interval (seconds)' },
    { regex: /命中次数/g, replacement: 'hit count' },
    { regex: /是否压缩/g, replacement: 'whether compressed' },
    { regex: /是否正在监听/g, replacement: 'whether listening' },
    { regex: /是否参数节点/g, replacement: 'whether parameter node' },
    { regex: /是否为 WebSocket 连接/g, replacement: 'whether WebSocket connection' },
    { regex: /是否保持连接/g, replacement: 'whether to keep connection alive' },
    { regex: /最后的错误码/g, replacement: 'last error code' },
    { regex: /最大缓存条目数/g, replacement: 'maximum cache entry count' },
    { regex: /最大条目数/g, replacement: 'maximum entry count' },
    { regex: /未命中次数/g, replacement: 'miss count' },
    { regex: /是否需要重启读取/g, replacement: 'whether need to restart read' },
    { regex: /是否拥有循环/g, replacement: 'whether owns loop' },
    { regex: /填充到32字节/g, replacement: 'padding to 32 bytes' },
    { regex: /填充到64字节/g, replacement: 'padding to 64 bytes' },
    { regex: /填充到16字节/g, replacement: 'padding to 16 bytes' },
    { regex: /是否正在解析头部字段/g, replacement: 'whether parsing header field' },
    { regex: /是否有待处理的 Ping/g, replacement: 'whether has pending Ping' },
    { regex: /限流是否enabled/g, replacement: 'whether rate limiting is enabled' },
    { regex: /最大请求数/g, replacement: 'maximum requests' },
    { regex: /当前请求数/g, replacement: 'current request count' },
    { regex: /时间窗口（秒）/g, replacement: 'time window (seconds)' },
    { regex: /sendfile 最大重试次数/g, replacement: 'sendfile maximum retry count' },
    { regex: /sendfile 超时时间（毫秒）/g, replacement: 'sendfile timeout time (milliseconds)' },
    { regex: /响应是否已发送/g, replacement: 'whether response has been sent' },
    { regex: /混合策略（adaptive，default）/g, replacement: 'hybrid strategy (adaptive, default)' },
    { regex: /良好（optimal）/g, replacement: 'good (optimal)' },
    { regex: /差/g, replacement: 'poor' },
    { regex: /一般/g, replacement: 'average' },
    { regex: /但连接占用时间长/g, replacement: 'but connection occupies long time' },
    { regex: /但响应时间过长/g, replacement: 'but response time is too long' },
    { regex: /user experience/g, replacement: 'user experience' },
    { regex: /编译时configuration/g, replacement: 'compile-time configuration' },
    { regex: /0次重试：/g, replacement: '0 retries:' },
    { regex: /1次重试：/g, replacement: '1 retry:' },
    { regex: /2次重试：/g, replacement: '2 retries:' },
    { regex: /3次重试：/g, replacement: '3 retries:' },
    { regex: /10s超时：/g, replacement: '10s timeout:' },
    { regex: /1s超时：/g, replacement: '1s timeout:' },
    { regex: /30s超时：/g, replacement: '30s timeout:' },
    { regex: /5s超时：/g, replacement: '5s timeout:' },
    { regex: /60s超时：/g, replacement: '60s timeout:' },
    { regex: /（optimal）/g, replacement: ' (optimal)' },
    { regex: /（diminishing returns）/g, replacement: ' (diminishing returns)' },
    { regex: /（秒）/g, replacement: ' (seconds)' },
    
    // More translations
    { regex: /Debug mode下，日志输出到 stderr/g, replacement: 'Debug mode, logs output to stderr' },
    { regex: /最大cache entry count/g, replacement: 'maximum cache entry count' },
    { regex: /未hit count/g, replacement: 'miss count' },
    { regex: /40字节 - padding to 64 bytes/g, replacement: '40 bytes - padding to 64 bytes' },
    { regex: /12字节 - padding to 16 bytes/g, replacement: '12 bytes - padding to 16 bytes' },
    { regex: /16字节 - padding to 64 bytes/g, replacement: '16 bytes - padding to 64 bytes' },
    { regex: /56字节 - padding to 64 bytes/g, replacement: '56 bytes - padding to 64 bytes' },
    { regex: /48字节 - padding to 64 bytes/g, replacement: '48 bytes - padding to 64 bytes' },
    { regex: /64字节 - padding to 64 bytes/g, replacement: '64 bytes - padding to 64 bytes' },
    { regex: /32字节 - padding to 64 bytes/g, replacement: '32 bytes - padding to 64 bytes' },
    { regex: /超时时间 \(seconds\)/g, replacement: 'timeout time (seconds)' },
    { regex: /TLS 是否enabled/g, replacement: 'whether TLS is enabled' },
    { regex: /是否使用Trie/g, replacement: 'whether to use Trie' },
    { regex: /IP 地址和端口configuration/g, replacement: 'IP address and port configuration' },
    { regex: /IP 地址验证configuration/g, replacement: 'IP address validation configuration' },
    { regex: /Linux 系统参数优化：/g, replacement: 'Linux system parameter optimization:' },
    { regex: /LRU 缓存configuration/g, replacement: 'LRU cache configuration' },
    { regex: /LRU缓存条件编译支持/g, replacement: 'LRU cache conditional compilation support' },
    { regex: /LRU缓存条目结构/g, replacement: 'LRU cache entry structure' },
    { regex: /LRU链表句柄/g, replacement: 'LRU list handle' },
    { regex: /mimalloc 不可用，回退到系统分配器/g, replacement: 'mimalloc not available, fallback to system allocator' },
    { regex: /MIME type映射条目/g, replacement: 'MIME type mapping entry' },
    { regex: /MONITORING: enabled性能监控（生产环境慎用）/g, replacement: 'MONITORING: enable performance monitoring (use with caution in production)' },
    { regex: /Nginx 优化：使用 sendfile 零拷贝发送静态文件（混合策略）/g, replacement: 'Nginx optimization: use sendfile zero-copy to send static files (hybrid strategy)' },
    { regex: /失败时，\*conn 被设置为 NULL/g, replacement: 'on failure, *conn is set to NULL' },
    { regex: /失败时，\*ctx 被设置为 NULL/g, replacement: 'on failure, *ctx is set to NULL' },
    { regex: /失败时，\*router 被设置为 NULL/g, replacement: 'on failure, *router is set to NULL' },
    { regex: /如果超时时间过大导致整数溢出，返回 UVHTTP_ERROR_INVALID_PARAM/g, replacement: 'if timeout is too large causing integer overflow, return UVHTTP_ERROR_INVALID_PARAM' },
    { regex: /成功时，\*conn 被设置为有效的connection object，必须使用 uvhttp_connection_free/g, replacement: 'on success, *conn is set to a valid connection object, must use uvhttp_connection_free' },
    { regex: /成功时，\*ctx 被设置为有效的 TLS context对象，必须使用/g, replacement: 'on success, *ctx is set to a valid TLS context object, must use' },
    { regex: /成功时，\*router 被设置为有效的router对象，必须使用 uvhttp_router_free/g, replacement: 'on success, *router is set to a valid router object, must use uvhttp_router_free' },
    { regex: /超时时间从 conn->server->config->connection_timeout 读取，/g, replacement: 'timeout is read from conn->server->config->connection_timeout,' },
    { regex: /超时时间必须在 UVHTTP_CONNECTION_TIMEOUT_MIN 和/g, replacement: 'timeout must be between UVHTTP_CONNECTION_TIMEOUT_MIN and' },
    { regex: /OCSP装订/g, replacement: 'OCSP stapling' },
    { regex: /cache TTL \(seconds\)，0表示永不过期/g, replacement: 'cache TTL (seconds), 0 means never expire' },
    { regex: /缓存TTL/g, replacement: 'cache TTL' },
    { regex: /输出参数，返回create的缓存管理器指针/g, replacement: 'output parameter, returns pointer to created cache manager' },
    { regex: /分块大小（字节），0 表示使用default value/g, replacement: 'chunk size (bytes), 0 means use default value' },
    { regex: /静态文件configuration/g, replacement: 'static file configuration' },
    { regex: /输出参数，用于接收连接指针/g, replacement: 'output parameter, receives connection pointer' },
    { regex: /内容长度/g, replacement: 'content length' },
    { regex: /输出参数，返回create的context/g, replacement: 'output parameter, returns created context' },
    { regex: /输出参数，用于接收 TLS context指针/g, replacement: 'output parameter, receives TLS context pointer' },
    { regex: /目录路径（相对于根目录）/g, replacement: 'directory path (relative to root directory)' },
    { regex: /文件ETag/g, replacement: 'file ETag' },
    { regex: /输出ETag缓冲区/g, replacement: 'output ETag buffer' },
    { regex: /File path（相对于根目录）/g, replacement: 'File path (relative to root directory)' },
    { regex: /请求的file path/g, replacement: 'requested file path' },
    { regex: /最大文件数（0表示无限制）/g, replacement: 'maximum file count (0 means unlimited)' },
    { regex: /最大内存使用量（字节）/g, replacement: 'maximum memory usage (bytes)' },
    { regex: /最大内存使用量/g, replacement: 'maximum memory usage' },
    { regex: /最大重试次数，0 表示使用default value/g, replacement: 'maximum retry count, 0 means use default value' },
    { regex: /输出MIME type缓冲区/g, replacement: 'output MIME type buffer' },
    { regex: /解析后的安全路径/g, replacement: 'resolved safe path' },
    { regex: /根目录/g, replacement: 'root directory' },
    { regex: /输出参数，用于接收router指针/g, replacement: 'output parameter, receives router pointer' },
    { regex: /服务器对象/g, replacement: 'server object' },
    { regex: /超时时间（毫秒），0 表示使用default value/g, replacement: 'timeout time (milliseconds), 0 means use default value' },
    { regex: /超时时间 \(seconds\)，范围：5-300/g, replacement: 'timeout time (seconds), range: 5-300' },
    { regex: /Rate limiting configuration验证常量/g, replacement: 'Rate limiting configuration validation constants' },
    { regex: /白名单哈希表/g, replacement: 'whitelist hash table' },
    { regex: /Release mode或日志功能disabled时，日志宏为空操作/g, replacement: 'in Release mode or when logging feature is disabled, logging macros are no-ops' },
    { regex: /1安全，0不安全/g, replacement: '1 for safe, 0 for unsafe' },
    { regex: /1过期，0未过期/g, replacement: '1 for expired, 0 for not expired' },
    { regex: /1需要返回304，0需要返回完整内容/g, replacement: '1 for need to return 304, 0 for need to return full content' },
    { regex: /成功返回 UVHTTP_OK，失败返回负数错误码/g, replacement: 'returns UVHTTP_OK on success, negative error code on failure' },
    { regex: /缓存条目指针，未找到返回NULL/g, replacement: 'cache entry pointer, returns NULL if not found' },
    { regex: /被移除的条目指针/g, replacement: 'pointer to removed entry' },
    { regex: /预热的文件数量，-1表示失败/g, replacement: 'number of prewarmed files, -1 means failure' },
    { regex: /活跃连接数/g, replacement: 'active connection count' },
    
    // More translations
    { regex: /timeout time \(seconds\)，范围：5-300/g, replacement: 'timeout time (seconds), range: 5-300' },
    { regex: /已接收的 body 长度/g, replacement: 'received body length' },
    { regex: /当前头部字段长度/g, replacement: 'current header field length' },
    { regex: /最大缓存大小（字节）/g, replacement: 'maximum cache size (bytes)' },
    { regex: /最大连接数/g, replacement: 'maximum connections' },
    { regex: /最大内存限制/g, replacement: 'maximum memory limit' },
    { regex: /最大消息大小/g, replacement: 'maximum message size' },
    { regex: /内存使用量/g, replacement: 'memory usage' },
    { regex: /白名单数量/g, replacement: 'whitelist count' },
    { regex: /读缓冲区大小/g, replacement: 'read buffer size' },
    { regex: /读缓冲区已使用/g, replacement: 'read buffer used' },
    { regex: /总路由数量/g, replacement: 'total route count' },
    { regex: /sendfile 分块大小（字节）/g, replacement: 'sendfile chunk size (bytes)' },
    { regex: /总内存使用/g, replacement: 'total memory usage' },
    { regex: /Socket 缓冲区大小/g, replacement: 'Socket buffer size' },
    { regex: /start服务器：/g, replacement: 'start server:' },
    { regex: /STATS: enabled统计功能（调试用）/g, replacement: 'STATS: enable statistics (for debugging)' },
    { regex: /应用context/g, replacement: 'application context' },
    { regex: /子节点/g, replacement: 'child nodes' },
    { regex: /所属服务器/g, replacement: 'server' },
    { regex: /TCP backlog（待处理连接队列长度）/g, replacement: 'TCP backlog (pending connection queue length)' },
    { regex: /最后访问时间/g, replacement: 'last access time' },
    { regex: /缓存过期时间/g, replacement: 'cache expiration time' },
    { regex: /缓存时间/g, replacement: 'cache time' },
    { regex: /最后修改时间/g, replacement: 'last modified time' },
    { regex: /TLS 1.3支持/g, replacement: 'TLS 1.3 support' },
    { regex: /TLScontext管理/g, replacement: 'TLS context management' },
    { regex: /TLScontext类型定义/g, replacement: 'TLS context type definition' },
    { regex: /TLS函数声明 \(暂时disabled\)/g, replacement: 'TLS function declarations (temporarily disabled)' },
    { regex: /TLS处理函数/g, replacement: 'TLS handling functions' },
    { regex: /TLS安全configuration/g, replacement: 'TLS security configuration' },
    { regex: /TLS性能监控/g, replacement: 'TLS performance monitoring' },
    { regex: /TLS模块管理/g, replacement: 'TLS module management' },
    { regex: /TLS 缓冲区大小/g, replacement: 'TLS buffer size' },
    { regex: /TLS连接管理/g, replacement: 'TLS connection management' },
    { regex: /TLS 错误码范围/g, replacement: 'TLS error code range' },
    { regex: /TLS 非阻塞状态（正数）/g, replacement: 'TLS non-blocking state (positive)' },
    { regex: /TLS 验证和会话configuration/g, replacement: 'TLS validation and session configuration' },
    { regex: /Trie路由相关（8字节对齐）/g, replacement: 'Trie routing related (8-byte aligned)' },
    { regex: /最后活动时间（毫秒）/g, replacement: 'last activity time (milliseconds)' },
    { regex: /最后发送 Ping 的时间（毫秒）/g, replacement: 'last Ping sent time (milliseconds)' },
    { regex: /Ping 超时时间（毫秒）/g, replacement: 'Ping timeout time (milliseconds)' },
    { regex: /窗口开始时间/g, replacement: 'window start time' },
    { regex: /URL 最大长度（字节）/g, replacement: 'URL maximum length (bytes)' },
    { regex: /URL、路径、方法长度限制/g, replacement: 'URL, path, method length limits' },
    { regex: /uthash哈希句柄/g, replacement: 'uthash hash handle' },
    { regex: /连接状态/g, replacement: 'connection state' },
    { regex: /UVHTTP_CONNECTION_TIMEOUT_MAX 之间/g, replacement: 'UVHTTP_CONNECTION_TIMEOUT_MAX' },
    { regex: /已删除 - 未使用/g, replacement: 'removed - unused' },
    
    // More translations
    { regex: /动态计算最大值/g, replacement: 'dynamically calculated maximum value' },
    { regex: /已删除 - 完全未使用/g, replacement: 'removed - completely unused' },
    { regex: /UVHTTP LRU缓存模块 - 基于uthash实现/g, replacement: 'UVHTTP LRU cache module - based on uthash implementation' },
    { regex: /UVHTTP_MAX_HEADER_NAME_SIZE: 256字节（RFC 7230 建议）/g, replacement: 'UVHTTP_MAX_HEADER_NAME_SIZE: 256 bytes (RFC 7230 recommended)' },
    { regex: /UVHTTP_MAX_HEADER_VALUE_SIZE: 4096字节（支持 GitHub CSP）/g, replacement: 'UVHTTP_MAX_HEADER_VALUE_SIZE: 4096 bytes (supports GitHub CSP)' },
    { regex: /请求处理器/g, replacement: 'request handler' },
    { regex: /请求对象/g, replacement: 'request object' },
    { regex: /响应对象/g, replacement: 'response object' },
    { regex: /UVHTTP WebSocket 实现/g, replacement: 'UVHTTP WebSocket implementation' },
    { regex: /UVHTTP 中间件系统 - 编译期configuration版本/g, replacement: 'UVHTTP middleware system - compile-time configuration version' },
    { regex: /UVHTTP - 平台兼容性头文件/g, replacement: 'UVHTTP - platform compatibility header file' },
    { regex: /UVHTTP 日志宏/g, replacement: 'UVHTTP logging macros' },
    { regex: /UVHTTP - 超轻量级HTTP服务器库 - API版本/g, replacement: 'UVHTTP - ultra-lightweight HTTP server library - API version' },
    { regex: /UVHTTP 静态文件服务模块 - 统一版本，支持可选LRU缓存/g, replacement: 'UVHTTP static file service module - unified version, supports optional LRU cache' },
    { regex: /约24-32字节/g, replacement: 'about 24-32 bytes' },
    { regex: /约40-48字节/g, replacement: 'about 40-48 bytes' },
    { regex: /事件循环/g, replacement: 'event loop' },
    { regex: /心跳检测timer/g, replacement: 'heartbeat detection timer' },
    { regex: /超时检测timer/g, replacement: 'timeout detection timer' },
    { regex: /白名单数组/g, replacement: 'whitelist array' },
    { regex: /应用数据/g, replacement: 'application data' },
    { regex: /WebSocket 连接/g, replacement: 'WebSocket connection' },
    { regex: /WebSocket 路由表（已废弃）/g, replacement: 'WebSocket routing table (deprecated)' },
    { regex: /WebSocket configuration验证常量/g, replacement: 'WebSocket configuration validation constants' },
    { regex: /WebSocket maximum message size（字节）/g, replacement: 'WebSocket maximum message size (bytes)' },
    { regex: /WebSocket Ping 超时 \(seconds\)/g, replacement: 'WebSocket Ping timeout (seconds)' },
    { regex: /WebSocket Ping 间隔 \(seconds\)/g, replacement: 'WebSocket Ping interval (seconds)' },
    { regex: /WebSocket 位掩码/g, replacement: 'WebSocket bit mask' },
    { regex: /WebSocket 关闭码范围/g, replacement: 'WebSocket close code range' },
    { regex: /WebSocket处理函数（内部）/g, replacement: 'WebSocket handling functions (internal)' },
    { regex: /WebSocket 密钥长度限制/g, replacement: 'WebSocket key length limit' },
    { regex: /WebSocket 帧头 \(RFC 6455\)/g, replacement: 'WebSocket frame header (RFC 6455)' },
    { regex: /WebSocket 帧结构/g, replacement: 'WebSocket frame structure' },
    { regex: /WebSocket 接收缓冲区大小（字节）/g, replacement: 'WebSocket receive buffer size (bytes)' },
    { regex: /WebSocket 操作码/g, replacement: 'WebSocket opcode' },
    { regex: /WebSocket 操作码 \(RFC 6455\)/g, replacement: 'WebSocket opcode (RFC 6455)' },
    { regex: /WebSocket 最大帧大小（字节）/g, replacement: 'WebSocket maximum frame size (bytes)' },
    { regex: /WebSocket 版本和协议/g, replacement: 'WebSocket version and protocol' },
    { regex: /WebSocket 状态/g, replacement: 'WebSocket state' },
    { regex: /WebSocket 连接/g, replacement: 'WebSocket connection' },
    { regex: /WebSocket 连接管理器/g, replacement: 'WebSocket connection manager' },
    { regex: /WebSocket 连接节点/g, replacement: 'WebSocket connection node' },
    { regex: /WebSocket 错误码范围/g, replacement: 'WebSocket error code range' },
    { regex: /whitelist hash table项/g, replacement: 'whitelist hash table entry' },
    { regex: /WebSocket 连接管理器/g, replacement: 'WebSocket connection manager' },
    { regex: /连接链表/g, replacement: 'connection list' },
    { regex: /一键start函数（最简API）/g, replacement: 'one-click start function (simplest API)' },
    { regex: /中型应用（1000-10000 RPS）：2048-4096（default 2048）/g, replacement: 'medium applications (1000-10000 RPS): 2048-4096 (default 2048)' },
    { regex: /增加连接数和缓冲区大小/g, replacement: 'increase connections and buffer size' },
    
    // More translations
    { regex: /WebSocket connection管理器/g, replacement: 'WebSocket connection manager' },
    { regex: /WebSocket connection节点/g, replacement: 'WebSocket connection node' },
    { regex: /WebSocket connection管理器/g, replacement: 'WebSocket connection manager' },
    { regex: /中型应用：10MB（default）/g, replacement: 'medium applications: 10MB (default)' },
    { regex: /中型应用：16384 \(16KB\) - default/g, replacement: 'medium applications: 16384 (16KB) - default' },
    { regex: /中型应用：1MB - default value/g, replacement: 'medium applications: 1MB - default value' },
    { regex: /中型应用：2048（default）/g, replacement: 'medium applications: 2048 (default)' },
    { regex: /中型应用：256（default）/g, replacement: 'medium applications: 256 (default)' },
    { regex: /中型应用：32-64（default）/g, replacement: 'medium applications: 32-64 (default)' },
    { regex: /中型应用：4096/g, replacement: 'medium applications: 4096' },
    { regex: /中型应用：8192 \(8KB\) - 平衡性能和内存（default）/g, replacement: 'medium applications: 8192 (8KB) - balance performance and memory (default)' },
    { regex: /中型应用configuration（平衡）：/g, replacement: 'medium applications configuration (balanced):' },
    { regex: /中等文件 \(4KB - 10MB\): 使用异步 sendfile/g, replacement: 'medium files (4KB - 10MB): use async sendfile' },
    { regex: /中间件configuration/g, replacement: 'middleware configuration' },
    { regex: /中间件context/g, replacement: 'middleware context' },
    { regex: /中间件处理函数类型/g, replacement: 'middleware handler function type' },
    { regex: /中间件返回值/g, replacement: 'middleware return value' },
    { regex: /为连接start超时timer，使用configuration中的default超时时间。/g, replacement: 'start timeout timer for connection, use default timeout time from configuration.' },
    { regex: /为连接start超时timer，使用指定的超时时间。/g, replacement: 'start timeout timer for connection, use specified timeout time.' },
    { regex: /从LRU list tail部移除条目/g, replacement: 'remove entry from LRU list tail' },
    { regex: /优化说明：增大缓冲区可以减少 I\/O 操作次数，提升大文件传输性能/g, replacement: 'optimization note: increasing buffer size can reduce I/O operations and improve large file transfer performance' },
    { regex: /优化说明：增大缓冲区可以减少系统调用次数，提升性能/g, replacement: 'optimization note: increasing buffer size can reduce system calls and improve performance' },
    { regex: /会话票证优化/g, replacement: 'session ticket optimization' },
    { regex: /使用示例：/g, replacement: 'usage example:' },
    { regex: /使用说明/g, replacement: 'usage instructions' },
    { regex: /便捷宏/g, replacement: 'convenience macros' },
    { regex: /便捷请求参数获取/g, replacement: 'convenient request parameter retrieval' },
    { regex: /保持向后兼容的别名/g, replacement: 'backward compatibility alias' },
    { regex: /关闭连接/g, replacement: 'close connection' },
    { regex: /内存configurationdefault value/g, replacement: 'memory configuration default values' },
    { regex: /内存受限环境：减小缓冲区大小，disable cache/g, replacement: 'memory-constrained environment: reduce buffer size, disable cache' },
    { regex: /内存池大小（字节）/g, replacement: 'memory pool size (bytes)' },
    { regex: /内存警告阈值/g, replacement: 'memory warning threshold' },
    { regex: /内存页面对齐/g, replacement: 'memory page alignment' },
    { regex: /内容类型/g, replacement: 'content type' },
    { regex: /内联 header 容量/g, replacement: 'inline header capacity' },
    { regex: /内联验证函数/g, replacement: 'inline validation functions' },
    { regex: /内部函数/g, replacement: 'internal functions' },
    { regex: /内部函数声明/g, replacement: 'internal function declarations' },
    { regex: /内部函数（由 uvhttp_connection 调用）/g, replacement: 'internal functions (called by uvhttp_connection)' },
    { regex: /函数宏/g, replacement: 'function macros' },
    { regex: /分块大小（用于动态分块大小调整）/g, replacement: 'chunk size (for dynamic chunk size adjustment)' },
    { regex: /分片重组/g, replacement: 'fragment reassembly' },
    { regex: /分配器信息/g, replacement: 'allocator information' },
    { regex: /分配器错误码范围/g, replacement: 'allocator error code range' },
    { regex: /删除缓存条目/g, replacement: 'delete cache entry' },
    { regex: /副作用函数：发送原始数据，包含网络I\/O/g, replacement: 'side effect function: send raw data, includes network I/O' },
    { regex: /功能开关default value/g, replacement: 'feature switch default values' },
    { regex: /包含default configuration values/g, replacement: 'includes default configuration values' },
    { regex: /包含uthash头文件/g, replacement: 'includes uthash header file' },
    { regex: /包含 uthash 头文件用于哈希表实现/g, replacement: 'includes uthash header file for hash table implementation' },
    { regex: /包含常量定义/g, replacement: 'includes constant definitions' },
    { regex: /危险字符常量/g, replacement: 'dangerous character constants' },
    
    // More translations
    { regex: /原有函数/g, replacement: 'original functions' },
    { regex: /参数解析/g, replacement: 'parameter parsing' },
    { regex: /发送 Ping/g, replacement: 'send Ping' },
    { regex: /发送 Pong/g, replacement: 'send Pong' },
    { regex: /发送 WebSocket 帧/g, replacement: 'send WebSocket frame' },
    { regex: /发送二进制消息/g, replacement: 'send binary message' },
    { regex: /发送文本消息/g, replacement: 'send text message' },
    { regex: /发送缓冲区/g, replacement: 'send buffer' },
    { regex: /可选功能/g, replacement: 'optional features' },
    { regex: /可选功能的条件包含/g, replacement: 'conditional includes for optional features' },
    { regex: /向后兼容的宏别名/g, replacement: 'backward compatible macro aliases' },
    { regex: /哈希configurationdefault value/g, replacement: 'hash configuration default values' },
    { regex: /哈希种子/g, replacement: 'hash seed' },
    { regex: /响应发送函数/g, replacement: 'response send functions' },
    { regex: /响应头和消息/g, replacement: 'response headers and messages' },
    { regex: /回调函数/g, replacement: 'callback function' },
    { regex: /回退路由支持/g, replacement: 'fallback route support' },
    { regex: /回退路由支持（8字节对齐）/g, replacement: 'fallback route support (8-byte aligned)' },
    { regex: /固定管线：中间件顺序在编译时确定/g, replacement: 'fixed pipeline: middleware order determined at compile time' },
    { regex: /在32位系统上，size_t是4字节，但uint64_t仍然是8字节/g, replacement: 'on 32-bit systems, size_t is 4 bytes, but uint64_t is still 8 bytes' },
    { regex: /在 HTTP 解析过程中频繁访问/g, replacement: 'frequently accessed during HTTP parsing' },
    { regex: /在 on_connection、连接管理中频繁访问/g, replacement: 'frequently accessed in on_connection, connection management' },
    { regex: /在 on_read、on_write、连接管理中频繁访问/g, replacement: 'frequently accessed in on_read, on_write, connection management' },
    { regex: /在响应构建、发送过程中频繁访问/g, replacement: 'frequently accessed during response building and sending' },
    { regex: /在响应构建、缓存管理中频繁访问/g, replacement: 'frequently accessed in response building, cache management' },
    { regex: /在服务器初始化、请求路由中频繁访问/g, replacement: 'frequently accessed in server initialization, request routing' },
    { regex: /在连接create、销毁、请求处理中频繁访问/g, replacement: 'frequently accessed in connection creation, destruction, request processing' },
    { regex: /基础宏定义/g, replacement: 'basic macro definitions' },
    { regex: /增加缓冲区大小以防止溢出，符合HTTP规范/g, replacement: 'increase buffer size to prevent overflow, complies with HTTP specification' },
    { regex: /处理器应该检查响应是否已经被发送，或者直接返回/g, replacement: 'handler should check if response has been sent, or return directly' },
    { regex: /处理接收到的数据/g, replacement: 'handle received data' },
    { regex: /\/\* 处理请求... \*\//g, replacement: '// process request...' },
    { regex: /处理静态文件请求/g, replacement: 'handle static file request' },
    { regex: /复杂应用：可以increased to 512 或 1024/g, replacement: 'complex applications: can be increased to 512 or 1024' },
    { regex: /大型应用：10000/g, replacement: 'large applications: 10000' },
    { regex: /大型应用（> 10000 RPS）：8192-10000/g, replacement: 'large applications (> 10000 RPS): 8192-10000' },
    { regex: /大型应用（> 10000 RPS）：需要系统调优，参考下面的大型应用configuration/g, replacement: 'large applications (> 10000 RPS): requires system tuning, refer to large application configuration below' },
    { regex: /大型应用：100MB-1GB/g, replacement: 'large applications: 100MB-1GB' },
    { regex: /大型应用：10MB - 支持大文件上传/g, replacement: 'large applications: 10MB - supports large file uploads' },
    { regex: /大型应用：128-256/g, replacement: 'large applications: 128-256' },
    { regex: /大型应用：16384 \(16KB\) - 高性能，更多内存/g, replacement: 'large applications: 16384 (16KB) - high performance, more memory' },
    { regex: /大型应用：32768 \(32KB\) - 高吞吐量/g, replacement: 'large applications: 32768 (32KB) - high throughput' },
    { regex: /大型应用：8192/g, replacement: 'large applications: 8192' },
    { regex: /大型应用：8192（default）/g, replacement: 'large applications: 8192 (default)' },
    { regex: /大型应用configuration（性能优先）：/g, replacement: 'large applications configuration (performance优先):' },
    { regex: /大多数应用：256 bytes足够/g, replacement: 'most applications: 256 bytes sufficient' },
    { regex: /大文件 \(> 10MB\): 使用分块 sendfile/g, replacement: 'large files (> 10MB): use chunked sendfile' },
    { regex: /大文件为主：128KB（default）/g, replacement: 'large file focused: 128KB (default)' },
    { regex: /大文件为主：32KB/g, replacement: 'large file focused: 32KB' },
    { regex: /大文件为主：64KB（default）/g, replacement: 'large file focused: 64KB (default)' },
    { regex: /大消息应用：128MB\+/g, replacement: 'large message applications: 128MB+' },
    
    // More translations
    { regex: /大消息应用：32MB\+/g, replacement: 'large message applications: 32MB+' },
    { regex: /大消息应用可以增加 UVHTTP_WEBSOCKET_DEFAULT_MAX_FRAME_SIZE/g, replacement: 'large message applications can increase UVHTTP_WEBSOCKET_DEFAULT_MAX_FRAME_SIZE' },
    { regex: /大消息应用可以增加这些值/g, replacement: 'large message applications can increase these values' },
    { regex: /头文件包含/g, replacement: 'header file includes' },
    { regex: /如果 config 为 NULL，则使用 UVHTTP_CONNECTION_TIMEOUT_DEFAULT/g, replacement: 'if config is NULL, use UVHTTP_CONNECTION_TIMEOUT_DEFAULT' },
    { regex: /如果中间件返回 UVHTTP_MIDDLEWARE_STOP，表示中间件已经处理了请求/g, replacement: 'if middleware returns UVHTTP_MIDDLEWARE_STOP, it means middleware has processed the request' },
    { regex: /如果需要支持超长 header，可以增加这些值/g, replacement: 'if need to support extra long headers, can increase these values' },
    { regex: /字符串化宏/g, replacement: 'stringification macro' },
    { regex: /字符串处理常量/g, replacement: 'string processing constants' },
    { regex: /字符串字段 - 冷路径/g, replacement: 'string fields - cold path' },
    { regex: /安全configurationdefault value/g, replacement: 'security configuration default values' },
    { regex: /安全提示：/g, replacement: 'security note:' },
    { regex: /安全的字符串复制函数/g, replacement: 'safe string copy function' },
    { regex: /安全的字符串操作/g, replacement: 'safe string operations' },
    { regex: /安全边距：/g, replacement: 'safety margin:' },
    { regex: /完全自主实现的 WebSocket 协议支持，基于 RFC 6455/g, replacement: 'fully self-implemented WebSocket protocol support, based on RFC 6455' },
    { regex: /宏定义/g, replacement: 'macro definitions' },
    { regex: /定义中间件链（供复用）/g, replacement: 'define middleware chain (for reuse)' },
    { regex: /客户端 IP 缓冲区大小/g, replacement: 'client IP buffer size' },
    { regex: /客户端握手时保存的原始 key（用于验证 accept）/g, replacement: 'original key saved during client handshake (for accept verification)' },
    { regex: /对于大型应用（> 10000 RPS），需要调整系统参数：/g, replacement: 'for large applications (> 10000 RPS), need to adjust system parameters:' },
    { regex: /对齐验证宏 - 根据平台adaptive/g, replacement: 'alignment validation macros - adaptive based on platform' },
    { regex: /小型应用（< 1000 RPS）：512-1024/g, replacement: 'small applications (< 1000 RPS): 512-1024' },
    { regex: /小型应用（< 1000 RPS）：使用defaultconfiguration/g, replacement: 'small applications (< 1000 RPS): use default configuration' },
    { regex: /小型应用：16/g, replacement: 'small applications: 16' },
    { regex: /小型应用：1MB/g, replacement: 'small applications: 1MB' },
    { regex: /小型应用：1MB（default）/g, replacement: 'small applications: 1MB (default)' },
    { regex: /小型应用：256KB - 防止大文件上传/g, replacement: 'small applications: 256KB - prevent large file uploads' },
    { regex: /小型应用：4096 \(4KB\) - 节省内存/g, replacement: 'small applications: 4096 (4KB) - save memory' },
    { regex: /小型应用：512/g, replacement: 'small applications: 512' },
    { regex: /小型应用：8192 \(8KB\)/g, replacement: 'small applications: 8192 (8KB)' },
    { regex: /小型应用configuration（内存优先）：/g, replacement: 'small applications configuration (memory优先):' },
    { regex: /小文件 \(< 4KB\): 使用传统方式（避免 sendfile 开销）/g, replacement: 'small files (< 4KB): use traditional method (avoid sendfile overhead)' },
    { regex: /小文件为主：16KB（default）/g, replacement: 'small file focused: 16KB (default)' },
    { regex: /小文件为主：32KB/g, replacement: 'small file focused: 32KB' },
    { regex: /小文件为主：64KB/g, replacement: 'small file focused: 64KB' },
    { regex: /小消息应用：1MB/g, replacement: 'small message applications: 1MB' },
    { regex: /小消息应用：8MB/g, replacement: 'small message applications: 8MB' },
    { regex: /布尔值宏/g, replacement: 'boolean value macros' },
    { regex: /帧处理函数/g, replacement: 'frame processing functions' },
    { regex: /常用响应头名称/g, replacement: 'common response header names' },
    { regex: /平台检测 - 只支持 Linux/g, replacement: 'platform detection - only supports Linux' },
    { regex: /应用层主导：中间件逻辑由应用层实现/g, replacement: 'application layer主导: middleware logic implemented by application layer' },
    { regex: /应用掩码/g, replacement: 'application mask' },
    { regex: /应用限制/g, replacement: 'application limits' },
    { regex: /异步文件 I\/O 缓冲区大小（字节）- 性能优化/g, replacement: 'async file I/O buffer size (bytes) - performance optimization' },
    { regex: /必须先包含 stdint.h 才能使用 UINTPTR_MAX/g, replacement: 'must include stdint.h before using UINTPTR_MAX' },
    
    // More translations
    { regex: /快速create和start服务器/g, replacement: 'quickly create and start server' },
    { regex: /性能测试依据（2026-01-30 性能基准测试）：/g, replacement: 'performance test basis (2026-01-30 performance benchmark test):' },
    { regex: /性能测试依据（2026-01-30 缓存性能测试）：/g, replacement: 'performance test basis (2026-01-30 cache performance test):' },
    { regex: /性能测试依据（2026-01-30 限流性能测试）：/g, replacement: 'performance test basis (2026-01-30 rate limit performance test):' },
    { regex: /所有default value都可以通过 CMake 编译选项覆盖/g, replacement: 'all default values can be overridden by CMake compilation options' },
    { regex: /执行 WebSocket 握手 \(客户端\)/g, replacement: 'perform WebSocket handshake (client)' },
    { regex: /执行 WebSocket 握手 \(服务器端\)/g, replacement: 'perform WebSocket handshake (server)' },
    { regex: /执行中间件链/g, replacement: 'execute middleware chain' },
    { regex: /执行预定义的中间件链/g, replacement: 'execute predefined middleware chain' },
    { regex: /批量驱逐10：平均驱逐延迟 0\.9ms，缓存命中率 95% \(optimal\)/g, replacement: 'batch eviction 10: average eviction latency 0.9ms, cache hit rate 95% (optimal)' },
    { regex: /批量驱逐20：平均驱逐延迟 1\.5ms，缓存命中率 96%（延迟增加）/g, replacement: 'batch eviction 20: average eviction latency 1.5ms, cache hit rate 96% (increased latency)' },
    { regex: /批量驱逐50：平均驱逐延迟 3\.2ms，缓存命中率 97%（延迟过高）/g, replacement: 'batch eviction 50: average eviction latency 3.2ms, cache hit rate 97% (excessive latency)' },
    { regex: /批量驱逐5：平均驱逐延迟 0\.8ms，缓存命中率 92%/g, replacement: 'batch eviction 5: average eviction latency 0.8ms, cache hit rate 92%' },
    { regex: /指针大小检测/g, replacement: 'pointer size detection' },
    { regex: /接收 WebSocket 帧/g, replacement: 'receive WebSocket frame' },
    { regex: /接收缓冲区/g, replacement: 'receive buffer' },
    { regex: /控制字符/g, replacement: 'control characters' },
    { regex: /控制待处理连接队列长度/g, replacement: 'control pending connection queue length' },
    { regex: /推荐mode：在中间件返回 STOP 后，处理器应该立即返回/g, replacement: 'recommended mode: after middleware returns STOP, handler should return immediately' },
    { regex: /推荐使用 CMake 选项，便于维护和版本控制/g, replacement: 'recommend using CMake options for easier maintenance and version control' },
    { regex: /数组路由相关（8字节对齐）/g, replacement: 'array routing related (8-byte aligned)' },
    { regex: /文件 I\/O 缓冲区大小/g, replacement: 'file I/O buffer size' },
    { regex: /文件上传应用：10-100MB/g, replacement: 'file upload applications: 10-100MB' },
    { regex: /文件响应最大文件大小（字节）/g, replacement: 'file response maximum file size (bytes)' },
    { regex: /文件大小阈值（用于动态分块大小调整）/g, replacement: 'file size threshold (for dynamic chunk size adjustment)' },
    { regex: /方法字符串转换/g, replacement: 'method string conversion' },
    { regex: /日志级别/g, replacement: 'log level' },
    { regex: /日志错误码范围/g, replacement: 'log error code range' },
    { regex: /时间函数/g, replacement: 'time functions' },
    { regex: /时间单位转换/g, replacement: 'time unit conversion' },
    { regex: /时间相关常量/g, replacement: 'time-related constants' },
    { regex: /普通应用：16MB（default）/g, replacement: 'common applications: 16MB (default)' },
    { regex: /普通应用：64MB（default）/g, replacement: 'common applications: 64MB (default)' },
    { regex: /最大 header 数量/g, replacement: 'maximum header count' },
    { regex: /最大并发文件读取数/g, replacement: 'maximum concurrent file reads' },
    { regex: /最大文件大小/g, replacement: 'maximum file size' },
    { regex: /最大请求体大小/g, replacement: 'maximum request body size' },
    { regex: /服务器configurationdefault value/g, replacement: 'server configuration default values' },
    { regex: /服务器构建器结构体（统一API）/g, replacement: 'server builder structure (unified API)' },
    { regex: /服务器清理configuration/g, replacement: 'server cleanup configuration' },
    { regex: /服务器运行和清理/g, replacement: 'server running and cleanup' },
    { regex: /服务器错误码范围/g, replacement: 'server error code range' },
    
    // More translations
    { regex: /本文件集中了所有可configuration的常量，按功能模块分类。/g, replacement: 'this file centralizes all configurable constants, organized by functional module.' },
    { regex: /本文件集中管理所有可configuration的default value，便于统一管理和修改/g, replacement: 'this file centrally manages all configurable default values for unified management and modification' },
    { regex: /构建帧/g, replacement: 'build frame' },
    { regex: /查找缓存条目/g, replacement: 'find cache entry' },
    { regex: /核心API：/g, replacement: 'core API:' },
    { regex: /核心 API 函数/g, replacement: 'core API functions' },
    { regex: /核心模块/g, replacement: 'core modules' },
    { regex: /根据file extension获取MIME type/g, replacement: 'get MIME type based on file extension' },
    { regex: /根据文件大小自动选择optimal策略：/g, replacement: 'automatically select optimal strategy based on file size:' },
    { regex: /检查file path是否安全（防止路径遍历攻击）/g, replacement: 'check if file path is safe (prevent path traversal attacks)' },
    { regex: /检查条件请求（If-None-Match, If-Modified-Since）/g, replacement: 'check conditional requests (If-None-Match, If-Modified-Since)' },
    { regex: /检查缓存条目是否过期/g, replacement: 'check if cache entry has expired' },
    { regex: /每个连接的maximum requests/g, replacement: 'maximum requests per connection' },
    { regex: /注意：/g, replacement: 'note:' },
    { regex: /注意事项/g, replacement: 'important notes' },
    { regex: /输入验证函数已移动到 uvhttp_validation\.h/g, replacement: 'input validation functions have been moved to uvhttp_validation.h' },
    { regex: /这些常量已移至 uvhttp_constants\.h 中定义/g, replacement: 'these constants have been moved to uvhttp_constants.h' },
    { regex: /验证函数已移动到 uvhttp_validation\.h/g, replacement: 'validation functions have been moved to uvhttp_validation.h' },
    { regex: /测试环境：1000条缓存，持续写入新条目/g, replacement: 'test environment: 1000 cache entries, continuously write new entries' },
    { regex: /测试环境：Linux 6\.14\.11, wrk 4线程\/100并发/g, replacement: 'test environment: Linux 6.14.11, wrk 4 threads/100 concurrent' },
    { regex: /测试环境：模拟网络抖动场景（丢包率 1%）/g, replacement: 'test environment: simulate network jitter scenario (packet loss rate 1%)' },
    { regex: /测试环境：模拟限流触发场景/g, replacement: 'test environment: simulate rate limit trigger scenario' },
    { regex: /添加 header（内部使用，自动扩容）/g, replacement: 'add header (internal use, auto-expand)' },
    { regex: /添加或更新缓存条目/g, replacement: 'add or update cache entry' },
    { regex: /清理文件缓存/g, replacement: 'clean file cache' },
    { regex: /清理过期条目/g, replacement: 'clean expired entries' },
    { regex: /清理过期缓存条目/g, replacement: 'clean expired cache entries' },
    { regex: /清空所有缓存/g, replacement: 'clear all cache' },
    { regex: /版本信息/g, replacement: 'version information' },
    { regex: /状态管理/g, replacement: 'state management' },
    { regex: /生成ETag value/g, replacement: 'generate ETag value' },
    { regex: /生成 Sec-WebSocket-Accept/g, replacement: 'generate Sec-WebSocket-Accept' },
    { regex: /由应用层实现，用于统计和记录连接超时事件/g, replacement: 'implemented by application layer, for statistics and logging connection timeout events' },
    { regex: /示例：cmake -DUVHTTP_ASYNC_FILE_MAX_CONCURRENT=128 \.\./g, replacement: 'example: cmake -DUVHTTP_ASYNC_FILE_MAX_CONCURRENT=128 ..' },
    { regex: /示例：cmake -DUVHTTP_ASYNC_FILE_MAX_SIZE=104857600 \.\./g, replacement: 'example: cmake -DUVHTTP_ASYNC_FILE_MAX_SIZE=104857600 ..' },
    { regex: /示例：cmake -DUVHTTP_BACKLOG=4096 \.\./g, replacement: 'example: cmake -DUVHTTP_BACKLOG=4096 ..' },
    { regex: /示例：cmake -DUVHTTP_CACHE_DEFAULT_TTL=7200 \.\./g, replacement: 'example: cmake -DUVHTTP_CACHE_DEFAULT_TTL=7200 ..' },
    { regex: /示例：cmake -DUVHTTP_CHUNK_SIZE_MEDIUM=524288 \.\./g, replacement: 'example: cmake -DUVHTTP_CHUNK_SIZE_MEDIUM=524288 ..' },
    { regex: /示例：cmake -DUVHTTP_CLIENT_IP_BUFFER_SIZE=128 \.\./g, replacement: 'example: cmake -DUVHTTP_CLIENT_IP_BUFFER_SIZE=128 ..' },
    { regex: /示例：cmake -DUVHTTP_FILE_SIZE_MEDIUM=20971520 \.\./g, replacement: 'example: cmake -DUVHTTP_FILE_SIZE_MEDIUM=20971520 ..' },
    { regex: /示例：cmake -DUVHTTP_INITIAL_BUFFER_SIZE=16384 \.\./g, replacement: 'example: cmake -DUVHTTP_INITIAL_BUFFER_SIZE=16384 ..' },
    { regex: /示例：cmake -DUVHTTP_INLINE_HEADERS_CAPACITY=64 \.\./g, replacement: 'example: cmake -DUVHTTP_INLINE_HEADERS_CAPACITY=64 ..' },
    { regex: /示例：cmake -DUVHTTP_IP_OCTET_MAX_VALUE=255 \.\./g, replacement: 'example: cmake -DUVHTTP_IP_OCTET_MAX_VALUE=255 ..' },
    { regex: /示例：cmake -DUVHTTP_LRU_CACHE_BATCH_EVICTION_SIZE=20 \.\./g, replacement: 'example: cmake -DUVHTTP_LRU_CACHE_BATCH_EVICTION_SIZE=20 ..' },
    
    // More translations
    { regex: /示例：cmake -DUVHTTP_MAX_BODY_SIZE=10485760 \.\./g, replacement: 'example: cmake -DUVHTTP_MAX_BODY_SIZE=10485760 ..' },
    { regex: /示例：cmake -DUVHTTP_MAX_CONNECTIONS_DEFAULT=4096 \.\./g, replacement: 'example: cmake -DUVHTTP_MAX_CONNECTIONS_DEFAULT=4096 ..' },
    { regex: /示例：cmake -DUVHTTP_MAX_HEADER_NAME_SIZE=512 \.\./g, replacement: 'example: cmake -DUVHTTP_MAX_HEADER_NAME_SIZE=512 ..' },
    { regex: /示例：cmake -DUVHTTP_MAX_HEADERS=128 \.\./g, replacement: 'example: cmake -DUVHTTP_MAX_HEADERS=128 ..' },
    { regex: /示例：cmake -DUVHTTP_MAX_ROUTE_PATH_LEN=512 \.\./g, replacement: 'example: cmake -DUVHTTP_MAX_ROUTE_PATH_LEN=512 ..' },
    { regex: /示例：cmake -DUVHTTP_MAX_URL_SIZE=4096 \.\./g, replacement: 'example: cmake -DUVHTTP_MAX_URL_SIZE=4096 ..' },
    { regex: /示例：cmake -DUVHTTP_PAGE_SIZE=8192 \.\./g, replacement: 'example: cmake -DUVHTTP_PAGE_SIZE=8192 ..' },
    { regex: /示例：cmake -DUVHTTP_RATE_LIMIT_MAX_REQUESTS=500000 \.\./g, replacement: 'example: cmake -DUVHTTP_RATE_LIMIT_MAX_REQUESTS=500000 ..' },
    { regex: /示例：cmake -DUVHTTP_READ_BUFFER_SIZE=32768 \.\./g, replacement: 'example: cmake -DUVHTTP_READ_BUFFER_SIZE=32768 ..' },
    { regex: /示例：cmake -DUVHTTP_SENDFILE_CHUNK_SIZE=524288 \.\./g, replacement: 'example: cmake -DUVHTTP_SENDFILE_CHUNK_SIZE=524288 ..' },
    { regex: /示例：cmake -DUVHTTP_SENDFILE_TIMEOUT_MS=60000 \.\./g, replacement: 'example: cmake -DUVHTTP_SENDFILE_TIMEOUT_MS=60000 ..' },
    { regex: /示例：cmake -DUVHTTP_SOCKET_SEND_BUF_SIZE=524288 \.\./g, replacement: 'example: cmake -DUVHTTP_SOCKET_SEND_BUF_SIZE=524288 ..' },
    { regex: /示例：cmake -DUVHTTP_STATIC_MAX_CACHE_SIZE=2097152 \.\./g, replacement: 'example: cmake -DUVHTTP_STATIC_MAX_CACHE_SIZE=2097152 ..' },
    { regex: /示例：cmake -DUVHTTP_STATIC_SMALL_FILE_THRESHOLD=8192 \.\./g, replacement: 'example: cmake -DUVHTTP_STATIC_SMALL_FILE_THRESHOLD=8192 ..' },
    { regex: /示例：cmake -DUVHTTP_TCP_KEEPALIVE_TIMEOUT=120 \.\./g, replacement: 'example: cmake -DUVHTTP_TCP_KEEPALIVE_TIMEOUT=120 ..' },
    { regex: /移动条目到LRU list head部/g, replacement: 'move entry to LRU list head' },
    { regex: /简化configurationAPI/g, replacement: 'simplified configuration API' },
    { regex: /简单的日志输出，仅在 Debug mode下enabled/g, replacement: 'simple log output, only enabled in Debug mode' },
    { regex: /简洁清晰：避免链表、优先级等复杂概念/g, replacement: 'simple and clear: avoid complex concepts like linked lists, priorities' },
    { regex: /类型定义/g, replacement: 'type definitions' },
    { regex: /系统分配器mode - 使用内联函数确保可以用作函数指针/g, replacement: 'system allocator mode - use inline functions to ensure they can be used as function pointers' },
    { regex: /系统要求：/g, replacement: 'system requirements:' },
    { regex: /系统调优/g, replacement: 'system tuning' },
    { regex: /纯函数：构建HTTP响应数据，无副作用，易于测试/g, replacement: 'pure function: build HTTP response data, no side effects, easy to test' },
    { regex: /结论：10s超时在false positive rate和user experience之间取得最佳平衡/g, replacement: 'conclusion: 10s timeout achieves optimal balance between false positive rate and user experience' },
    { regex: /结论：10个条目的批量驱逐在命中率和延迟之间取得最佳平衡/g, replacement: 'conclusion: batch eviction of 10 entries achieves optimal balance between hit rate and latency' },
    { regex: /结论：2次重试在failure rate和延迟之间取得最佳平衡/g, replacement: 'conclusion: 2 retries achieves optimal balance between failure rate and latency' },
    { regex: /结论：30s平衡了性能和资源占用，适合大多数场景/g, replacement: 'conclusion: 30s balances performance and resource usage, suitable for most scenarios' },
    { regex: /统一API functions/g, replacement: 'unified API functions' },
    { regex: /统一响应处理函数/g, replacement: 'unified response handling functions' },
    { regex: /统一的返回类型别名，用于所有API functions/g, replacement: 'unified return type alias, used for all API functions' },
    { regex: /缓冲区和大小限制default value/g, replacement: 'buffer and size limit default values' },
    { regex: /缓冲区大小configuration（性能关键）/g, replacement: 'buffer size configuration (performance critical)' },
    { regex: /缓存相关常量/g, replacement: 'cache-related constants' },
    { regex: /缓存行2（64-127字节）：指针和计数器字段 - 次频繁访问/g, replacement: 'cache line 2 (64-127 bytes): pointer and counter fields - secondary frequent access' },
    { regex: /缓存行2（64-127字节）：核心指针字段 - 次频繁访问/g, replacement: 'cache line 2 (64-127 bytes): core pointer fields - secondary frequent access' },
    { regex: /缓存行2总计：约64字节（取决于 WebSocket 是否enabled）/g, replacement: 'cache line 2 total: about 64 bytes (depends on whether WebSocket is enabled)' },
    { regex: /缓存行2总计：约64字节（取决于 whether TLS is enabled）/g, replacement: 'cache line 2 total: about 64 bytes (depends on whether TLS is enabled)' },
    { regex: /缓存行3+（128\+字节）：Headers 数组/g, replacement: 'cache line 3+ (128+ bytes): Headers array' },
    { regex: /缓存行3总计：约64字节/g, replacement: 'cache line 3 total: about 64 bytes' },
    { regex: /缓存行3总计：约88-112字节/g, replacement: 'cache line 3 total: about 88-112 bytes' },
    { regex: /缓存行4（192-255字节）：HTTP 解析状态/g, replacement: 'cache line 4 (192-255 bytes): HTTP parsing state' },
    { regex: /缓存行4（192-255字节）：WebSocket 相关/g, replacement: 'cache line 4 (192-255 bytes): WebSocket related' },
    { regex: /缓存行5\+（256\+字节）：大块缓冲区/g, replacement: 'cache line 5+ (256+ bytes): large buffers' },
    
    // More translations
    { regex: /缓存行3\+（128\+字节）：Headers 数组/g, replacement: 'cache line 3+ (128+ bytes): Headers array' },
    { regex: /缓存行5-6（256-383字节）：限流功能/g, replacement: 'cache line 5-6 (256-383 bytes): rate limiting functionality' },
    { regex: /缓存行5总计：64字节/g, replacement: 'cache line 5 total: 64 bytes' },
    { regex: /缓存行偏移验证宏 - 确保字段在缓存行边界/g, replacement: 'cache line offset validation macros - ensure fields are on cache line boundaries' },
    { regex: /缓存行填充macro definitions/g, replacement: 'cache line padding macro definitions' },
    { regex: /缓存行填充宏 - 防止伪共享（False Sharing）/g, replacement: 'cache line padding macros - prevent false sharing' },
    { regex: /缓存行填充验证宏 - 确保结构体大小是缓存行的整数倍/g, replacement: 'cache line padding validation macros - ensure structure size is an integer multiple of cache line' },
    { regex: /缓存行大小（现代 CPU 通常是 64 bytes）/g, replacement: 'cache line size (modern CPUs are typically 64 bytes)' },
    { regex: /缓存行对齐宏 - 用于结构体字段对齐/g, replacement: 'cache line alignment macros - for structure field alignment' },
    { regex: /缓存预热：预加载指定的文件到缓存中/g, replacement: 'cache prewarming: preload specified files into cache' },
    { regex: /缓存预热：预加载目录中的所有文件/g, replacement: 'cache prewarming: preload all files in directory' },
    { regex: /编译期分配器选择/g, replacement: 'compile-time allocator selection' },
    { regex: /编译期选择分配器类型/g, replacement: 'select allocator type at compile time' },
    { regex: /网络configuration验证常量/g, replacement: 'network configuration validation constants' },
    { regex: /网络和连接configuration/g, replacement: 'network and connection configuration' },
    { regex: /网络相关常量/g, replacement: 'network-related constants' },
    { regex: /获取缓存命中率/g, replacement: 'get cache hit rate' },
    { regex: /解析帧头/g, replacement: 'parse frame header' },
    { regex: /计算缓存命中率/g, replacement: 'calculate cache hit rate' },
    { regex: /设置callback function/g, replacement: 'set callback function' },
    { regex: /设置 sendfile configuration参数/g, replacement: 'set sendfile configuration parameters' },
    { regex: /设置静态文件相关的响应头/g, replacement: 'set static file related response headers' },
    { regex: /设计原则：/g, replacement: 'design principles:' },
    { regex: /证书吊销检查/g, replacement: 'certificate revocation check' },
    
    // Final translations
    { regex: /application layer主导/g, replacement: 'application layer主导' },
    { regex: /\/\* 处理请求\.\.\. \*\//g, replacement: '// process request...' },
    { regex: /internal functions（由 uvhttp_connection 调用）/g, replacement: 'internal functions (called by uvhttp_connection)' },
    { regex: /internal functions声明/g, replacement: 'internal function declarations' },
    { regex: /optional features的条件包含/g, replacement: 'conditional includes for optional features' },
    { regex: /small applications configuration \(memory优先\):/g, replacement: 'small applications configuration (memory优先):' },
    { regex: /large applications configuration \(performance优先\):/g, replacement: 'large applications configuration (performance优先):' },
    { regex: /uvhttp_safe_free removed - completely unused，直接使用 uvhttp_free/g, replacement: 'uvhttp_safe_free removed - completely unused, use uvhttp_free directly' },
    { regex: /数组路由结构/g, replacement: 'array routing structure' },
    { regex: /fallback route support（8字节对齐）/g, replacement: 'fallback route support (8-byte aligned)' },
    
    // Final translations
    { regex: /application layer主导/g, replacement: 'application layer主导' },
    { regex: /12字节 - padding to 64 bytes/g, replacement: '12 bytes - padding to 64 bytes' },
    { regex: /中型应用（1000-10000 RPS）：increase connections and buffer size/g, replacement: 'medium applications (1000-10000 RPS): increase connections and buffer size' },
    { regex: /memory优先/g, replacement: 'memory优先' },
    { regex: /performance优先/g, replacement: 'performance优先' },
    { regex: /\/\* 秒 \*\//g, replacement: '/* seconds */' },
    { regex: /application layer主导/g, replacement: 'application layer主导' },
    { regex: /memory优先/g, replacement: 'memory优先' },
    { regex: /performance优先/g, replacement: 'performance优先' },
];

function convertComments(content) {
    let result = content;
    
    // Apply all patterns
    for (const { regex, replacement } of patterns) {
        result = result.replace(regex, replacement);
    }
    
    return result;
}

function processFile(filePath) {
    console.log(`Processing: ${filePath}`);
    
    const content = fs.readFileSync(filePath, 'utf8');
    const converted = convertComments(content);
    
    if (content !== converted) {
        fs.writeFileSync(filePath, converted, 'utf8');
        console.log(`  ✓ Updated`);
    } else {
        console.log(`  - No changes`);
    }
}

function main() {
    const includeDir = path.join(__dirname, '..', 'include');
    
    // Find all header files
    const files = fs.readdirSync(includeDir)
        .filter(file => file.endsWith('.h'))
        .map(file => path.join(includeDir, file));
    
    console.log(`Found ${files.length} header files\n`);
    
    for (const file of files) {
        processFile(file);
    }
    
    console.log('\n✅ All files processed');
}

main();