const fs = require('fs');
const path = require('path');

const srcDir = '/home/zhaodi-chen/project/uvhttp/src';
const includeDir = '/home/zhaodi-chen/project/uvhttp/include';

// Get all C and H files
const srcFiles = fs.readdirSync(srcDir).filter(f => f.endsWith('.c'));
const includeFiles = fs.readdirSync(includeDir).filter(f => f.endsWith('.h'));
const allFiles = [...srcFiles.map(f => path.join(srcDir, f)), ...includeFiles.map(f => path.join(includeDir, f))];

// Fix macro definitions that were incorrectly split
const macroPatterns = [
    { pattern: /UV HTTP_/g, replacement: 'UVHTTP_' },
    { pattern: /UV HTTP/g, replacement: 'UVHTTP' },
    { pattern: /UV HTTP/g, replacement: 'UVHTTP' },
    { pattern: /HTTP_ERROR_MAX/g, replacement: 'UVHTTP_ERROR_MAX' },
    { pattern: /HTTP_ALLO C ATOR_TYPE/g, replacement: 'UVHTTP_ALLOCATOR_TYPE' },
    { pattern: /HTTP_DEFAULT_/g, replacement: 'UVHTTP_DEFAULT_' },
    { pattern: /HTTP_MAX_/g, replacement: 'UVHTTP_MAX_' },
    { pattern: /HTTP_/g, replacement: 'UVHTTP_' },
    { pattern: /HTTP_C ONNE C TION S/g, replacement: 'UVHTTP_CONNECTIONS' },
    { pattern: /HTTP_C ONNE/g, replacement: 'UVHTTP_CONN' },
    { pattern: /HTTP_/g, replacement: 'UVHTTP_' },
    { pattern: /HTTP/g, replacement: 'HTTP' },  // Keep HTTP as is when it's the protocol name
    
    // Fix other common patterns
    { pattern: /mimallo c/g, replacement: 'mimalloc' },
    { pattern: /mimallo c/g, replacement: 'mimalloc' },
    { pattern: /dynami c ally/g, replacement: 'dynamically' },
    { pattern: /c al c ulated/g, replacement: 'calculated' },
    { pattern: /c onne c tion/g, replacement: 'connection' },
    { pattern: /request s/g, replacement: 'requests' },
    { pattern: /se c onds/g, replacement: 'seconds' },
    { pattern: /allo c ator/g, replacement: 'allocator' },
    { pattern: /maxi mum/g, replacement: 'maximum' },
    { pattern: /defau lt/g, replacement: 'default' },
    { pattern: /c he c k/g, replacement: 'check' },
    { pattern: /s et/g, replacement: 'set' },
    { pattern: /get/g, replacement: 'get' },
    { pattern: /add/g, replacement: 'add' },
    { pattern: /remove/g, replacement: 'remove' },
    { pattern: /find/g, replacement: 'find' },
    { pattern: /handle/g, replacement: 'handle' },
    { pattern: /handler/g, replacement: 'handler' },
    { pattern: /request/g, replacement: 'request' },
    { pattern: /response/g, replacement: 'response' },
    { pattern: /connection/g, replacement: 'connection' },
    { pattern: /server/g, replacement: 'server' },
    { pattern: /client/g, replacement: 'client' },
    { pattern: /buffer/g, replacement: 'buffer' },
    { pattern: /file/g, replacement: 'file' },
    { pattern: /path/g, replacement: 'path' },
    { pattern: /context/g, replacement: 'context' },
    { pattern: /state/g, replacement: 'state' },
    { pattern: /timeout/g, replacement: 'timeout' },
    { pattern: /timer/g, replacement: 'timer' },
    { pattern: /cache/g, replacement: 'cache' },
    { pattern: /router/g, replacement: 'router' },
    { pattern: /route/g, replacement: 'route' },
    { pattern: /header/g, replacement: 'header' },
    { pattern: /body/g, replacement: 'body' },
    { pattern: /size/g, replacement: 'size' },
    { pattern: /count/g, replacement: 'count' },
    { pattern: /entry/g, replacement: 'entry' },
    { pattern: /node/g, replacement: 'node' },
    { pattern: /list/g, replacement: 'list' },
    { pattern: /table/g, replacement: 'table' },
    { pattern: /hash/g, replacement: 'hash' },
    { pattern: /pool/g, replacement: 'pool' },
    { pattern: /pointer/g, replacement: 'pointer' },
    { pattern: /data/g, replacement: 'data' },
    { pattern: /memory/g, replacement: 'memory' },
    { pattern: /allocate/g, replacement: 'allocate' },
    { pattern: /callback/g, replacement: 'callback' },
    { pattern: /function/g, replacement: 'function' },
    { pattern: /parameter/g, replacement: 'parameter' },
    { pattern: /value/g, replacement: 'value' },
    { pattern: /limit/g, replacement: 'limit' },
    { pattern: /error/g, replacement: 'error' },
    { pattern: /validate/g, replacement: 'validate' },
    { pattern: /update/g, replacement: 'update' },
    { pattern: /cleanup/g, replacement: 'cleanup' },
    { pattern: /statistics/g, replacement: 'statistics' },
    { pattern: /information/g, replacement: 'information' },
    { pattern: /string/g, replacement: 'string' },
    { pattern: /character/g, replacement: 'character' },
    { pattern: /operation/g, replacement: 'operation' },
    { pattern: /mode/g, replacement: 'mode' },
    { pattern: /type/g, replacement: 'type' },
    { pattern: /option/g, replacement: 'option' },
    { pattern: /feature/g, replacement: 'feature' },
    { pattern: /module/g, replacement: 'module' },
    { pattern: /enabled/g, replacement: 'enabled' },
    { pattern: /disabled/g, replacement: 'disabled' },
    { pattern: /success/g, replacement: 'success' },
    { pattern: /failure/g, replacement: 'failure' },
    { pattern: /complete/g, replacement: 'complete' },
    { pattern: /match/g, replacement: 'match' },
    { pattern: /parse/g, replacement: 'parse' },
    { pattern: /send/g, replacement: 'send' },
    { pattern: /receive/g, replacement: 'receive' },
    { pattern: /read/g, replacement: 'read' },
    { pattern: /write/g, replacement: 'write' },
    { pattern: /close/g, replacement: 'close' },
    { pattern: /open/g, replacement: 'open' },
    { pattern: /start/g, replacement: 'start' },
    { pattern: /stop/g, replacement: 'stop' },
    { pattern: /enable/g, replacement: 'enable' },
    { pattern: /disable/g, replacement: 'disable' },
    { pattern: /reset/g, replacement: 'reset' },
    { pattern: /clear/g, replacement: 'clear' },
    { pattern: /copy/g, replacement: 'copy' },
    { pattern: /move/g, replacement: 'move' },
    { pattern: /build/g, replacement: 'build' },
    { pattern: /create/g, replacement: 'create' },
    { pattern: /destroy/g, replacement: 'destroy' },
    { pattern: /release/g, replacement: 'release' },
    { pattern: /acquire/g, replacement: 'acquire' },
    { pattern: /lock/g, replacement: 'lock' },
    { pattern: /unlock/g, replacement: 'unlock' },
    { pattern: /thread/g, replacement: 'thread' },
    { pattern: /process/g, replacement: 'process' },
    { pattern: /event/g, replacement: 'event' },
    { pattern: /loop/g, replacement: 'loop' },
    { pattern: /async/g, replacement: 'async' },
    { pattern: /sync/g, replacement: 'sync' },
    { pattern: /blocking/g, replacement: 'blocking' },
    { pattern: /non/g, replacement: 'non' },
    { pattern: /safe/g, replacement: 'safe' },
    { pattern: /unsafe/g, replacement: 'unsafe' },
    { pattern: /static/g, replacement: 'static' },
    { pattern: /dynamic/g, replacement: 'dynamic' },
    { pattern: /global/g, replacement: 'global' },
    { pattern: /local/g, replacement: 'local' },
    { pattern: /public/g, replacement: 'public' },
    { pattern: /private/g, replacement: 'private' },
    { pattern: /internal/g, replacement: 'internal' },
    { pattern: /external/g, replacement: 'external' },
    { pattern: /default/g, replacement: 'default' },
    { pattern: /custom/g, replacement: 'custom' },
    { pattern: /user/g, replacement: 'user' },
    { pattern: /system/g, replacement: 'system' },
    { pattern: /application/g, replacement: 'application' },
    { pattern: /framework/g, replacement: 'framework' },
    { pattern: /library/g, replacement: 'library' },
    { pattern: /protocol/g, replacement: 'protocol' },
    { pattern: /network/g, replacement: 'network' },
    { pattern: /socket/g, replacement: 'socket' },
    { pattern: /TCP/g, replacement: 'TCP' },
    { pattern: /HTTP/g, replacement: 'HTTP' },
    { pattern: /HTTPS/g, replacement: 'HTTPS' },
    { pattern: /WebSocket/g, replacement: 'WebSocket' },
    { pattern: /TLS/g, replacement: 'TLS' },
    { pattern: /SSL/g, replacement: 'SSL' },
    { pattern: /API/g, replacement: 'API' },
    { pattern: /URL/g, replacement: 'URL' },
    { pattern: /URI/g, replacement: 'URI' },
    { pattern: /IP/g, replacement: 'IP' },
    { pattern: /DNS/g, replacement: 'DNS' },
    { pattern: /JSON/g, replacement: 'JSON' },
    { pattern: /XML/g, replacement: 'XML' },
    { pattern: /HTML/g, replacement: 'HTML' },
    { pattern: /CSS/g, replacement: 'CSS' },
    { pattern: /JavaScript/g, replacement: 'JavaScript' },
    { pattern: /Python/g, replacement: 'Python' },
    { pattern: /C\+\+/g, replacement: 'C++' },
    { pattern: /Java/g, replacement: 'Java' },
    { pattern: /Go/g, replacement: 'Go' },
    { pattern: /Rust/g, replacement: 'Rust' },
    { pattern: /Node/g, replacement: 'Node' },
    { pattern: /Linux/g, replacement: 'Linux' },
    { pattern: /Windows/g, replacement: 'Windows' },
    { pattern: /macOS/g, replacement: 'macOS' },
    { pattern: /Unix/g, replacement: 'Unix' },
    { pattern: /POSIX/g, replacement: 'POSIX' },
    { pattern: /ANSI/g, replacement: 'ANSI' },
    { pattern: /ISO/g, replacement: 'ISO' },
    { pattern: /UTF/g, replacement: 'UTF' },
    { pattern: /ASCII/g, replacement: 'ASCII' },
    { pattern: /Unicode/g, replacement: 'Unicode' },
    { pattern: /Base64/g, replacement: 'Base64' },
    { pattern: /MD5/g, replacement: 'MD5' },
    { pattern: /SHA/g, replacement: 'SHA' },
    { pattern: /RSA/g, replacement: 'RSA' },
    { pattern: /AES/g, replacement: 'AES' },
    { pattern: /DES/g, replacement: 'DES' },
    { pattern: /HMAC/g, replacement: 'HMAC' },
    { pattern: /OAuth/g, replacement: 'OAuth' },
    { pattern: /JWT/g, replacement: 'JWT' },
    { pattern: /UUID/g, replacement: 'UUID' },
    { pattern: /GUID/g, replacement: 'GUID' },
    { pattern: /ID/g, replacement: 'ID' },
    { pattern: /OK/g, replacement: 'OK' },
    { pattern: /NULL/g, replacement: 'NULL' },
    { pattern: /EOF/g, replacement: 'EOF' },
    { pattern: /EOL/g, replacement: 'EOL' },
    { pattern: /CR/g, replacement: 'CR' },
    { pattern: /LF/g, replacement: 'LF' },
    { pattern: /CRLF/g, replacement: 'CRLF' }
];

let totalFixed = 0;

allFiles.forEach(filePath => {
    const content = fs.readFileSync(filePath, 'utf8');
    let result = content;

    macroPatterns.forEach(({pattern, replacement}) => {
        result = result.replace(pattern, replacement);
    });

    if (content !== result) {
        fs.writeFileSync(filePath, result, 'utf8');
        console.log('Fixed:', path.basename(filePath));
        totalFixed++;
    }
});

console.log('\nTotal files fixed:', totalFixed);
