const fs = require('fs');
const path = require('path');

const srcDir = '/home/zhaodi-chen/project/uvhttp/src';
const includeDir = '/home/zhaodi-chen/project/uvhttp/include';

// Get all C and H files
const srcFiles = fs.readdirSync(srcDir).filter(f => f.endsWith('.c'));
const includeFiles = fs.readdirSync(includeDir).filter(f => f.endsWith('.h'));
const allFiles = [...srcFiles.map(f => path.join(srcDir, f)), ...includeFiles.map(f => path.join(includeDir, f))];

// Common word boundaries that need spaces
const commonPatterns = [
    // Common concatenated words
    { pattern: /([a-z])([A-Z][a-z])/g, replacement: '$1 $2' },  // camelCase to separate words
    { pattern: /([a-z]+)(configuration)/gi, replacement: '$1 $2' },
    { pattern: /(configuration)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(management)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(system)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(implementation)/gi, replacement: '$1 $2' },
    { pattern: /(initialize)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(initialize)/gi, replacement: '$1 $2' },
    { pattern: /(create)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(create)/gi, replacement: '$1 $2' },
    { pattern: /(free)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(free)/gi, replacement: '$1 $2' },
    { pattern: /(set)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(set)/gi, replacement: '$1 $2' },
    { pattern: /(get)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(get)/gi, replacement: '$1 $2' },
    { pattern: /(add)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(add)/gi, replacement: '$1 $2' },
    { pattern: /(check)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(check)/gi, replacement: '$1 $2' },
    { pattern: /(remove)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(remove)/gi, replacement: '$1 $2' },
    { pattern: /(find)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(find)/gi, replacement: '$1 $2' },
    { pattern: /(handle)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(handle)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(handler)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(request)/gi, replacement: '$1 $2' },
    { pattern: /(request)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(response)/gi, replacement: '$1 $2' },
    { pattern: /(response)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(connection)/gi, replacement: '$1 $2' },
    { pattern: /(connection)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(server)/gi, replacement: '$1 $2' },
    { pattern: /(server)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(client)/gi, replacement: '$1 $2' },
    { pattern: /(client)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(buffer)/gi, replacement: '$1 $2' },
    { pattern: /(buffer)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(file)/gi, replacement: '$1 $2' },
    { pattern: /(file)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(path)/gi, replacement: '$1 $2' },
    { pattern: /(path)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(context)/gi, replacement: '$1 $2' },
    { pattern: /(context)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(state)/gi, replacement: '$1 $2' },
    { pattern: /(state)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(timeout)/gi, replacement: '$1 $2' },
    { pattern: /(timeout)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(timer)/gi, replacement: '$1 $2' },
    { pattern: /(timer)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(cache)/gi, replacement: '$1 $2' },
    { pattern: /(cache)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(router)/gi, replacement: '$1 $2' },
    { pattern: /(router)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(route)/gi, replacement: '$1 $2' },
    { pattern: /(route)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(header)/gi, replacement: '$1 $2' },
    { pattern: /(header)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(body)/gi, replacement: '$1 $2' },
    { pattern: /(body)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(size)/gi, replacement: '$1 $2' },
    { pattern: /(size)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(count)/gi, replacement: '$1 $2' },
    { pattern: /(count)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(entry)/gi, replacement: '$1 $2' },
    { pattern: /(entry)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(node)/gi, replacement: '$1 $2' },
    { pattern: /(node)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(list)/gi, replacement: '$1 $2' },
    { pattern: /(list)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(table)/gi, replacement: '$1 $2' },
    { pattern: /(table)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(hash)/gi, replacement: '$1 $2' },
    { pattern: /(hash)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(pool)/gi, replacement: '$1 $2' },
    { pattern: /(pool)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(pointer)/gi, replacement: '$1 $2' },
    { pattern: /(pointer)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(data)/gi, replacement: '$1 $2' },
    { pattern: /(data)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(memory)/gi, replacement: '$1 $2' },
    { pattern: /(memory)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(allocate)/gi, replacement: '$1 $2' },
    { pattern: /(allocate)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(callback)/gi, replacement: '$1 $2' },
    { pattern: /(callback)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(function)/gi, replacement: '$1 $2' },
    { pattern: /(function)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(parameter)/gi, replacement: '$1 $2' },
    { pattern: /(parameter)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(value)/gi, replacement: '$1 $2' },
    { pattern: /(value)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(limit)/gi, replacement: '$1 $2' },
    { pattern: /(limit)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(error)/gi, replacement: '$1 $2' },
    { pattern: /(error)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(validate)/gi, replacement: '$1 $2' },
    { pattern: /(validate)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(update)/gi, replacement: '$1 $2' },
    { pattern: /(update)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(cleanup)/gi, replacement: '$1 $2' },
    { pattern: /(cleanup)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(statistics)/gi, replacement: '$1 $2' },
    { pattern: /(statistics)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(information)/gi, replacement: '$1 $2' },
    { pattern: /(information)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(string)/gi, replacement: '$1 $2' },
    { pattern: /(string)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(character)/gi, replacement: '$1 $2' },
    { pattern: /(character)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(operation)/gi, replacement: '$1 $2' },
    { pattern: /(operation)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(mode)/gi, replacement: '$1 $2' },
    { pattern: /(mode)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(type)/gi, replacement: '$1 $2' },
    { pattern: /(type)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(option)/gi, replacement: '$1 $2' },
    { pattern: /(option)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(feature)/gi, replacement: '$1 $2' },
    { pattern: /(feature)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(module)/gi, replacement: '$1 $2' },
    { pattern: /(module)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(enabled)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(disabled)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(success)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(failure)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(complete)/gi, replacement: '$1 $2' },
    { pattern: /(complete)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(match)/gi, replacement: '$1 $2' },
    { pattern: /(match)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(parse)/gi, replacement: '$1 $2' },
    { pattern: /(parse)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(send)/gi, replacement: '$1 $2' },
    { pattern: /(send)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(receive)/gi, replacement: '$1 $2' },
    { pattern: /(receive)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(read)/gi, replacement: '$1 $2' },
    { pattern: /(read)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(write)/gi, replacement: '$1 $2' },
    { pattern: /(write)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(close)/gi, replacement: '$1 $2' },
    { pattern: /(close)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(open)/gi, replacement: '$1 $2' },
    { pattern: /(open)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(start)/gi, replacement: '$1 $2' },
    { pattern: /(start)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(stop)/gi, replacement: '$1 $2' },
    { pattern: /(stop)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(enable)/gi, replacement: '$1 $2' },
    { pattern: /(enable)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(disable)/gi, replacement: '$1 $2' },
    { pattern: /(disable)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(reset)/gi, replacement: '$1 $2' },
    { pattern: /(reset)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(clear)/gi, replacement: '$1 $2' },
    { pattern: /(clear)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(copy)/gi, replacement: '$1 $2' },
    { pattern: /(copy)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(move)/gi, replacement: '$1 $2' },
    { pattern: /(move)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(build)/gi, replacement: '$1 $2' },
    { pattern: /(build)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(create)/gi, replacement: '$1 $2' },
    { pattern: /(create)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(destroy)/gi, replacement: '$1 $2' },
    { pattern: /(destroy)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(release)/gi, replacement: '$1 $2' },
    { pattern: /(release)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(acquire)/gi, replacement: '$1 $2' },
    { pattern: /(acquire)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(lock)/gi, replacement: '$1 $2' },
    { pattern: /(lock)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(unlock)/gi, replacement: '$1 $2' },
    { pattern: /(unlock)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(thread)/gi, replacement: '$1 $2' },
    { pattern: /(thread)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(process)/gi, replacement: '$1 $2' },
    { pattern: /(process)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(event)/gi, replacement: '$1 $2' },
    { pattern: /(event)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(loop)/gi, replacement: '$1 $2' },
    { pattern: /(loop)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(async)/gi, replacement: '$1 $2' },
    { pattern: /(async)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(sync)/gi, replacement: '$1 $2' },
    { pattern: /(sync)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(blocking)/gi, replacement: '$1 $2' },
    { pattern: /(blocking)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(non)/gi, replacement: '$1 $2' },
    { pattern: /(non)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(safe)/gi, replacement: '$1 $2' },
    { pattern: /(safe)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(unsafe)/gi, replacement: '$1 $2' },
    { pattern: /(unsafe)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(static)/gi, replacement: '$1 $2' },
    { pattern: /(static)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(dynamic)/gi, replacement: '$1 $2' },
    { pattern: /(dynamic)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(global)/gi, replacement: '$1 $2' },
    { pattern: /(global)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(local)/gi, replacement: '$1 $2' },
    { pattern: /(local)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(public)/gi, replacement: '$1 $2' },
    { pattern: /(public)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(private)/gi, replacement: '$1 $2' },
    { pattern: /(private)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(internal)/gi, replacement: '$1 $2' },
    { pattern: /(internal)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(external)/gi, replacement: '$1 $2' },
    { pattern: /(external)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(default)/gi, replacement: '$1 $2' },
    { pattern: /(default)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(custom)/gi, replacement: '$1 $2' },
    { pattern: /(custom)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(user)/gi, replacement: '$1 $2' },
    { pattern: /(user)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(system)/gi, replacement: '$1 $2' },
    { pattern: /(system)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(application)/gi, replacement: '$1 $2' },
    { pattern: /(application)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(framework)/gi, replacement: '$1 $2' },
    { pattern: /(framework)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(library)/gi, replacement: '$1 $2' },
    { pattern: /(library)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(protocol)/gi, replacement: '$1 $2' },
    { pattern: /(protocol)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(network)/gi, replacement: '$1 $2' },
    { pattern: /(network)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(socket)/gi, replacement: '$1 $2' },
    { pattern: /(socket)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(TCP)/gi, replacement: '$1 $2' },
    { pattern: /(TCP)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(HTTP)/gi, replacement: '$1 $2' },
    { pattern: /(HTTP)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(HTTPS)/gi, replacement: '$1 $2' },
    { pattern: /(HTTPS)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(WebSocket)/gi, replacement: '$1 $2' },
    { pattern: /(WebSocket)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(TLS)/gi, replacement: '$1 $2' },
    { pattern: /(TLS)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(SSL)/gi, replacement: '$1 $2' },
    { pattern: /(SSL)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(API)/gi, replacement: '$1 $2' },
    { pattern: /(API)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(URL)/gi, replacement: '$1 $2' },
    { pattern: /(URL)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(URI)/gi, replacement: '$1 $2' },
    { pattern: /(URI)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(IP)/gi, replacement: '$1 $2' },
    { pattern: /(IP)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(DNS)/gi, replacement: '$1 $2' },
    { pattern: /(DNS)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(JSON)/gi, replacement: '$1 $2' },
    { pattern: /(JSON)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(XML)/gi, replacement: '$1 $2' },
    { pattern: /(XML)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(HTML)/gi, replacement: '$1 $2' },
    { pattern: /(HTML)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(CSS)/gi, replacement: '$1 $2' },
    { pattern: /(CSS)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(JavaScript)/gi, replacement: '$1 $2' },
    { pattern: /(JavaScript)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(Python)/gi, replacement: '$1 $2' },
    { pattern: /(Python)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(C)/gi, replacement: '$1 $2' },
    { pattern: /(C)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(C\+\+)/gi, replacement: '$1 $2' },
    { pattern: /(C\+\+)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(Java)/gi, replacement: '$1 $2' },
    { pattern: /(Java)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(Go)/gi, replacement: '$1 $2' },
    { pattern: /(Go)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(Rust)/gi, replacement: '$1 $2' },
    { pattern: /(Rust)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(Node)/gi, replacement: '$1 $2' },
    { pattern: /(Node)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(Linux)/gi, replacement: '$1 $2' },
    { pattern: /(Linux)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(Windows)/gi, replacement: '$1 $2' },
    { pattern: /(Windows)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(macOS)/gi, replacement: '$1 $2' },
    { pattern: /(macOS)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(Unix)/gi, replacement: '$1 $2' },
    { pattern: /(Unix)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(POSIX)/gi, replacement: '$1 $2' },
    { pattern: /(POSIX)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(ANSI)/gi, replacement: '$1 $2' },
    { pattern: /(ANSI)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(ISO)/gi, replacement: '$1 $2' },
    { pattern: /(ISO)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(UTF)/gi, replacement: '$1 $2' },
    { pattern: /(UTF)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(ASCII)/gi, replacement: '$1 $2' },
    { pattern: /(ASCII)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(Unicode)/gi, replacement: '$1 $2' },
    { pattern: /(Unicode)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(Base64)/gi, replacement: '$1 $2' },
    { pattern: /(Base64)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(MD5)/gi, replacement: '$1 $2' },
    { pattern: /(MD5)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(SHA)/gi, replacement: '$1 $2' },
    { pattern: /(SHA)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(RSA)/gi, replacement: '$1 $2' },
    { pattern: /(RSA)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(AES)/gi, replacement: '$1 $2' },
    { pattern: /(AES)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(DES)/gi, replacement: '$1 $2' },
    { pattern: /(DES)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(HMAC)/gi, replacement: '$1 $2' },
    { pattern: /(HMAC)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(OAuth)/gi, replacement: '$1 $2' },
    { pattern: /(OAuth)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(JWT)/gi, replacement: '$1 $2' },
    { pattern: /(JWT)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(UUID)/gi, replacement: '$1 $2' },
    { pattern: /(UUID)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(GUID)/gi, replacement: '$1 $2' },
    { pattern: /(GUID)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(ID)/gi, replacement: '$1 $2' },
    { pattern: /(ID)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(OK)/gi, replacement: '$1 $2' },
    { pattern: /(OK)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(NULL)/gi, replacement: '$1 $2' },
    { pattern: /(NULL)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(EOF)/gi, replacement: '$1 $2' },
    { pattern: /(EOF)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(EOL)/gi, replacement: '$1 $2' },
    { pattern: /(EOL)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(CR)/gi, replacement: '$1 $2' },
    { pattern: /(CR)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(LF)/gi, replacement: '$1 $2' },
    { pattern: /(LF)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(CRLF)/gi, replacement: '$1 $2' },
    { pattern: /(CRLF)([a-z]+)/gi, replacement: '$1 $2' },
    { pattern: /([a-z]+)(HTTP)/gi, replacement: '$1 $2' },
    { pattern: /(HTTP)([a-z]+)/gi, replacement: '$1 $2' },
    
    // Chinese punctuation to English
    { pattern: /，/g, replacement: ',' },
    { pattern: /。/g, replacement: '.' },
    { pattern: /：/g, replacement: ':' },
    { pattern: /；/g, replacement: ';' },
    { pattern: /（/g, replacement: '(' },
    { pattern: /）/g, replacement: ')' },
    { pattern: /【/g, replacement: '[' },
    { pattern: /】/g, replacement: ']' },
    { pattern: /《/g, replacement: '<' },
    { pattern: /》/g, replacement: '>' },
    { pattern: /"/g, replacement: '"' },
    { pattern: /"/g, replacement: '"' },
    { pattern: /'/g, replacement: "'" },
    { pattern: /'/g, replacement: "'" },
    
    // Multiple spaces to single space (but not in code)
    { pattern: /  +/g, replacement: ' ' },
    
    // Space before punctuation
    { pattern: /\s+([,.:;])/g, replacement: '$1' },
    
    // Space after opening parenthesis
    { pattern: /\(\s+/g, replacement: '(' },
    
    // Space before closing parenthesis
    { pattern: /\s+\)/g, replacement: ')' }
];

let totalFixed = 0;

allFiles.forEach(filePath => {
    const content = fs.readFileSync(filePath, 'utf8');
    let result = content;

    // Only process within comments (/* */ and //)
    const lines = result.split('\n');
    const processedLines = lines.map(line => {
        // Check if line contains a comment
        if (line.includes('/*') || line.includes('//')) {
            let processedLine = line;
            
            // Apply patterns only to comment parts
            commonPatterns.forEach(({pattern, replacement}) => {
                processedLine = processedLine.replace(pattern, replacement);
            });
            
            return processedLine;
        }
        return line;
    });

    result = processedLines.join('\n');

    if (content !== result) {
        fs.writeFileSync(filePath, result, 'utf8');
        console.log('Fixed:', path.basename(filePath));
        totalFixed++;
    }
});

console.log('\nTotal files fixed:', totalFixed);