const fs = require('fs');
const path = require('path');

const srcDir = '/home/zhaodi-chen/project/uvhttp/src';
const includeDir = '/home/zhaodi-chen/project/uvhttp/include';

// Get all C and H files
const srcFiles = fs.readdirSync(srcDir).filter(f => f.endsWith('.c'));
const includeFiles = fs.readdirSync(includeDir).filter(f => f.endsWith('.h'));
const allFiles = [...srcFiles.map(f => path.join(srcDir, f)), ...includeFiles.map(f => path.join(includeDir, f))];

// Comprehensive translation dictionary organized by category
const translations = {
    // Common phrases
    common: {
        '默认': 'default',
        '最大': 'maximum',
        '最小': 'minimum',
        '配置': 'configuration',
        '初始化': 'initialize',
        '释放': 'release',
        '创建': 'create',
        '删除': 'delete',
        '添加': 'add',
        '移除': 'remove',
        '获取': 'get',
        '设置': 'set',
        '检查': 'check',
        '验证': 'validate',
        '更新': 'update',
        '处理': 'handle',
        '返回': 'return',
        '参数': 'parameter',
        '值': 'value',
        '错误': 'error',
        '成功': 'success',
        '失败': 'failure',
        '警告': 'warning',
        '注意': 'note',
        '建议': 'recommendation',
        '示例': 'example',
        '包含': 'include',
        '支持': 'support',
        '禁用': 'disable',
        '启用': 'enable',
        '可选': 'optional',
        '必需': 'required',
        '建议': 'suggested',
        '推荐': 'recommended',
        '基于': 'based on',
        '用于': 'used for',
        '适用于': 'applicable to',
        '如果': 'if',
        '否则': 'else',
        '当': 'when',
        '然后': 'then',
        '之后': 'after',
        '之前': 'before',
        '同时': 'simultaneously',
        '另外': 'additionally',
        '此外': 'furthermore',
        '因此': 'therefore',
        '所以': 'so',
        '但是': 'however',
        '虽然': 'although',
        '因为': 'because',
        '由于': 'due to',
        '通过': 'through',
        '使用': 'use',
        '利用': 'utilize',
        '采用': 'adopt',
        '实现': 'implement',
        '执行': 'execute',
        '运行': 'run',
        '启动': 'start',
        '停止': 'stop',
        '关闭': 'close',
        '打开': 'open',
        '读取': 'read',
        '写入': 'write',
        '发送': 'send',
        '接收': 'receive',
        '连接': 'connect',
        '断开': 'disconnect',
        '请求': 'request',
        '响应': 'response',
        '服务器': 'server',
        '客户端': 'client',
        '网络': 'network',
        '协议': 'protocol',
        '接口': 'interface',
        'API': 'API',
        '函数': 'function',
        '方法': 'method',
        '变量': 'variable',
        '常量': 'constant',
        '类型': 'type',
        '结构': 'structure',
        '对象': 'object',
        '指针': 'pointer',
        '缓冲区': 'buffer',
        '内存': 'memory',
        '线程': 'thread',
        '进程': 'process',
        '事件': 'event',
        '循环': 'loop',
        '回调': 'callback',
        '处理': 'handler',
        '管理器': 'manager',
        '上下文': 'context',
        '状态': 'state',
        '模式': 'mode',
        '选项': 'option',
        '特性': 'feature',
        '模块': 'module',
        '组件': 'component',
        '系统': 'system',
        '应用程序': 'application',
        '框架': 'framework',
        '库': 'library',
        '工具': 'tool',
        '脚本': 'script',
        '文档': 'documentation',
        '注释': 'comment',
        '代码': 'code',
        '测试': 'test',
        '调试': 'debug',
        '日志': 'log',
        '错误处理': 'error handling',
        '资源管理': 'resource management',
        '内存管理': 'memory management',
        '连接管理': 'connection management',
        '线程安全': 'thread safety',
        '性能优化': 'performance optimization',
        '安全': 'security',
        '稳定性': 'stability'
    },
    
    // Technical terms
    technical: {
        '事件循环': 'event loop',
        '单线程': 'single-threaded',
        '多线程': 'multi-threaded',
        '异步': 'asynchronous',
        '同步': 'synchronous',
        '阻塞': 'blocking',
        '非阻塞': 'non-blocking',
        '并发': 'concurrent',
        '串行': 'serial',
        '并发数': 'concurrency',
        '吞吐量': 'throughput',
        '延迟': 'latency',
        '超时': 'timeout',
        '重试': 'retry',
        '缓冲': 'buffering',
        '缓存': 'cache',
        '路由': 'routing',
        '路由器': 'router',
        '中间件': 'middleware',
        '处理器': 'handler',
        '拦截器': 'interceptor',
        '过滤器': 'filter',
        '验证器': 'validator',
        '解析器': 'parser',
        '生成器': 'generator',
        '序列化': 'serialization',
        '反序列化': 'deserialization',
        '编码': 'encoding',
        '解码': 'decoding',
        '加密': 'encryption',
        '解密': 'decryption',
        '签名': 'signature',
        '验证': 'verification',
        '认证': 'authentication',
        '授权': 'authorization',
        '权限': 'permission',
        '角色': 'role',
        '用户': 'user',
        '会话': 'session',
        '令牌': 'token',
        '密钥': 'key',
        '证书': 'certificate',
        '握手': 'handshake',
        '连接池': 'connection pool',
        '线程池': 'thread pool',
        '对象池': 'object pool',
        '内存池': 'memory pool',
        '文件描述符': 'file descriptor',
        '套接字': 'socket',
        '端口': 'port',
        '主机': 'host',
        '地址': 'address',
        'URL': 'URL',
        'URI': 'URI',
        '路径': 'path',
        '查询参数': 'query parameter',
        '请求体': 'request body',
        '响应体': 'response body',
        '请求头': 'request header',
        '响应头': 'response header',
        '状态码': 'status code',
        '内容类型': 'content type',
        '内容长度': 'content length',
        '编码': 'encoding',
        '压缩': 'compression',
        '分块传输': 'chunked transfer',
        '长连接': 'keep-alive',
        '短连接': 'short connection',
        'WebSocket': 'WebSocket',
        'HTTP': 'HTTP',
        'HTTPS': 'HTTPS',
        'TCP': 'TCP',
        'TLS': 'TLS',
        'SSL': 'SSL',
        'IPv4': 'IPv4',
        'IPv6': 'IPv6',
        'DNS': 'DNS',
        'JSON': 'JSON',
        'XML': 'XML',
        'HTML': 'HTML',
        'CSS': 'CSS',
        'JavaScript': 'JavaScript',
        'Python': 'Python',
        'C语言': 'C language',
        'C++': 'C++',
        'Java': 'Java',
        'Go': 'Go',
        'Rust': 'Rust',
        'Node.js': 'Node.js',
        'Linux': 'Linux',
        'Windows': 'Windows',
        'macOS': 'macOS',
        'Unix': 'Unix',
        'POSIX': 'POSIX',
        'ANSI': 'ANSI',
        'ISO': 'ISO',
        'UTF-8': 'UTF-8',
        'ASCII': 'ASCII',
        'Unicode': 'Unicode',
        'Base64': 'Base64',
        'MD5': 'MD5',
        'SHA': 'SHA',
        'RSA': 'RSA',
        'AES': 'AES',
        'DES': 'DES',
        'HMAC': 'HMAC',
        'OAuth': 'OAuth',
        'JWT': 'JWT',
        'UUID': 'UUID',
        'GUID': 'GUID',
        'NULL': 'NULL',
        'EOF': 'EOF',
        'EOL': 'EOL',
        'CR': 'CR',
        'LF': 'LF',
        'CRLF': 'CRLF',
        'RPS': 'RPS',
        'QPS': 'QPS',
        'TPS': 'TPS',
        'DoS': 'DoS',
        'DDoS': 'DDoS',
        'XSS': 'XSS',
        'CSRF': 'CSRF',
        'SQL注入': 'SQL injection',
        '路径遍历': 'path traversal',
        '缓冲区溢出': 'buffer overflow',
        '内存泄漏': 'memory leak',
        '空指针': 'null pointer',
        '野指针': 'dangling pointer',
        '竞态条件': 'race condition',
        '死锁': 'deadlock',
        '活锁': 'livelock',
        '饥饿': 'starvation',
        '优先级': 'priority',
        '队列': 'queue',
        '栈': 'stack',
        '堆': 'heap',
        '树': 'tree',
        '图': 'graph',
        '哈希表': 'hash table',
        '链表': 'linked list',
        '数组': 'array',
        '向量': 'vector',
        '列表': 'list',
        '集合': 'set',
        '映射': 'map',
        '字典': 'dictionary'
    },
    
    // Action verbs
    actions: {
        '初始化': 'initialize',
        '初始化': 'initialize',
        '分配': 'allocate',
        '释放': 'free',
        '释放': 'release',
        '创建': 'create',
        '创建': 'create',
        '销毁': 'destroy',
        '销毁': 'destroy',
        '构建': 'build',
        '构建': 'build',
        '编译': 'compile',
        '编译': 'compile',
        '链接': 'link',
        '链接': 'link',
        '加载': 'load',
        '加载': 'load',
        '卸载': 'unload',
        '卸载': 'unload',
        '安装': 'install',
        '安装': 'install',
        '卸载': 'uninstall',
        '卸载': 'uninstall',
        '配置': 'configure',
        '配置': 'configure',
        '设置': 'set up',
        '设置': 'set up',
        '启动': 'start',
        '启动': 'start',
        '停止': 'stop',
        '停止': 'stop',
        '暂停': 'pause',
        '暂停': 'pause',
        '恢复': 'resume',
        '恢复': 'resume',
        '重启': 'restart',
        '重启': 'restart',
        '重载': 'reload',
        '重载': 'reload',
        '刷新': 'refresh',
        '刷新': 'refresh',
        '更新': 'update',
        '更新': 'update',
        '升级': 'upgrade',
        '升级': 'upgrade',
        '降级': 'downgrade',
        '降级': 'downgrade',
        '迁移': 'migrate',
        '迁移': 'migrate',
        '转换': 'convert',
        '转换': 'convert',
        '转换': 'transform',
        '转换': 'transform',
        '序列化': 'serialize',
        '序列化': 'serialize',
        '反序列化': 'deserialize',
        '反序列化': 'deserialize',
        '编码': 'encode',
        '编码': 'encode',
        '解码': 'decode',
        '解码': 'decode',
        '加密': 'encrypt',
        '加密': 'encrypt',
        '解密': 'decrypt',
        '解密': 'decrypt',
        '签名': 'sign',
        '签名': 'sign',
        '验证': 'verify',
        '验证': 'verify',
        '校验': 'checksum',
        '校验': 'checksum',
        '哈希': 'hash',
        '哈希': 'hash',
        '压缩': 'compress',
        '压缩': 'compress',
        '解压': 'decompress',
        '解压': 'decompress',
        '打包': 'package',
        '打包': 'package',
        '解包': 'unpack',
        '解包': 'unpack',
        '解析': 'parse',
        '解析': 'parse',
        '格式化': 'format',
        '格式化': 'format',
        '渲染': 'render',
        '渲染': 'render',
        '绘制': 'draw',
        '绘制': 'draw',
        '显示': 'display',
        '显示': 'display',
        '隐藏': 'hide',
        '隐藏': 'hide',
        '显示': 'show',
        '显示': 'show',
        '启用': 'enable',
        '启用': 'enable',
        '禁用': 'disable',
        '禁用': 'disable',
        '允许': 'allow',
        '允许': 'allow',
        '禁止': 'forbid',
        '禁止': 'forbid',
        '拒绝': 'reject',
        '拒绝': 'reject',
        '接受': 'accept',
        '接受': 'accept',
        '忽略': 'ignore',
        '忽略': 'ignore',
        '跳过': 'skip',
        '跳过': 'skip',
        '继续': 'continue',
        '继续': 'continue',
        '中断': 'interrupt',
        '中断': 'interrupt',
        '中止': 'abort',
        '中止': 'abort',
        '终止': 'terminate',
        '终止': 'terminate',
        '完成': 'complete',
        '完成': 'complete',
        '完成': 'finish',
        '完成': 'finish',
        '失败': 'fail',
        '失败': 'fail',
        '成功': 'succeed',
        '成功': 'succeed',
        '错误': 'error',
        '错误': 'error',
        '出错': 'error out',
        '出错': 'error out',
        '崩溃': 'crash',
        '崩溃': 'crash',
        '挂起': 'hang',
        '挂起': 'hang',
        '阻塞': 'block',
        '阻塞': 'block',
        '等待': 'wait',
        '等待': 'wait',
        '通知': 'notify',
        '通知': 'notify',
        '触发': 'trigger',
        '触发': 'trigger',
        '调用': 'call',
        '调用': 'call',
        '调用': 'invoke',
        '调用': 'invoke',
        '执行': 'execute',
        '执行': 'execute',
        '执行': 'run',
        '执行': 'run',
        '运行': 'run',
        '运行': 'run',
        '运行': 'execute',
        '运行': 'operate',
        '操作': 'operate',
        '操作': 'operate',
        '处理': 'process',
        '处理': 'process',
        '处理': 'handle',
        '处理': 'handle',
        '管理': 'manage',
        '管理': 'manage',
        '管理': 'administer',
        '管理': 'administer',
        '控制': 'control',
        '控制': 'control',
        '控制': 'regulate',
        '控制': 'regulate',
        '监控': 'monitor',
        '监控': 'monitor',
        '监控': 'watch',
        '监控': 'watch',
        '观察': 'observe',
        '观察': 'observe',
        '观察': 'watch',
        '观察': 'monitor',
        '记录': 'record',
        '记录': 'record',
        '记录': 'log',
        '记录': 'log',
        '记录': 'track',
        '记录': 'track',
        '跟踪': 'track',
        '跟踪': 'track',
        '跟踪': 'trace',
        '跟踪': 'trace',
        '调试': 'debug',
        '调试': 'debug',
        '调试': 'troubleshoot',
        '调试': 'troubleshoot',
        '测试': 'test',
        '测试': 'test',
        '测试': 'examine',
        '测试': 'check',
        '验证': 'verify',
        '验证': 'validate',
        '验证': 'confirm',
        '验证': 'confirm',
        '确认': 'confirm',
        '确认': 'confirm',
        '确认': 'acknowledge',
        '确认': 'acknowledge',
        '确定': 'determine',
        '确定': 'determine',
        '决定': 'decide',
        '决定': 'decide',
        '选择': 'choose',
        '选择': 'select',
        '选择': 'pick',
        '选择': 'choose',
        '选择': 'select',
        '选择': 'opt'
    },
    
    // Adjectives
    adjectives: {
        '有效的': 'valid',
        '无效的': 'invalid',
        '安全的': 'safe',
        '不安全的': 'unsafe',
        '可用的': 'available',
        '不可用的': 'unavailable',
        '必需的': 'required',
        '可选的': 'optional',
        '推荐的': 'recommended',
        '建议的': 'suggested',
        '默认的': 'default',
        '自定义的': 'custom',
        '标准的': 'standard',
        '规范的': 'standardized',
        '优化的': 'optimized',
        '高效的': 'efficient',
        '高性能的': 'high-performance',
        '低延迟的': 'low-latency',
        '高吞吐量的': 'high-throughput',
        '可扩展的': 'scalable',
        '可维护的': 'maintainable',
        '可读的': 'readable',
        '可靠的': 'reliable',
        '稳定的': 'stable',
        '不稳定的': 'unstable',
        '兼容的': 'compatible',
        '不兼容的': 'incompatible',
        '独立的': 'independent',
        '依赖的': 'dependent',
        '相关的': 'related',
        '无关的': 'unrelated',
        '相似的': 'similar',
        '不同的': 'different',
        '相同的': 'same',
        '相等的': 'equal',
        '不等的': 'unequal',
        '大于': 'greater than',
        '小于': 'less than',
        '等于': 'equal to',
        '不等于': 'not equal to',
        '包含': 'contains',
        '不包含': 'does not contain',
        '属于': 'belongs to',
        '不属于': 'does not belong to',
        '位于': 'located at',
        '位于': 'situated at',
        '存在于': 'exists in',
        '不存在于': 'does not exist in',
        '定义为': 'defined as',
        '定义为': 'defined to be',
        '实现为': 'implemented as',
        '实现为': 'implemented to be',
        '配置为': 'configured as',
        '配置为': 'configured to be',
        '设置为': 'set to',
        '设置为': 'set as',
        '标记为': 'marked as',
        '标记为': 'marked to be',
        '识别为': 'identified as',
        '识别为': 'recognized as',
        '视为': 'considered as',
        '视为': 'treated as',
        '用作': 'used as',
        '用作': 'used for',
        '用作': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'designed for',
        '用于': 'intended for',
        '用于': 'meant for',
        '用于': 'created for',
        '用于': 'built for',
        '用于': 'made for',
        '用于': 'designed to',
        '用于': 'intended to',
        '用于': 'meant to',
        '用于': 'created to',
        '用于': 'built to',
        '用于': 'made to',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to',
        '用于': 'used for',
        '用于': 'used to'
    }
};

// Flatten all translations into a single array for easier processing
const allTranslations = [];
Object.values(translations).forEach(category => {
    Object.entries(category).forEach(([chinese, english]) => {
        allTranslations.push({ chinese, english });
    });
});

// Sort by length (longer phrases first to avoid partial matches)
allTranslations.sort((a, b) => b.chinese.length - a.chinese.length);

let totalTranslated = 0;

allFiles.forEach(filePath => {
    const content = fs.readFileSync(filePath, 'utf8');
    let result = content;
    let changes = 0;
    
    // Only process lines that are comments
    const lines = result.split('\n');
    const processedLines = lines.map(line => {
        // Check if line contains Chinese characters
        if (/[一-龥]/.test(line)) {
            let processedLine = line;
            
            // Apply translations
            allTranslations.forEach(({chinese, english}) => {
                const regex = new RegExp(chinese.replace(/[.*+?^${}()|[\]\\]/g, '\\\\$&'), 'g');
                if (regex.test(processedLine)) {
                    processedLine = processedLine.replace(regex, english);
                    changes++;
                }
            });
            
            return processedLine;
        }
        return line;
    });

    result = processedLines.join('\n');

    if (content !== result) {
        fs.writeFileSync(filePath, result, 'utf8');
        console.log('Translated:', path.basename(filePath), `(${changes} changes)`);
        totalTranslated++;
    }
});

console.log('\nTotal files translated:', totalTranslated);
console.log('Total translation patterns:', allTranslations.length);
