@PACKAGE_INIT@

include(CMakeFindDependencyMacro)

# Find dependencies
find_dependency(Libuv REQUIRED)
if(BUILD_WITH_WEBSOCKET OR BUILD_WITH_HTTPS)
    find_dependency(MbedTLS REQUIRED)
endif()
find_dependency(xxhash REQUIRED)

# Include exported targets
include("${CMAKE_CURRENT_LIST_DIR}/uvhttp-targets.cmake")

# Set package variables
set(UVHTTP_VERSION @UVHTTP_VERSION@)
set(UVHTTP_INCLUDE_DIRS "@CMAKE_INSTALL_FULL_INCLUDEDIR@")
set(UVHTTP_LIBRARIES uvhttp)
set(UVHTTP_LIBRARY_DIRS "@CMAKE_INSTALL_FULL_LIBDIR@")

check_required_components(uvhttp)

# Feature flags
set(UVHTTP_FEATURE_WEBSOCKET @BUILD_WITH_WEBSOCKET@)
set(UVHTTP_FEATURE_HTTPS @BUILD_WITH_HTTPS@)
set(UVHTTP_FEATURE_STATIC_FILES @UVHTTP_FEATURE_STATIC_FILES@)
set(UVHTTP_FEATURE_RATE_LIMIT @UVHTTP_FEATURE_RATE_LIMIT@)
set(UVHTTP_FEATURE_LRU_CACHE @UVHTTP_FEATURE_LRU_CACHE@)
set(UVHTTP_FEATURE_ROUTER_CACHE @UVHTTP_FEATURE_ROUTER_CACHE@)
set(UVHTTP_FEATURE_LOGGING @UVHTTP_FEATURE_LOGGING@)